/*
-- Query: SELECT * FROM tp_bd_2023.actoressecundariospelicula
LIMIT 0, 1000

-- Date: 2023-06-01 20:57
*/
INSERT INTO `` (`TitIngles`,`ActoresSecundarios`) VALUES ('Saving Private Ryan','Tom Sizemore');
INSERT INTO `` (`TitIngles`,`ActoresSecundarios`) VALUES ('The Princess Bride','Mandy Patinkin');
INSERT INTO `` (`TitIngles`,`ActoresSecundarios`) VALUES ('The Lion King II: Simba\'s Pride','Andy Dick (voice)');
INSERT INTO `` (`TitIngles`,`ActoresSecundarios`) VALUES ('Mulan','Ming-Na Wen (voice)');
INSERT INTO `` (`TitIngles`,`ActoresSecundarios`) VALUES ('The Social Network','Jesse Eisenberg');
INSERT INTO `` (`TitIngles`,`ActoresSecundarios`) VALUES ('Gone with the Wind','Clark Gable');
INSERT INTO `` (`TitIngles`,`ActoresSecundarios`) VALUES ('The Breakfast Club','Judd Nelson');
INSERT INTO `` (`TitIngles`,`ActoresSecundarios`) VALUES ('Pulp Fiction','John Travolta');
INSERT INTO `` (`TitIngles`,`ActoresSecundarios`) VALUES ('The Sixth Sense','Bruce Willis');
INSERT INTO `` (`TitIngles`,`ActoresSecundarios`) VALUES ('2001: A Space Odyssey','Gary Lockwood');
INSERT INTO `` (`TitIngles`,`ActoresSecundarios`) VALUES ('Titanic','Leonardo DiCaprio');
INSERT INTO `` (`TitIngles`,`ActoresSecundarios`) VALUES ('Star Wars: Episode IV - A New Hope','Mark Hamill');
INSERT INTO `` (`TitIngles`,`ActoresSecundarios`) VALUES ('The Hateful Eight','Samuel L. Jackson');
INSERT INTO `` (`TitIngles`,`ActoresSecundarios`) VALUES ('Star Wars: Episode I - The Phantom Menace','Ewan McGregor');
INSERT INTO `` (`TitIngles`,`ActoresSecundarios`) VALUES ('The Lord of the Rings: The Return of the King','Sean Astin');
INSERT INTO `` (`TitIngles`,`ActoresSecundarios`) VALUES ('Star Wars: Episode II - Attack of the Clones','Hayden Christensen');
INSERT INTO `` (`TitIngles`,`ActoresSecundarios`) VALUES ('The Matrix','Keanu Reeves');
INSERT INTO `` (`TitIngles`,`ActoresSecundarios`) VALUES ('The Iron Giant','Vin Diesel (voice)');
INSERT INTO `` (`TitIngles`,`ActoresSecundarios`) VALUES ('Aladdin','Scott Weinger (voice)');
INSERT INTO `` (`TitIngles`,`ActoresSecundarios`) VALUES ('Star Wars: Episode III - Revenge of the Sith','Ewan McGregor');
INSERT INTO `` (`TitIngles`,`ActoresSecundarios`) VALUES ('The Exorcist','Linda Blair');
INSERT INTO `` (`TitIngles`,`ActoresSecundarios`) VALUES ('Goodfellas','Jamie Foxx');
INSERT INTO `` (`TitIngles`,`ActoresSecundarios`) VALUES ('Django Unchained','Albert Brooks (voice)');
INSERT INTO `` (`TitIngles`,`ActoresSecundarios`) VALUES ('Nemo','Jodi Benson (voice)');
INSERT INTO `` (`TitIngles`,`ActoresSecundarios`) VALUES ('The Little Mermaid','Nicole Kidman');
INSERT INTO `` (`TitIngles`,`ActoresSecundarios`) VALUES ('The Others','Mel Gibson');
INSERT INTO `` (`TitIngles`,`ActoresSecundarios`) VALUES ('Signs','Tim Robbins');
INSERT INTO `` (`TitIngles`,`ActoresSecundarios`) VALUES ('The Shawshank Redemption','Tom Hanks (voice)');
INSERT INTO `` (`TitIngles`,`ActoresSecundarios`) VALUES ('Toy Story','Jodie Foster');
INSERT INTO `` (`TitIngles`,`ActoresSecundarios`) VALUES ('The Silence of the Lambs','Harrison Ford');
INSERT INTO `` (`TitIngles`,`ActoresSecundarios`) VALUES ('Fight Club','Craig T. Nelson (voice)');
INSERT INTO `` (`TitIngles`,`ActoresSecundarios`) VALUES ('The Incredibles','Ralph Fiennes');
INSERT INTO `` (`TitIngles`,`ActoresSecundarios`) VALUES ('The Grand Budapest Hotel','Sam Neill');
INSERT INTO `` (`TitIngles`,`ActoresSecundarios`) VALUES ('Jurassic Park','Daniel Radcliffe');
INSERT INTO `` (`TitIngles`,`ActoresSecundarios`) VALUES ('Harry Potter and the Philosopher\'s Stone','Andy Garcia');
INSERT INTO `` (`TitIngles`,`ActoresSecundarios`) VALUES ('The Godfather: Part III','Ed Harris');
INSERT INTO `` (`TitIngles`,`ActoresSecundarios`) VALUES ('The Truman Show','Robert De Niro');
INSERT INTO `` (`TitIngles`,`ActoresSecundarios`) VALUES ('The Godfather: Part II','Ray Bolger');
INSERT INTO `` (`TitIngles`,`ActoresSecundarios`) VALUES ('The Wizard of Oz','Rupert Grint');
INSERT INTO `` (`TitIngles`,`ActoresSecundarios`) VALUES ('Harry Potter and the Chamber of Secrets','Amy Poehler (voice)');
INSERT INTO `` (`TitIngles`,`ActoresSecundarios`) VALUES ('Inside Out','Emma Watson');
INSERT INTO `` (`TitIngles`,`ActoresSecundarios`) VALUES ('Harry Potter and the Prisoner of Azkaban','Leonardo DiCaprio');
INSERT INTO `` (`TitIngles`,`ActoresSecundarios`) VALUES ('The Departed','Rupert Grint');
INSERT INTO `` (`TitIngles`,`ActoresSecundarios`) VALUES ('Harry Potter and the Goblet of Fire','Emma Watson');
INSERT INTO `` (`TitIngles`,`ActoresSecundarios`) VALUES ('Harry Potter and the Order of the Phoenix','Rupert Grint');
INSERT INTO `` (`TitIngles`,`ActoresSecundarios`) VALUES ('Harry Potter and the Half-Blood Prince','Harrison Ford');
INSERT INTO `` (`TitIngles`,`ActoresSecundarios`) VALUES ('Star Wars: Episode VI - Return of the Jedi','Steven Strait');
INSERT INTO `` (`TitIngles`,`ActoresSecundarios`) VALUES ('Saving Private Ryan','Tom Hardy');
INSERT INTO `` (`TitIngles`,`ActoresSecundarios`) VALUES ('The Princess Bride','Christoph Waltz');
INSERT INTO `` (`TitIngles`,`ActoresSecundarios`) VALUES ('The Lion King II: Simba\'s Pride','Anne Hathaway');
INSERT INTO `` (`TitIngles`,`ActoresSecundarios`) VALUES ('Mulan','Samuel L. Jackson');
INSERT INTO `` (`TitIngles`,`ActoresSecundarios`) VALUES ('The Social Network','Bill Murray');
INSERT INTO `` (`TitIngles`,`ActoresSecundarios`) VALUES ('Gone with the Wind','Scarlett Johansson');
INSERT INTO `` (`TitIngles`,`ActoresSecundarios`) VALUES ('The Breakfast Club','Jake Gyllenhaal');
INSERT INTO `` (`TitIngles`,`ActoresSecundarios`) VALUES ('Pulp Fiction','Cate Blanchett');
INSERT INTO `` (`TitIngles`,`ActoresSecundarios`) VALUES ('The Sixth Sense','Bradley Cooper');
INSERT INTO `` (`TitIngles`,`ActoresSecundarios`) VALUES ('2001: A Space Odyssey','Octavia Spencer');
INSERT INTO `` (`TitIngles`,`ActoresSecundarios`) VALUES ('Titanic','Tilda Swinton');
INSERT INTO `` (`TitIngles`,`ActoresSecundarios`) VALUES ('Star Wars: Episode IV - A New Hope','Anthony Mackie');
INSERT INTO `` (`TitIngles`,`ActoresSecundarios`) VALUES ('The Hateful Eight','Kate Winslet');
INSERT INTO `` (`TitIngles`,`ActoresSecundarios`) VALUES ('Star Wars: Episode I - The Phantom Menace','Morgan Freeman');
INSERT INTO `` (`TitIngles`,`ActoresSecundarios`) VALUES ('The Lord of the Rings: The Return of the King','Charlize Theron');
INSERT INTO `` (`TitIngles`,`ActoresSecundarios`) VALUES ('Star Wars: Episode II - Attack of the Clones','Jude Law');
INSERT INTO `` (`TitIngles`,`ActoresSecundarios`) VALUES ('The Matrix','Marion Cotillard');
INSERT INTO `` (`TitIngles`,`ActoresSecundarios`) VALUES ('The Iron Giant','Michael Fassbender');
INSERT INTO `` (`TitIngles`,`ActoresSecundarios`) VALUES ('Aladdin','Gary Oldman');
INSERT INTO `` (`TitIngles`,`ActoresSecundarios`) VALUES ('Star Wars: Episode III - Revenge of the Sith','Emily Blunt');
INSERT INTO `` (`TitIngles`,`ActoresSecundarios`) VALUES ('The Exorcist','Javier Bardem');
INSERT INTO `` (`TitIngles`,`ActoresSecundarios`) VALUES ('Goodfellas','Saoirse Ronan');
INSERT INTO `` (`TitIngles`,`ActoresSecundarios`) VALUES ('Django Unchained','Willem Dafoe');
INSERT INTO `` (`TitIngles`,`ActoresSecundarios`) VALUES ('Nemo','Julianne Moore');
INSERT INTO `` (`TitIngles`,`ActoresSecundarios`) VALUES ('The Little Mermaid','Mark Ruffalo');
INSERT INTO `` (`TitIngles`,`ActoresSecundarios`) VALUES ('The Others','Jessica Chastain');
INSERT INTO `` (`TitIngles`,`ActoresSecundarios`) VALUES ('Signs','Ralph Fiennes');
INSERT INTO `` (`TitIngles`,`ActoresSecundarios`) VALUES ('The Shawshank Redemption','Christoph Waltz');
INSERT INTO `` (`TitIngles`,`ActoresSecundarios`) VALUES ('Toy Story','Saoirse Ronan');
INSERT INTO `` (`TitIngles`,`ActoresSecundarios`) VALUES ('The Silence of the Lambs','Octavia Spencer');
INSERT INTO `` (`TitIngles`,`ActoresSecundarios`) VALUES ('Fight Club','Richard Jenkins');
INSERT INTO `` (`TitIngles`,`ActoresSecundarios`) VALUES ('The Incredibles','Viola Davis');
INSERT INTO `` (`TitIngles`,`ActoresSecundarios`) VALUES ('The Grand Budapest Hotel','Sam Rockwell');
INSERT INTO `` (`TitIngles`,`ActoresSecundarios`) VALUES ('Jurassic Park','Michelle Williams');
INSERT INTO `` (`TitIngles`,`ActoresSecundarios`) VALUES ('Harry Potter and the Philosopher\'s Stone','Jonah Hill');
INSERT INTO `` (`TitIngles`,`ActoresSecundarios`) VALUES ('The Godfather: Part III','Amy Adams');
INSERT INTO `` (`TitIngles`,`ActoresSecundarios`) VALUES ('The Truman Show','Mahershala Ali');
INSERT INTO `` (`TitIngles`,`ActoresSecundarios`) VALUES ('The Godfather: Part II','Emma Stone');
INSERT INTO `` (`TitIngles`,`ActoresSecundarios`) VALUES ('The Wizard of Oz','Steve Carell');
INSERT INTO `` (`TitIngles`,`ActoresSecundarios`) VALUES ('Harry Potter and the Chamber of Secrets','Nicole Kidman');
INSERT INTO `` (`TitIngles`,`ActoresSecundarios`) VALUES ('Inside Out','Ryan Gosling');
INSERT INTO `` (`TitIngles`,`ActoresSecundarios`) VALUES ('Harry Potter and the Prisoner of Azkaban','Tom Hanks');
INSERT INTO `` (`TitIngles`,`ActoresSecundarios`) VALUES ('The Departed','Julia Roberts');
INSERT INTO `` (`TitIngles`,`ActoresSecundarios`) VALUES ('Harry Potter and the Goblet of Fire','Jude Law');
INSERT INTO `` (`TitIngles`,`ActoresSecundarios`) VALUES ('Harry Potter and the Order of the Phoenix','Natalie Portman');
INSERT INTO `` (`TitIngles`,`ActoresSecundarios`) VALUES ('Harry Potter and the Half-Blood Prince','Michael Shannon');
INSERT INTO `` (`TitIngles`,`ActoresSecundarios`) VALUES ('Star Wars: Episode VI - Return of the Jedi','Frances McDormand');
