/*
-- Query: SELECT * FROM tp_bd_2023.historial
LIMIT 0, 1000

-- Date: 2023-06-01 21:04
*/
INSERT INTO `` (`idContenido`,`Nombre`,`Fecha`,`Audio`,`Seleccionado`) VALUES (1291,'Piper Dunbabin','2019-06-23','Castellano','ninguno');
INSERT INTO `` (`idContenido`,`Nombre`,`Fecha`,`Audio`,`Seleccionado`) VALUES (1037,'Otes Brideaux','2020-09-14','Castellano','ninguno');
INSERT INTO `` (`idContenido`,`Nombre`,`Fecha`,`Audio`,`Seleccionado`) VALUES (875,'Hunter Fife','2021-04-30','Castellano','ninguno');
INSERT INTO `` (`idContenido`,`Nombre`,`Fecha`,`Audio`,`Seleccionado`) VALUES (1574,'Ronny Flahy','2018-12-17','Castellano','ninguno');
INSERT INTO `` (`idContenido`,`Nombre`,`Fecha`,`Audio`,`Seleccionado`) VALUES (684,'Ketty Mewton','2022-07-05','Castellano','ninguno');
INSERT INTO `` (`idContenido`,`Nombre`,`Fecha`,`Audio`,`Seleccionado`) VALUES (152,'Becky Crome','2019-02-11','Castellano','ninguno');
INSERT INTO `` (`idContenido`,`Nombre`,`Fecha`,`Audio`,`Seleccionado`) VALUES (422,'Tybalt Rummery','2022-01-27','Castellano','ninguno');
INSERT INTO `` (`idContenido`,`Nombre`,`Fecha`,`Audio`,`Seleccionado`) VALUES (764,'Thalia Cusick','2021-10-02','Castellano','ninguno');
INSERT INTO `` (`idContenido`,`Nombre`,`Fecha`,`Audio`,`Seleccionado`) VALUES (759,'Berna Grocutt','2020-05-19','Castellano','ninguno');
INSERT INTO `` (`idContenido`,`Nombre`,`Fecha`,`Audio`,`Seleccionado`) VALUES (1801,'Sandor Zelley','2018-11-08','Castellano','ninguno');
INSERT INTO `` (`idContenido`,`Nombre`,`Fecha`,`Audio`,`Seleccionado`) VALUES (742,'Sebastiano Ottey','2023-03-12','Castellano','ninguno');
INSERT INTO `` (`idContenido`,`Nombre`,`Fecha`,`Audio`,`Seleccionado`) VALUES (1987,'Ellen Blasiak','2020-03-29','Castellano','ninguno');
INSERT INTO `` (`idContenido`,`Nombre`,`Fecha`,`Audio`,`Seleccionado`) VALUES (1330,'Arlyne Carme','2022-05-21','Castellano','ninguno');
INSERT INTO `` (`idContenido`,`Nombre`,`Fecha`,`Audio`,`Seleccionado`) VALUES (1082,'Sigvard Ditchburn','2019-07-06','Castellano','ninguno');
INSERT INTO `` (`idContenido`,`Nombre`,`Fecha`,`Audio`,`Seleccionado`) VALUES (1692,'Warren Jaimez','2023-01-09','Castellano','ninguno');
INSERT INTO `` (`idContenido`,`Nombre`,`Fecha`,`Audio`,`Seleccionado`) VALUES (1092,'Aubert Benaine','2021-09-18','Castellano','ninguno');
INSERT INTO `` (`idContenido`,`Nombre`,`Fecha`,`Audio`,`Seleccionado`) VALUES (1104,'Rhona Abbess','2018-08-27','Castellano','ninguno');
INSERT INTO `` (`idContenido`,`Nombre`,`Fecha`,`Audio`,`Seleccionado`) VALUES (1321,'Marie Whorlton','2022-08-08','Ingles','ninguno');
INSERT INTO `` (`idContenido`,`Nombre`,`Fecha`,`Audio`,`Seleccionado`) VALUES (1815,'Hedda Di Giacomettino','2019-03-24','Ingles','ninguno');
INSERT INTO `` (`idContenido`,`Nombre`,`Fecha`,`Audio`,`Seleccionado`) VALUES (140,'Bernarr Graybeal','2021-05-03','Ingles','ninguno');
INSERT INTO `` (`idContenido`,`Nombre`,`Fecha`,`Audio`,`Seleccionado`) VALUES (1093,'Chauncey Juniper','2020-01-15','Ingles','ninguno');
INSERT INTO `` (`idContenido`,`Nombre`,`Fecha`,`Audio`,`Seleccionado`) VALUES (572,'Janenna Rodgers','2018-10-21','Ingles','castellano');
INSERT INTO `` (`idContenido`,`Nombre`,`Fecha`,`Audio`,`Seleccionado`) VALUES (568,'Cortney Giacomuzzi','2023-02-20','Ingles','castellano');
INSERT INTO `` (`idContenido`,`Nombre`,`Fecha`,`Audio`,`Seleccionado`) VALUES (1545,'Ichabod Beeching','2019-08-10','Ingles','castellano');
INSERT INTO `` (`idContenido`,`Nombre`,`Fecha`,`Audio`,`Seleccionado`) VALUES (1005,'Velvet Attack','2022-10-26','Ingles','castellano');
INSERT INTO `` (`idContenido`,`Nombre`,`Fecha`,`Audio`,`Seleccionado`) VALUES (1818,'Melody Swinburn','2020-07-13','Ingles','castellano');
INSERT INTO `` (`idContenido`,`Nombre`,`Fecha`,`Audio`,`Seleccionado`) VALUES (301,'Kimmy Eaken','2021-03-02','Ingles','castellano');
INSERT INTO `` (`idContenido`,`Nombre`,`Fecha`,`Audio`,`Seleccionado`) VALUES (802,'Zechariah Dessant','2018-12-19','Ingles','castellano');
INSERT INTO `` (`idContenido`,`Nombre`,`Fecha`,`Audio`,`Seleccionado`) VALUES (307,'Estevan Addams','2022-06-24','Ingles','castellano');
INSERT INTO `` (`idContenido`,`Nombre`,`Fecha`,`Audio`,`Seleccionado`) VALUES (1308,'Madelon Kagan','2019-01-31','Ingles','castellano');
INSERT INTO `` (`idContenido`,`Nombre`,`Fecha`,`Audio`,`Seleccionado`) VALUES (793,'Marcello Kliesl','2023-05-06','Original','castellano');
INSERT INTO `` (`idContenido`,`Nombre`,`Fecha`,`Audio`,`Seleccionado`) VALUES (925,'Jorgan Fordham','2020-11-15','Original','castellano');
INSERT INTO `` (`idContenido`,`Nombre`,`Fecha`,`Audio`,`Seleccionado`) VALUES (1006,'Halimeda Thornham','2021-06-03','Original','castellano');
INSERT INTO `` (`idContenido`,`Nombre`,`Fecha`,`Audio`,`Seleccionado`) VALUES (1587,'Tarah Petrozzi','2018-09-13','Original','castellano');
INSERT INTO `` (`idContenido`,`Nombre`,`Fecha`,`Audio`,`Seleccionado`) VALUES (1308,'Alexandros Presley','2022-04-21','Original','castellano');
INSERT INTO `` (`idContenido`,`Nombre`,`Fecha`,`Audio`,`Seleccionado`) VALUES (793,'Margaretha Kloss','2019-06-07','Original','castellano');
INSERT INTO `` (`idContenido`,`Nombre`,`Fecha`,`Audio`,`Seleccionado`) VALUES (925,'Regen Tumelty','2023-01-23','Original','castellano');
INSERT INTO `` (`idContenido`,`Nombre`,`Fecha`,`Audio`,`Seleccionado`) VALUES (1006,'Meaghan Pittel','2020-09-08','Original','castellano');
INSERT INTO `` (`idContenido`,`Nombre`,`Fecha`,`Audio`,`Seleccionado`) VALUES (1587,'Delcina Alishoner','2021-11-12','Original','castellano');
INSERT INTO `` (`idContenido`,`Nombre`,`Fecha`,`Audio`,`Seleccionado`) VALUES (1186,'Maggy Chartres','2018-05-30','Original','castellano');
INSERT INTO `` (`idContenido`,`Nombre`,`Fecha`,`Audio`,`Seleccionado`) VALUES (275,'Ilise Manoelli','2019-03-10','Original','castellano');
INSERT INTO `` (`idContenido`,`Nombre`,`Fecha`,`Audio`,`Seleccionado`) VALUES (1560,'Cassius Dorre','2022-02-14','Original','castellano');
INSERT INTO `` (`idContenido`,`Nombre`,`Fecha`,`Audio`,`Seleccionado`) VALUES (5,'Iris Crumly','2020-01-26','Original','castellano');
INSERT INTO `` (`idContenido`,`Nombre`,`Fecha`,`Audio`,`Seleccionado`) VALUES (1566,'Wynny Kenn','2023-03-31','Original','ingles');
INSERT INTO `` (`idContenido`,`Nombre`,`Fecha`,`Audio`,`Seleccionado`) VALUES (26,'Casar Mion','2021-10-05','Original','ingles');
INSERT INTO `` (`idContenido`,`Nombre`,`Fecha`,`Audio`,`Seleccionado`) VALUES (384,'Delly Danielsohn','2018-08-15','Original','ingles');
INSERT INTO `` (`idContenido`,`Nombre`,`Fecha`,`Audio`,`Seleccionado`) VALUES (158,'Josie Churchill','2022-08-20','Original','ingles');
INSERT INTO `` (`idContenido`,`Nombre`,`Fecha`,`Audio`,`Seleccionado`) VALUES (615,'Marline Liccardi','2019-07-28','Original','ingles');
INSERT INTO `` (`idContenido`,`Nombre`,`Fecha`,`Audio`,`Seleccionado`) VALUES (1276,'Velma Donisthorpe','2021-05-10','Original','ingles');
INSERT INTO `` (`idContenido`,`Nombre`,`Fecha`,`Audio`,`Seleccionado`) VALUES (680,'Vergil Wintringham','2020-03-17','Original','ingles');
INSERT INTO `` (`idContenido`,`Nombre`,`Fecha`,`Audio`,`Seleccionado`) VALUES (1051,'Orelia Lotze','2018-11-27','Original','ingles');
INSERT INTO `` (`idContenido`,`Nombre`,`Fecha`,`Audio`,`Seleccionado`) VALUES (1925,'Lanie Abeau','2022-05-30','Original','ingles');
INSERT INTO `` (`idContenido`,`Nombre`,`Fecha`,`Audio`,`Seleccionado`) VALUES (917,'Beverlee Phelps','2019-01-14','Original','ingles');
INSERT INTO `` (`idContenido`,`Nombre`,`Fecha`,`Audio`,`Seleccionado`) VALUES (604,'Karoly Nanson','2023-02-25','Original','ingles');
INSERT INTO `` (`idContenido`,`Nombre`,`Fecha`,`Audio`,`Seleccionado`) VALUES (1143,'Rodie Spellward','2020-12-02','Original','ingles');
INSERT INTO `` (`idContenido`,`Nombre`,`Fecha`,`Audio`,`Seleccionado`) VALUES (1872,'Madelon Kagan','2021-06-18','Original','ingles');
INSERT INTO `` (`idContenido`,`Nombre`,`Fecha`,`Audio`,`Seleccionado`) VALUES (145,'Torr Bramer','2018-09-05','Original','ingles');
INSERT INTO `` (`idContenido`,`Nombre`,`Fecha`,`Audio`,`Seleccionado`) VALUES (1462,'Trace Janaszkiewicz','2022-04-05','Castellano','ingles');
INSERT INTO `` (`idContenido`,`Nombre`,`Fecha`,`Audio`,`Seleccionado`) VALUES (1862,'Beatrice Watterson','2019-05-22','Castellano','ingles');
INSERT INTO `` (`idContenido`,`Nombre`,`Fecha`,`Audio`,`Seleccionado`) VALUES (1598,'Florette Khan','2023-01-05','Castellano','ingles');
INSERT INTO `` (`idContenido`,`Nombre`,`Fecha`,`Audio`,`Seleccionado`) VALUES (178,'Marcello Kliesl','2020-10-15','Castellano','ingles');
INSERT INTO `` (`idContenido`,`Nombre`,`Fecha`,`Audio`,`Seleccionado`) VALUES (1487,'Jorgan Fordham','2021-02-23','Castellano','ingles');
INSERT INTO `` (`idContenido`,`Nombre`,`Fecha`,`Audio`,`Seleccionado`) VALUES (1226,'Halimeda Thornham','2018-07-11','Castellano','ingles');
INSERT INTO `` (`idContenido`,`Nombre`,`Fecha`,`Audio`,`Seleccionado`) VALUES (1654,'Tarah Petrozzi','2022-07-26','Castellano','ingles');
INSERT INTO `` (`idContenido`,`Nombre`,`Fecha`,`Audio`,`Seleccionado`) VALUES (867,'Alexandros Presley','2019-08-31','Castellano','ingles');
INSERT INTO `` (`idContenido`,`Nombre`,`Fecha`,`Audio`,`Seleccionado`) VALUES (1706,'Margaretha Kloss','2020-06-15','Castellano','ingles');
INSERT INTO `` (`idContenido`,`Nombre`,`Fecha`,`Audio`,`Seleccionado`) VALUES (1573,'Regen Tumelty','2023-04-20','Castellano','ingles');
INSERT INTO `` (`idContenido`,`Nombre`,`Fecha`,`Audio`,`Seleccionado`) VALUES (915,'Meaghan Pittel','2021-10-25','Castellano','ingles');
INSERT INTO `` (`idContenido`,`Nombre`,`Fecha`,`Audio`,`Seleccionado`) VALUES (1048,'Delcina Alishoner','2018-08-02','Castellano','ingles');
INSERT INTO `` (`idContenido`,`Nombre`,`Fecha`,`Audio`,`Seleccionado`) VALUES (252,'Maggy Chartres','2022-08-17','Castellano','ingles');
INSERT INTO `` (`idContenido`,`Nombre`,`Fecha`,`Audio`,`Seleccionado`) VALUES (310,'Ilise Manoelli','2019-06-03','Castellano','ingles');
INSERT INTO `` (`idContenido`,`Nombre`,`Fecha`,`Audio`,`Seleccionado`) VALUES (1466,'Cassius Dorre','2021-04-13','Castellano','ingles');
INSERT INTO `` (`idContenido`,`Nombre`,`Fecha`,`Audio`,`Seleccionado`) VALUES (789,'Iris Crumly','2020-01-25','Castellano','ingles');
INSERT INTO `` (`idContenido`,`Nombre`,`Fecha`,`Audio`,`Seleccionado`) VALUES (1938,'Wynny Kenn','2018-11-20','Castellano','ingles');
INSERT INTO `` (`idContenido`,`Nombre`,`Fecha`,`Audio`,`Seleccionado`) VALUES (376,'Casar Mion','2023-03-25','Castellano','ingles');
INSERT INTO `` (`idContenido`,`Nombre`,`Fecha`,`Audio`,`Seleccionado`) VALUES (707,'Delly Danielsohn','2020-12-08','Castellano','portugues');
INSERT INTO `` (`idContenido`,`Nombre`,`Fecha`,`Audio`,`Seleccionado`) VALUES (1583,'Josie Churchill','2021-06-27','Castellano','portugues');
INSERT INTO `` (`idContenido`,`Nombre`,`Fecha`,`Audio`,`Seleccionado`) VALUES (24,'Marline Liccardi','2018-09-12','Castellano','portugues');
INSERT INTO `` (`idContenido`,`Nombre`,`Fecha`,`Audio`,`Seleccionado`) VALUES (1278,'Velma Donisthorpe','2022-04-09','Castellano','portugues');
INSERT INTO `` (`idContenido`,`Nombre`,`Fecha`,`Audio`,`Seleccionado`) VALUES (300,'Vergil Wintringham','2019-05-19','Castellano','portugues');
INSERT INTO `` (`idContenido`,`Nombre`,`Fecha`,`Audio`,`Seleccionado`) VALUES (1119,'Orelia Lotze','2023-01-08','Castellano','portugues');
INSERT INTO `` (`idContenido`,`Nombre`,`Fecha`,`Audio`,`Seleccionado`) VALUES (1997,'Lanie Abeau','2020-10-19','Ingles','portugues');
INSERT INTO `` (`idContenido`,`Nombre`,`Fecha`,`Audio`,`Seleccionado`) VALUES (915,'Beverlee Phelps','2021-03-03','Ingles','portugues');
INSERT INTO `` (`idContenido`,`Nombre`,`Fecha`,`Audio`,`Seleccionado`) VALUES (1048,'Karoly Nanson','2018-07-18','Ingles','portugues');
INSERT INTO `` (`idContenido`,`Nombre`,`Fecha`,`Audio`,`Seleccionado`) VALUES (252,'Rodie Spellward','2022-07-31','Ingles','portugues');
INSERT INTO `` (`idContenido`,`Nombre`,`Fecha`,`Audio`,`Seleccionado`) VALUES (310,'Mohammed Haking','2019-08-23','Ingles','portugues');
INSERT INTO `` (`idContenido`,`Nombre`,`Fecha`,`Audio`,`Seleccionado`) VALUES (1466,'Edmund Von Helmholtz','2020-06-07','Ingles','portugues');
INSERT INTO `` (`idContenido`,`Nombre`,`Fecha`,`Audio`,`Seleccionado`) VALUES (789,'Brice Ord','2023-04-07','Ingles','portugues');
INSERT INTO `` (`idContenido`,`Nombre`,`Fecha`,`Audio`,`Seleccionado`) VALUES (1938,'Shari Drewe','2021-11-09','Ingles','portugues');
INSERT INTO `` (`idContenido`,`Nombre`,`Fecha`,`Audio`,`Seleccionado`) VALUES (376,'Salomi Sampey','2018-04-29','Ingles','portugues');
INSERT INTO `` (`idContenido`,`Nombre`,`Fecha`,`Audio`,`Seleccionado`) VALUES (707,'Dolorita Scamp','2019-02-05','Ingles','portugues');
INSERT INTO `` (`idContenido`,`Nombre`,`Fecha`,`Audio`,`Seleccionado`) VALUES (1583,'Joellyn Robottham','2022-01-09','Ingles','portugues');
INSERT INTO `` (`idContenido`,`Nombre`,`Fecha`,`Audio`,`Seleccionado`) VALUES (24,'Wilma Robottham','2020-10-22','Ingles','italianoÂ ');
INSERT INTO `` (`idContenido`,`Nombre`,`Fecha`,`Audio`,`Seleccionado`) VALUES (1278,'Fran Danbi','2023-03-17','Ingles','italianoÂ ');
INSERT INTO `` (`idContenido`,`Nombre`,`Fecha`,`Audio`,`Seleccionado`) VALUES (300,'Margaretha Kloss','2021-09-27','Ingles','italianoÂ ');
INSERT INTO `` (`idContenido`,`Nombre`,`Fecha`,`Audio`,`Seleccionado`) VALUES (1119,'Regen Tumelty','2018-08-04','Ingles','italianoÂ ');
INSERT INTO `` (`idContenido`,`Nombre`,`Fecha`,`Audio`,`Seleccionado`) VALUES (1997,'Meaghan Pittel','2022-08-31','Ingles','italianoÂ ');
INSERT INTO `` (`idContenido`,`Nombre`,`Fecha`,`Audio`,`Seleccionado`) VALUES (1992,'Delcina Alishoner','2019-06-16','Ingles','italianoÂ ');
INSERT INTO `` (`idContenido`,`Nombre`,`Fecha`,`Audio`,`Seleccionado`) VALUES (335,'Maggy Chartres','2021-04-02','Ingles','italianoÂ ');
INSERT INTO `` (`idContenido`,`Nombre`,`Fecha`,`Audio`,`Seleccionado`) VALUES (905,'Ilise Manoelli','2020-01-13','Ingles','italianoÂ ');
INSERT INTO `` (`idContenido`,`Nombre`,`Fecha`,`Audio`,`Seleccionado`) VALUES (767,'Cassius Dorre','2018-11-14','Ingles','italianoÂ ');
INSERT INTO `` (`idContenido`,`Nombre`,`Fecha`,`Audio`,`Seleccionado`) VALUES (785,'Iris Crumly','2023-03-19','Ingles','italianoÂ ');
INSERT INTO `` (`idContenido`,`Nombre`,`Fecha`,`Audio`,`Seleccionado`) VALUES (1510,'Wynny Kenn','2020-12-06','Ingles','italianoÂ ');
INSERT INTO `` (`idContenido`,`Nombre`,`Fecha`,`Audio`,`Seleccionado`) VALUES (1948,'Casar Mion','2021-06-20','Ingles','italianoÂ ');
INSERT INTO `` (`idContenido`,`Nombre`,`Fecha`,`Audio`,`Seleccionado`) VALUES (1590,'Delly Danielsohn','2018-09-11','Original','italianoÂ ');
INSERT INTO `` (`idContenido`,`Nombre`,`Fecha`,`Audio`,`Seleccionado`) VALUES (383,'Josie Churchill','2022-04-07','Original','frances');
INSERT INTO `` (`idContenido`,`Nombre`,`Fecha`,`Audio`,`Seleccionado`) VALUES (304,'Marline Liccardi','2019-05-15','Original','frances');
INSERT INTO `` (`idContenido`,`Nombre`,`Fecha`,`Audio`,`Seleccionado`) VALUES (70,'Velma Donisthorpe','2023-01-02','Original','frances');
INSERT INTO `` (`idContenido`,`Nombre`,`Fecha`,`Audio`,`Seleccionado`) VALUES (870,'Vergil Wintringham','2020-10-17','Original','frances');
INSERT INTO `` (`idContenido`,`Nombre`,`Fecha`,`Audio`,`Seleccionado`) VALUES (226,'Orelia Lotze','2021-03-05','Original','frances');
INSERT INTO `` (`idContenido`,`Nombre`,`Fecha`,`Audio`,`Seleccionado`) VALUES (1147,'Lanie Abeau','2018-07-23','Original','frances');
INSERT INTO `` (`idContenido`,`Nombre`,`Fecha`,`Audio`,`Seleccionado`) VALUES (1269,'Beverlee Phelps','2022-07-28','Original','frances');
INSERT INTO `` (`idContenido`,`Nombre`,`Fecha`,`Audio`,`Seleccionado`) VALUES (567,'Karoly Nanson','2019-08-18','Original','frances');
INSERT INTO `` (`idContenido`,`Nombre`,`Fecha`,`Audio`,`Seleccionado`) VALUES (1512,'Rodie Spellward','2020-06-03','Original','frances');
INSERT INTO `` (`idContenido`,`Nombre`,`Fecha`,`Audio`,`Seleccionado`) VALUES (836,'Mohammed Haking','2023-04-14','Original','frances');
INSERT INTO `` (`idContenido`,`Nombre`,`Fecha`,`Audio`,`Seleccionado`) VALUES (1198,'Edmund Von Helmholtz','2021-10-29','Original','frances');
INSERT INTO `` (`idContenido`,`Nombre`,`Fecha`,`Audio`,`Seleccionado`) VALUES (755,'Brice Ord','2018-04-26','Original','frances');
INSERT INTO `` (`idContenido`,`Nombre`,`Fecha`,`Audio`,`Seleccionado`) VALUES (1012,'Shari Drewe','2019-01-30','Original','frances');
INSERT INTO `` (`idContenido`,`Nombre`,`Fecha`,`Audio`,`Seleccionado`) VALUES (1422,'Salomi Sampey','2022-01-23','Original','frances');
INSERT INTO `` (`idContenido`,`Nombre`,`Fecha`,`Audio`,`Seleccionado`) VALUES (1707,'Dolorita Scamp','2020-10-03','Original','frances');
INSERT INTO `` (`idContenido`,`Nombre`,`Fecha`,`Audio`,`Seleccionado`) VALUES (1552,'Joellyn Robottham','2023-03-21','Original','frances');
INSERT INTO `` (`idContenido`,`Nombre`,`Fecha`,`Audio`,`Seleccionado`) VALUES (1745,'Wilma Robottham','2021-09-22','Original','ninguno');
INSERT INTO `` (`idContenido`,`Nombre`,`Fecha`,`Audio`,`Seleccionado`) VALUES (1473,'Fran Danbi','2018-08-10','Original','ninguno');
INSERT INTO `` (`idContenido`,`Nombre`,`Fecha`,`Audio`,`Seleccionado`) VALUES (149,'Marcie Masarrat','2022-09-04','Original','ninguno');
INSERT INTO `` (`idContenido`,`Nombre`,`Fecha`,`Audio`,`Seleccionado`) VALUES (1041,'Darsey Mansfield','2019-06-12','Original','ninguno');
INSERT INTO `` (`idContenido`,`Nombre`,`Fecha`,`Audio`,`Seleccionado`) VALUES (1404,'Gigi Costello','2021-03-29','Original','ninguno');
INSERT INTO `` (`idContenido`,`Nombre`,`Fecha`,`Audio`,`Seleccionado`) VALUES (1512,'Darleen Rickis','2020-01-05','Original','castellano');
INSERT INTO `` (`idContenido`,`Nombre`,`Fecha`,`Audio`,`Seleccionado`) VALUES (836,'Caryl Shipperbottom','2018-11-03','Original','castellano');
INSERT INTO `` (`idContenido`,`Nombre`,`Fecha`,`Audio`,`Seleccionado`) VALUES (1198,'Peadar Giddings','2023-02-26','Original','castellano');
INSERT INTO `` (`idContenido`,`Nombre`,`Fecha`,`Audio`,`Seleccionado`) VALUES (755,'Rozalie Saltwell','2020-12-03','Ingles','castellano');
INSERT INTO `` (`idContenido`,`Nombre`,`Fecha`,`Audio`,`Seleccionado`) VALUES (1012,'Rand Aim','2021-06-12','Ingles','castellano');
INSERT INTO `` (`idContenido`,`Nombre`,`Fecha`,`Audio`,`Seleccionado`) VALUES (1422,'Micheil Stiddard','2018-09-17','Ingles','castellano');
INSERT INTO `` (`idContenido`,`Nombre`,`Fecha`,`Audio`,`Seleccionado`) VALUES (1707,'Doug Yeabsley','2022-04-12','Ingles','castellano');
INSERT INTO `` (`idContenido`,`Nombre`,`Fecha`,`Audio`,`Seleccionado`) VALUES (1552,'Bernardina Carlyon','2019-05-28','Ingles','castellano');
INSERT INTO `` (`idContenido`,`Nombre`,`Fecha`,`Audio`,`Seleccionado`) VALUES (1745,'Kaia Dainton','2023-01-01','Ingles','castellano');
INSERT INTO `` (`idContenido`,`Nombre`,`Fecha`,`Audio`,`Seleccionado`) VALUES (1473,'Jo-anne Fetteplace','2020-10-12','Ingles','castellano');
INSERT INTO `` (`idContenido`,`Nombre`,`Fecha`,`Audio`,`Seleccionado`) VALUES (149,'Dari Glasheen','2021-02-26','Ingles','castellano');
INSERT INTO `` (`idContenido`,`Nombre`,`Fecha`,`Audio`,`Seleccionado`) VALUES (1041,'Granny Westrip','2018-07-30','Ingles','castellano');
INSERT INTO `` (`idContenido`,`Nombre`,`Fecha`,`Audio`,`Seleccionado`) VALUES (1404,'Torre Mortimer','2022-08-04','Ingles','frances');
INSERT INTO `` (`idContenido`,`Nombre`,`Fecha`,`Audio`,`Seleccionado`) VALUES (231,'Gardner Bramelt','2019-08-27','Ingles','frances');
INSERT INTO `` (`idContenido`,`Nombre`,`Fecha`,`Audio`,`Seleccionado`) VALUES (303,'Sophi Cody','2020-06-12','Ingles','frances');
INSERT INTO `` (`idContenido`,`Nombre`,`Fecha`,`Audio`,`Seleccionado`) VALUES (1662,'Estrella Zarfat','2023-04-02','Ingles','frances');
INSERT INTO `` (`idContenido`,`Nombre`,`Fecha`,`Audio`,`Seleccionado`) VALUES (1592,'Edouard Pearsey','2021-10-10','Ingles','frances');
INSERT INTO `` (`idContenido`,`Nombre`,`Fecha`,`Audio`,`Seleccionado`) VALUES (5829,'Ira Bellis','2018-05-23','Ingles','frances');
INSERT INTO `` (`idContenido`,`Nombre`,`Fecha`,`Audio`,`Seleccionado`) VALUES (1764,'Leland Conerding','2019-03-07','Ingles','frances');
INSERT INTO `` (`idContenido`,`Nombre`,`Fecha`,`Audio`,`Seleccionado`) VALUES (9437,'Zena Farlambe','2022-02-03','Ingles','frances');
INSERT INTO `` (`idContenido`,`Nombre`,`Fecha`,`Audio`,`Seleccionado`) VALUES (3098,'Alayne Gunbie','2020-01-20','Ingles','frances');
INSERT INTO `` (`idContenido`,`Nombre`,`Fecha`,`Audio`,`Seleccionado`) VALUES (26,'Sayre Lismore','2023-03-28','Castellano','frances');
INSERT INTO `` (`idContenido`,`Nombre`,`Fecha`,`Audio`,`Seleccionado`) VALUES (384,'Derward Langer','2021-09-13','Castellano','frances');
INSERT INTO `` (`idContenido`,`Nombre`,`Fecha`,`Audio`,`Seleccionado`) VALUES (158,'Rebeka Stenning','2018-07-03','Castellano','frances');
INSERT INTO `` (`idContenido`,`Nombre`,`Fecha`,`Audio`,`Seleccionado`) VALUES (615,'Bancroft Rayworth','2022-07-12','Castellano','frances');
INSERT INTO `` (`idContenido`,`Nombre`,`Fecha`,`Audio`,`Seleccionado`) VALUES (1276,'Smith Heinsen','2019-06-29','Castellano','frances');
INSERT INTO `` (`idContenido`,`Nombre`,`Fecha`,`Audio`,`Seleccionado`) VALUES (680,'Freida Carstairs','2021-04-23','Castellano','italianoÂ ');
INSERT INTO `` (`idContenido`,`Nombre`,`Fecha`,`Audio`,`Seleccionado`) VALUES (1051,'Sinclare Mechem','2020-01-01','Castellano','italianoÂ ');
INSERT INTO `` (`idContenido`,`Nombre`,`Fecha`,`Audio`,`Seleccionado`) VALUES (1925,'Irena Lock','2018-11-29','Castellano','italianoÂ ');
INSERT INTO `` (`idContenido`,`Nombre`,`Fecha`,`Audio`,`Seleccionado`) VALUES (917,'Babbie Hudless','2023-03-22','Castellano','italianoÂ ');
INSERT INTO `` (`idContenido`,`Nombre`,`Fecha`,`Audio`,`Seleccionado`) VALUES (604,'Lezley Kearns','2020-12-07','Castellano','italianoÂ ');
INSERT INTO `` (`idContenido`,`Nombre`,`Fecha`,`Audio`,`Seleccionado`) VALUES (1143,'Huntington Allenby','2021-06-15','Castellano','italianoÂ ');
INSERT INTO `` (`idContenido`,`Nombre`,`Fecha`,`Audio`,`Seleccionado`) VALUES (1872,'Matthias Roddy','2018-09-07','Castellano','italianoÂ ');
INSERT INTO `` (`idContenido`,`Nombre`,`Fecha`,`Audio`,`Seleccionado`) VALUES (145,'Amble Clew','2022-04-03','Castellano','italianoÂ ');
INSERT INTO `` (`idContenido`,`Nombre`,`Fecha`,`Audio`,`Seleccionado`) VALUES (1462,'Angus Cazin','2019-05-17','Castellano','italianoÂ ');
INSERT INTO `` (`idContenido`,`Nombre`,`Fecha`,`Audio`,`Seleccionado`) VALUES (1862,'Quinn Gaffey','2023-01-06','Castellano','italianoÂ ');
INSERT INTO `` (`idContenido`,`Nombre`,`Fecha`,`Audio`,`Seleccionado`) VALUES (1598,'Edd Nafziger','2020-10-11','Castellano','ingles');
INSERT INTO `` (`idContenido`,`Nombre`,`Fecha`,`Audio`,`Seleccionado`) VALUES (178,'Clyve Champain','2021-03-06','Castellano','ingles');
INSERT INTO `` (`idContenido`,`Nombre`,`Fecha`,`Audio`,`Seleccionado`) VALUES (1487,'Nike Ties','2018-07-14','Castellano','ingles');
INSERT INTO `` (`idContenido`,`Nombre`,`Fecha`,`Audio`,`Seleccionado`) VALUES (1226,'Robby Kleinberer','2022-07-21','Castellano','ingles');
INSERT INTO `` (`idContenido`,`Nombre`,`Fecha`,`Audio`,`Seleccionado`) VALUES (1654,'Piper Dunbabin','2019-08-13','Castellano','ingles');
INSERT INTO `` (`idContenido`,`Nombre`,`Fecha`,`Audio`,`Seleccionado`) VALUES (867,'Otes Brideaux','2020-05-29','Castellano','ingles');
INSERT INTO `` (`idContenido`,`Nombre`,`Fecha`,`Audio`,`Seleccionado`) VALUES (1706,'Hunter Fife','2023-03-30','Original','ingles');
INSERT INTO `` (`idContenido`,`Nombre`,`Fecha`,`Audio`,`Seleccionado`) VALUES (1573,'Ronny Flahy','2021-11-07','Original','ingles');
INSERT INTO `` (`idContenido`,`Nombre`,`Fecha`,`Audio`,`Seleccionado`) VALUES (915,'Ketty Mewton','2018-04-16','Original','ingles');
INSERT INTO `` (`idContenido`,`Nombre`,`Fecha`,`Audio`,`Seleccionado`) VALUES (1048,'Becky Crome','2019-02-20','Original','ingles');
INSERT INTO `` (`idContenido`,`Nombre`,`Fecha`,`Audio`,`Seleccionado`) VALUES (252,'Tybalt Rummery','2022-01-16','Original','ingles');
INSERT INTO `` (`idContenido`,`Nombre`,`Fecha`,`Audio`,`Seleccionado`) VALUES (310,'Thalia Cusick','2020-10-27','Original','ingles');
INSERT INTO `` (`idContenido`,`Nombre`,`Fecha`,`Audio`,`Seleccionado`) VALUES (1466,'Berna Grocutt','2023-03-14','Original','ingles');
INSERT INTO `` (`idContenido`,`Nombre`,`Fecha`,`Audio`,`Seleccionado`) VALUES (789,'Sandor Zelley','2021-09-23','Original','ingles');
INSERT INTO `` (`idContenido`,`Nombre`,`Fecha`,`Audio`,`Seleccionado`) VALUES (1938,'Sebastiano Ottey','2018-08-06','Original','ingles');
INSERT INTO `` (`idContenido`,`Nombre`,`Fecha`,`Audio`,`Seleccionado`) VALUES (376,'Ellen Blasiak','2022-08-13','Original','ingles');
INSERT INTO `` (`idContenido`,`Nombre`,`Fecha`,`Audio`,`Seleccionado`) VALUES (707,'Arlyne Carme','2019-07-01','Original','ingles');
INSERT INTO `` (`idContenido`,`Nombre`,`Fecha`,`Audio`,`Seleccionado`) VALUES (1583,'Sigvard Ditchburn','2021-04-25','Original','portugues');
INSERT INTO `` (`idContenido`,`Nombre`,`Fecha`,`Audio`,`Seleccionado`) VALUES (24,'Warren Jaimez','2020-01-08','Original','portugues');
INSERT INTO `` (`idContenido`,`Nombre`,`Fecha`,`Audio`,`Seleccionado`) VALUES (1278,'Aubert Benaine','2018-12-03','Original','portugues');
INSERT INTO `` (`idContenido`,`Nombre`,`Fecha`,`Audio`,`Seleccionado`) VALUES (300,'Rhona Abbess','2023-02-27','Original','portugues');
INSERT INTO `` (`idContenido`,`Nombre`,`Fecha`,`Audio`,`Seleccionado`) VALUES (1119,'Marie Whorlton','2020-12-04','Original','portugues');
INSERT INTO `` (`idContenido`,`Nombre`,`Fecha`,`Audio`,`Seleccionado`) VALUES (1997,'Hedda Di Giacomettino','2021-06-14','Original','portugues');
INSERT INTO `` (`idContenido`,`Nombre`,`Fecha`,`Audio`,`Seleccionado`) VALUES (1992,'Bernarr Graybeal','2018-09-09','Original','portugues');
INSERT INTO `` (`idContenido`,`Nombre`,`Fecha`,`Audio`,`Seleccionado`) VALUES (335,'Orelia Lotze','2022-04-05','Ingles','portugues');
INSERT INTO `` (`idContenido`,`Nombre`,`Fecha`,`Audio`,`Seleccionado`) VALUES (905,'Lanie Abeau','2019-05-21','Ingles','portugues');
INSERT INTO `` (`idContenido`,`Nombre`,`Fecha`,`Audio`,`Seleccionado`) VALUES (767,'Beverlee Phelps','2023-01-04','Ingles','portugues');
INSERT INTO `` (`idContenido`,`Nombre`,`Fecha`,`Audio`,`Seleccionado`) VALUES (785,'Karoly Nanson','2020-10-16','Ingles','portugues');
INSERT INTO `` (`idContenido`,`Nombre`,`Fecha`,`Audio`,`Seleccionado`) VALUES (1510,'Rodie Spellward','2021-03-04','Ingles','castellano');
INSERT INTO `` (`idContenido`,`Nombre`,`Fecha`,`Audio`,`Seleccionado`) VALUES (1948,'Mohammed Haking','2018-07-20','Ingles','castellano');
INSERT INTO `` (`idContenido`,`Nombre`,`Fecha`,`Audio`,`Seleccionado`) VALUES (1590,'Edmund Von Helmholtz','2022-07-25','Ingles','castellano');
INSERT INTO `` (`idContenido`,`Nombre`,`Fecha`,`Audio`,`Seleccionado`) VALUES (383,'Brice Ord','2019-08-16','Ingles','castellano');
INSERT INTO `` (`idContenido`,`Nombre`,`Fecha`,`Audio`,`Seleccionado`) VALUES (304,'Shari Drewe','2020-06-01','Ingles','castellano');
INSERT INTO `` (`idContenido`,`Nombre`,`Fecha`,`Audio`,`Seleccionado`) VALUES (70,'Salomi Sampey','2023-04-11','Ingles','castellano');
INSERT INTO `` (`idContenido`,`Nombre`,`Fecha`,`Audio`,`Seleccionado`) VALUES (870,'Dolorita Scamp','2021-10-15','Ingles','castellano');
INSERT INTO `` (`idContenido`,`Nombre`,`Fecha`,`Audio`,`Seleccionado`) VALUES (226,'Joellyn Robottham','2018-04-24','Ingles','castellano');
INSERT INTO `` (`idContenido`,`Nombre`,`Fecha`,`Audio`,`Seleccionado`) VALUES (1147,'Wilma Robottham','2019-02-09','Ingles','castellano');
INSERT INTO `` (`idContenido`,`Nombre`,`Fecha`,`Audio`,`Seleccionado`) VALUES (1269,'Fran Danbi','2022-01-20','Original','castellano');
INSERT INTO `` (`idContenido`,`Nombre`,`Fecha`,`Audio`,`Seleccionado`) VALUES (567,'Marcie Masarrat','2020-10-24','Original','castellano');
INSERT INTO `` (`idContenido`,`Nombre`,`Fecha`,`Audio`,`Seleccionado`) VALUES (1512,'Darsey Mansfield','2023-03-15','Original','castellano');
INSERT INTO `` (`idContenido`,`Nombre`,`Fecha`,`Audio`,`Seleccionado`) VALUES (836,'Gigi Costello','2021-09-28','Original','ingles');
INSERT INTO `` (`idContenido`,`Nombre`,`Fecha`,`Audio`,`Seleccionado`) VALUES (1198,'Darleen Rickis','2018-08-08','Original','ingles');
INSERT INTO `` (`idContenido`,`Nombre`,`Fecha`,`Audio`,`Seleccionado`) VALUES (755,'Caryl Shipperbottom','2022-08-23','Original','ingles');
INSERT INTO `` (`idContenido`,`Nombre`,`Fecha`,`Audio`,`Seleccionado`) VALUES (1012,'Peadar Giddings','2019-07-04','Original','ingles');
INSERT INTO `` (`idContenido`,`Nombre`,`Fecha`,`Audio`,`Seleccionado`) VALUES (1422,'Rozalie Saltwell','2021-04-28','Original','ingles');
INSERT INTO `` (`idContenido`,`Nombre`,`Fecha`,`Audio`,`Seleccionado`) VALUES (1707,'Rand Aim','2020-01-11','Original','ingles');
INSERT INTO `` (`idContenido`,`Nombre`,`Fecha`,`Audio`,`Seleccionado`) VALUES (1552,'Micheil Stiddard','2018-12-10','Original','ingles');
INSERT INTO `` (`idContenido`,`Nombre`,`Fecha`,`Audio`,`Seleccionado`) VALUES (1745,'Doug Yeabsley','2023-03-01','Original','ingles');
INSERT INTO `` (`idContenido`,`Nombre`,`Fecha`,`Audio`,`Seleccionado`) VALUES (1473,'Bernardina Carlyon','2020-12-09','Original','ingles');
INSERT INTO `` (`idContenido`,`Nombre`,`Fecha`,`Audio`,`Seleccionado`) VALUES (149,'Kaia Dainton','2021-06-21','Original','ingles');
INSERT INTO `` (`idContenido`,`Nombre`,`Fecha`,`Audio`,`Seleccionado`) VALUES (1041,'Jo-anne Fetteplace','2018-09-16','Original','ingles');
INSERT INTO `` (`idContenido`,`Nombre`,`Fecha`,`Audio`,`Seleccionado`) VALUES (1404,'Dari Glasheen','2022-04-18','Original','ingles');
INSERT INTO `` (`idContenido`,`Nombre`,`Fecha`,`Audio`,`Seleccionado`) VALUES (231,'Granny Westrip','2019-05-25','Original','ingles');
INSERT INTO `` (`idContenido`,`Nombre`,`Fecha`,`Audio`,`Seleccionado`) VALUES (303,'Torre Mortimer','2023-01-03','Original','ninguno');
INSERT INTO `` (`idContenido`,`Nombre`,`Fecha`,`Audio`,`Seleccionado`) VALUES (1662,'Gardner Bramelt','2020-10-21','Original','ninguno');
INSERT INTO `` (`idContenido`,`Nombre`,`Fecha`,`Audio`,`Seleccionado`) VALUES (1592,'Sophi Cody','2021-03-07','Castellano','ninguno');
INSERT INTO `` (`idContenido`,`Nombre`,`Fecha`,`Audio`,`Seleccionado`) VALUES (5829,'Estrella Zarfat','2018-07-26','Castellano','ninguno');
INSERT INTO `` (`idContenido`,`Nombre`,`Fecha`,`Audio`,`Seleccionado`) VALUES (1764,'Edouard Pearsey','2022-07-29','Castellano','ninguno');
INSERT INTO `` (`idContenido`,`Nombre`,`Fecha`,`Audio`,`Seleccionado`) VALUES (9437,'Ira Bellis','2019-08-21','Castellano','portugues');
INSERT INTO `` (`idContenido`,`Nombre`,`Fecha`,`Audio`,`Seleccionado`) VALUES (3098,'Kain Downes','2020-06-08','Castellano','portugues');
INSERT INTO `` (`idContenido`,`Nombre`,`Fecha`,`Audio`,`Seleccionado`) VALUES (1291,'Petronilla Coronado','2023-04-05','Castellano','portugues');
INSERT INTO `` (`idContenido`,`Nombre`,`Fecha`,`Audio`,`Seleccionado`) VALUES (1037,'Bentlee Hek','2021-10-16','Castellano','portugues');
INSERT INTO `` (`idContenido`,`Nombre`,`Fecha`,`Audio`,`Seleccionado`) VALUES (875,'Dela Halward','2018-05-28','Castellano','portugues');
INSERT INTO `` (`idContenido`,`Nombre`,`Fecha`,`Audio`,`Seleccionado`) VALUES (1574,'Becca Turpey','2019-03-12','Castellano','portugues');
INSERT INTO `` (`idContenido`,`Nombre`,`Fecha`,`Audio`,`Seleccionado`) VALUES (684,'Constance Slayton','2022-02-10','Castellano','frances');
INSERT INTO `` (`idContenido`,`Nombre`,`Fecha`,`Audio`,`Seleccionado`) VALUES (152,'Dorena Klaesson','2020-01-22','Castellano','frances');
INSERT INTO `` (`idContenido`,`Nombre`,`Fecha`,`Audio`,`Seleccionado`) VALUES (422,'Ethe Chitson','2023-03-27','Castellano','frances');
INSERT INTO `` (`idContenido`,`Nombre`,`Fecha`,`Audio`,`Seleccionado`) VALUES (764,'Kinnie Benting','2021-09-16','Castellano','frances');
INSERT INTO `` (`idContenido`,`Nombre`,`Fecha`,`Audio`,`Seleccionado`) VALUES (759,'Harwell McGilvra','2018-08-12','Castellano','frances');
INSERT INTO `` (`idContenido`,`Nombre`,`Fecha`,`Audio`,`Seleccionado`) VALUES (1801,'Alison Getch','2022-08-27','Castellano','frances');
INSERT INTO `` (`idContenido`,`Nombre`,`Fecha`,`Audio`,`Seleccionado`) VALUES (742,'Emylee Spaldin','2019-07-09','Castellano','frances');
INSERT INTO `` (`idContenido`,`Nombre`,`Fecha`,`Audio`,`Seleccionado`) VALUES (1987,'Edan Nornasell','2021-04-19','Castellano','frances');
INSERT INTO `` (`idContenido`,`Nombre`,`Fecha`,`Audio`,`Seleccionado`) VALUES (1330,'Rori Grafton-Herbert','2020-01-03','Castellano','frances');
INSERT INTO `` (`idContenido`,`Nombre`,`Fecha`,`Audio`,`Seleccionado`) VALUES (1082,'Hertha Clac','2018-12-07','Castellano','frances');
INSERT INTO `` (`idContenido`,`Nombre`,`Fecha`,`Audio`,`Seleccionado`) VALUES (1692,'Lorne Kinnane','2023-02-28','Castellano','italianoÂ ');
INSERT INTO `` (`idContenido`,`Nombre`,`Fecha`,`Audio`,`Seleccionado`) VALUES (1092,'Phyllis Aughtie','2020-12-05','Castellano','italianoÂ ');
INSERT INTO `` (`idContenido`,`Nombre`,`Fecha`,`Audio`,`Seleccionado`) VALUES (1104,'Lock McIlwraith','2021-06-24','Castellano','italianoÂ ');
INSERT INTO `` (`idContenido`,`Nombre`,`Fecha`,`Audio`,`Seleccionado`) VALUES (1321,'Kassie Skittrell','2018-09-14','Castellano','italianoÂ ');
INSERT INTO `` (`idContenido`,`Nombre`,`Fecha`,`Audio`,`Seleccionado`) VALUES (1815,'Diana Rubinshtein','2022-04-16','Castellano','italianoÂ ');
INSERT INTO `` (`idContenido`,`Nombre`,`Fecha`,`Audio`,`Seleccionado`) VALUES (140,'Finn MacCartair','2019-05-24','Castellano','italianoÂ ');
INSERT INTO `` (`idContenido`,`Nombre`,`Fecha`,`Audio`,`Seleccionado`) VALUES (1093,'Arley McGahern','2023-01-07','Castellano','italianoÂ ');
INSERT INTO `` (`idContenido`,`Nombre`,`Fecha`,`Audio`,`Seleccionado`) VALUES (572,'Zabrina Cundey','2020-10-18','Castellano','italianoÂ ');
INSERT INTO `` (`idContenido`,`Nombre`,`Fecha`,`Audio`,`Seleccionado`) VALUES (568,'Consalve Mancer','2021-03-08','Castellano','italianoÂ ');
INSERT INTO `` (`idContenido`,`Nombre`,`Fecha`,`Audio`,`Seleccionado`) VALUES (1545,'Ashil McFadzean','2018-07-27','Castellano','italianoÂ ');
INSERT INTO `` (`idContenido`,`Nombre`,`Fecha`,`Audio`,`Seleccionado`) VALUES (1005,'Annabela Aiston','2022-07-30','Castellano','italianoÂ ');
INSERT INTO `` (`idContenido`,`Nombre`,`Fecha`,`Audio`,`Seleccionado`) VALUES (1818,'Georgiana Blackler','2019-08-24','Castellano','italianoÂ ');
INSERT INTO `` (`idContenido`,`Nombre`,`Fecha`,`Audio`,`Seleccionado`) VALUES (301,'Wallie Wretham','2020-06-10','Castellano','italianoÂ ');
INSERT INTO `` (`idContenido`,`Nombre`,`Fecha`,`Audio`,`Seleccionado`) VALUES (802,'Arley McGahern','2023-04-08','Castellano','');
