/*
-- Query: SELECT * FROM tp_bd_2023.cuenta
LIMIT 0, 1000

-- Date: 2023-06-01 21:01
*/
INSERT INTO `` (`mail`,`estado`,`contrasena`,`nombre`,`apellido`,`domicilio`,`cant_usuarios`,`idioma`) VALUES ('ahintzeh@so-net.ne.jp','Activo','asZu48jQ2bC','Thomasine','Guerin','682 Brown Point',3,'castellano');
INSERT INTO `` (`mail`,`estado`,`contrasena`,`nombre`,`apellido`,`domicilio`,`cant_usuarios`,`idioma`) VALUES ('ajohananoffc@ehow.com','Activo','6t4O64rx2Er','Reg','Caldaro','9 Lakewood Lane',3,'castellano');
INSERT INTO `` (`mail`,`estado`,`contrasena`,`nombre`,`apellido`,`domicilio`,`cant_usuarios`,`idioma`) VALUES ('amargarson15@opera.com','Activo','znFlTXZ','Bartholomeus','Pullan','7117 Brown Alley',3,'ingles');
INSERT INTO `` (`mail`,`estado`,`contrasena`,`nombre`,`apellido`,`domicilio`,`cant_usuarios`,`idioma`) VALUES ('aratlee2m@simplemachines.org','Inactivo','tAYdRX1X','Saunderson','Ingold','43594 Memorial Avenue',2,'ingles');
INSERT INTO `` (`mail`,`estado`,`contrasena`,`nombre`,`apellido`,`domicilio`,`cant_usuarios`,`idioma`) VALUES ('asadry19@wikia.com','Activo','xLEgJqpwLp','Paige','Casterot','1121 Armistice Drive',3,'ingles');
INSERT INTO `` (`mail`,`estado`,`contrasena`,`nombre`,`apellido`,`domicilio`,`cant_usuarios`,`idioma`) VALUES ('astanton3@xinhuanet.com','Inactivo','TSrpWAT','Olwen','Fearnill','2 Corben Street',3,'ingles');
INSERT INTO `` (`mail`,`estado`,`contrasena`,`nombre`,`apellido`,`domicilio`,`cant_usuarios`,`idioma`) VALUES ('bbradden1o@umich.edu','Activo','rF3fxMGgy','Sianna','Sidebotham','07 Starling Way',2,'castellano');
INSERT INTO `` (`mail`,`estado`,`contrasena`,`nombre`,`apellido`,`domicilio`,`cant_usuarios`,`idioma`) VALUES ('blagesg@oaic.gov.au','Inactivo','WQI7X2Jt1k','Ana','Hintze','29 Mayer Alley',3,'ingles');
INSERT INTO `` (`mail`,`estado`,`contrasena`,`nombre`,`apellido`,`domicilio`,`cant_usuarios`,`idioma`) VALUES ('blamplough1b@nifty.com','Activo','sJhKfik','Hagen','Klimushev','408 Maple Wood Place',3,'ingles');
INSERT INTO `` (`mail`,`estado`,`contrasena`,`nombre`,`apellido`,`domicilio`,`cant_usuarios`,`idioma`) VALUES ('bpullan16@cisco.com','Activo','DJNiwp','Friedrick','Gheorghie','7657 Dwight Center',3,'ingles');
INSERT INTO `` (`mail`,`estado`,`contrasena`,`nombre`,`apellido`,`domicilio`,`cant_usuarios`,`idioma`) VALUES ('bramsbothamy@elpais.com','Activo','VXogmlmf','Nestor','Maryet','334 Welch Plaza',3,'ingles');
INSERT INTO `` (`mail`,`estado`,`contrasena`,`nombre`,`apellido`,`domicilio`,`cant_usuarios`,`idioma`) VALUES ('cbows2o@homestead.com','Activo','pAE9o8AYuftn','Ynez','Getty','6182 Farragut Street',2,'ingles');
INSERT INTO `` (`mail`,`estado`,`contrasena`,`nombre`,`apellido`,`domicilio`,`cant_usuarios`,`idioma`) VALUES ('cbrennans18@baidu.com','Activo','2shaHV','Allan','Sadry','4282 Southridge Center',3,'ingles');
INSERT INTO `` (`mail`,`estado`,`contrasena`,`nombre`,`apellido`,`domicilio`,`cant_usuarios`,`idioma`) VALUES ('crammell12@who.int','Activo','CbE5ZY','Wayne','Tanby','4410 Northwestern Crossing',3,'ingles');
INSERT INTO `` (`mail`,`estado`,`contrasena`,`nombre`,`apellido`,`domicilio`,`cant_usuarios`,`idioma`) VALUES ('crosenstengelt@reference.com','Activo','1A8xRA85A','Jessee','Lysons','8959 Maple Circle',3,'ingles');
INSERT INTO `` (`mail`,`estado`,`contrasena`,`nombre`,`apellido`,`domicilio`,`cant_usuarios`,`idioma`) VALUES ('cskidmore2b@youku.com','Inactivo','8WpGy6adHFO','Judas','Lead','8 Gerald Crossing',2,'ingles');
INSERT INTO `` (`mail`,`estado`,`contrasena`,`nombre`,`apellido`,`domicilio`,`cant_usuarios`,`idioma`) VALUES ('cwoollacott22@amazon.de','Activo','WeRno1x','Stillmann','Bligh','4855 Main Court',2,'ingles');
INSERT INTO `` (`mail`,`estado`,`contrasena`,`nombre`,`apellido`,`domicilio`,`cant_usuarios`,`idioma`) VALUES ('dpietzke7@de.vu','Inactivo','7GYoa5h','Jess','Levitt','22 Buell Way',3,'ingles');
INSERT INTO `` (`mail`,`estado`,`contrasena`,`nombre`,`apellido`,`domicilio`,`cant_usuarios`,`idioma`) VALUES ('dsheaf1l@mashable.com','Activo','jhUS2WKHQc','Ferd','Bewicke','3849 Carioca Hill',2,'castellano');
INSERT INTO `` (`mail`,`estado`,`contrasena`,`nombre`,`apellido`,`domicilio`,`cant_usuarios`,`idioma`) VALUES ('falpe1x@cargocollective.com','Activo','ZrC4ka2zu','Julio','Chaston','17577 Bultman Trail',2,'ingles');
INSERT INTO `` (`mail`,`estado`,`contrasena`,`nombre`,`apellido`,`domicilio`,`cant_usuarios`,`idioma`) VALUES ('fbewicke1m@godaddy.com','Activo','e6s6C0wxTNU','Rabi','Stranks','76 Melrose Place',2,'ingles');
INSERT INTO `` (`mail`,`estado`,`contrasena`,`nombre`,`apellido`,`domicilio`,`cant_usuarios`,`idioma`) VALUES ('fgheorghie17@topsy.com','Activo','RqlIhpjI','Consalve','Brennans','08 Pine View Center',3,'castellano');
INSERT INTO `` (`mail`,`estado`,`contrasena`,`nombre`,`apellido`,`domicilio`,`cant_usuarios`,`idioma`) VALUES ('gchriston1@geocities.jp','Activo','2jhUMnlUqvVo','Jeramey','Hurleston','869 Corben Trail',3,'ingles');
INSERT INTO `` (`mail`,`estado`,`contrasena`,`nombre`,`apellido`,`domicilio`,`cant_usuarios`,`idioma`) VALUES ('gdemageard1v@last.fm','Activo','aOXdWNt00','Malory','Allix','3356 Gina Parkway',2,'castellano');
INSERT INTO `` (`mail`,`estado`,`contrasena`,`nombre`,`apellido`,`domicilio`,`cant_usuarios`,`idioma`) VALUES ('gdrewett2d@facebook.com','Activo','SnkmgaOEgZ4n','Octavia','Goggey','5850 Burning Wood Center',2,'ingles');
INSERT INTO `` (`mail`,`estado`,`contrasena`,`nombre`,`apellido`,`domicilio`,`cant_usuarios`,`idioma`) VALUES ('geaklek@skyrock.com','Inactivo','LMlLqQX','Vance','Boydle','0595 Hagan Road',3,'castellano');
INSERT INTO `` (`mail`,`estado`,`contrasena`,`nombre`,`apellido`,`domicilio`,`cant_usuarios`,`idioma`) VALUES ('gsuller1h@elpais.com','Activo','71IRnFcE3','Jocelyne','Driscoll','711 Morningstar Street',2,'ingles');
INSERT INTO `` (`mail`,`estado`,`contrasena`,`nombre`,`apellido`,`domicilio`,`cant_usuarios`,`idioma`) VALUES ('hbessells@dyndns.org','Activo','hiGJQP','Cher','Rosenstengel','48230 Gale Circle',3,'castellano');
INSERT INTO `` (`mail`,`estado`,`contrasena`,`nombre`,`apellido`,`domicilio`,`cant_usuarios`,`idioma`) VALUES ('hblancowe9@prlog.org','Activo','ecaegDlbZ','Noel','McCotter','2442 Esch Street',3,'castellano');
INSERT INTO `` (`mail`,`estado`,`contrasena`,`nombre`,`apellido`,`domicilio`,`cant_usuarios`,`idioma`) VALUES ('hbondar13@wikipedia.org','Activo','kDXV09dC','Reginald','Wynett','0 Paget Parkway',3,'castellano');
INSERT INTO `` (`mail`,`estado`,`contrasena`,`nombre`,`apellido`,`domicilio`,`cant_usuarios`,`idioma`) VALUES ('hgareisr2g@cbc.ca','Activo','vTIX8L','Marj','Dohmann','082 Annamark Avenue',2,'castellano');
INSERT INTO `` (`mail`,`estado`,`contrasena`,`nombre`,`apellido`,`domicilio`,`cant_usuarios`,`idioma`) VALUES ('hklimushev1c@opera.com','Activo','33qHyqKDIb','Ruperta','Noah','46 Atwood Place',3,'ingles');
INSERT INTO `` (`mail`,`estado`,`contrasena`,`nombre`,`apellido`,`domicilio`,`cant_usuarios`,`idioma`) VALUES ('ihulkw@smh.com.au','Activo','t8WbB8','Kennett','Putt','86201 Anzinger Parkway',3,'ingles');
INSERT INTO `` (`mail`,`estado`,`contrasena`,`nombre`,`apellido`,`domicilio`,`cant_usuarios`,`idioma`) VALUES ('jbenoix1j@utexas.edu','Inactivo','3aVVuTTnyfrs','Lona','Ferreira','5 Bultman Center',2,'ingles');
INSERT INTO `` (`mail`,`estado`,`contrasena`,`nombre`,`apellido`,`domicilio`,`cant_usuarios`,`idioma`) VALUES ('jchaston1y@creativecommons.org','Activo','EOmUVtUZM','Phil','Fatkin','7 Elmside Terrace',2,'castellano');
INSERT INTO `` (`mail`,`estado`,`contrasena`,`nombre`,`apellido`,`domicilio`,`cant_usuarios`,`idioma`) VALUES ('jdriscoll1i@japanpost.jp','Activo','PFsYw52o','Judye','Benoix','469 Acker Junction',2,'ingles');
INSERT INTO `` (`mail`,`estado`,`contrasena`,`nombre`,`apellido`,`domicilio`,`cant_usuarios`,`idioma`) VALUES ('jhurleston2@marketwatch.com','Activo','fLL5KFz5bJ','Aggi','Stanton','2 Roth Parkway',3,'ingles');
INSERT INTO `` (`mail`,`estado`,`contrasena`,`nombre`,`apellido`,`domicilio`,`cant_usuarios`,`idioma`) VALUES ('jkornes1e@skype.com','Inactivo','frUjUG','Lexy','Quick','43320 Bellgrove Drive',2,'castellano');
INSERT INTO `` (`mail`,`estado`,`contrasena`,`nombre`,`apellido`,`domicilio`,`cant_usuarios`,`idioma`) VALUES ('jlead2c@goo.gl','Activo','bGFh61','Gideon','Drewett','7 Ruskin Plaza',2,'castellano');
INSERT INTO `` (`mail`,`estado`,`contrasena`,`nombre`,`apellido`,`domicilio`,`cant_usuarios`,`idioma`) VALUES ('jlevitt8@privacy.gov.au','Activo','Xv5vfS','Henderson','Blancowe','33463 Toban Center',3,'ingles');
INSERT INTO `` (`mail`,`estado`,`contrasena`,`nombre`,`apellido`,`domicilio`,`cant_usuarios`,`idioma`) VALUES ('jlysonsu@4shared.com','Inactivo','QzGCw3v1','Oran','Wylam','388 Waxwing Road',3,'castellano');
INSERT INTO `` (`mail`,`estado`,`contrasena`,`nombre`,`apellido`,`domicilio`,`cant_usuarios`,`idioma`) VALUES ('jmaypes10@amazon.co.uk','Inactivo','1yuP2NggDE','Liana','Tamblingson','66484 Express Center',3,'ingles');
INSERT INTO `` (`mail`,`estado`,`contrasena`,`nombre`,`apellido`,`domicilio`,`cant_usuarios`,`idioma`) VALUES ('jtomes26@csmonitor.com','Inactivo','lzvv8gt3JK0','Robinetta','Stacey','1 Caliangt Hill',2,'ingles');
INSERT INTO `` (`mail`,`estado`,`contrasena`,`nombre`,`apellido`,`domicilio`,`cant_usuarios`,`idioma`) VALUES ('kelden2i@thetimes.co.uk','Inactivo','BVomM7vdMNH','Leigh','Blakemore','545 Granby Hill',2,'ingles');
INSERT INTO `` (`mail`,`estado`,`contrasena`,`nombre`,`apellido`,`domicilio`,`cant_usuarios`,`idioma`) VALUES ('kputtx@howstuffworks.com','Activo','22e16e','Berthe','Ramsbotham','1654 Holmberg Center',3,'ingles');
INSERT INTO `` (`mail`,`estado`,`contrasena`,`nombre`,`apellido`,`domicilio`,`cant_usuarios`,`idioma`) VALUES ('kyakov1s@constantcontact.com','Activo','GWyvQntfha','Marcia','Iowarch','21 Sullivan Way',2,'ingles');
INSERT INTO `` (`mail`,`estado`,`contrasena`,`nombre`,`apellido`,`domicilio`,`cant_usuarios`,`idioma`) VALUES ('lblakemore2j@php.net','Activo','nprgpbOo','Vally','Hedling','67 Mosinee Pass',2,'ingles');
INSERT INTO `` (`mail`,`estado`,`contrasena`,`nombre`,`apellido`,`domicilio`,`cant_usuarios`,`idioma`) VALUES ('lcanwell2l@newsvine.com','Inactivo','ub14bpzH','Ariel','Ratlee','41532 Rigney Trail',2,'ingles');
INSERT INTO `` (`mail`,`estado`,`contrasena`,`nombre`,`apellido`,`domicilio`,`cant_usuarios`,`idioma`) VALUES ('lferreira1k@w3.org','Activo','XH9fKHmH','Daron','Sheaf','73 Derek Hill',2,'castellano');
INSERT INTO `` (`mail`,`estado`,`contrasena`,`nombre`,`apellido`,`domicilio`,`cant_usuarios`,`idioma`) VALUES ('llawrance1u@biblegateway.com','Activo','E77ojSX1l','Gery','Demageard','256 Thierer Circle',2,'ingles');
INSERT INTO `` (`mail`,`estado`,`contrasena`,`nombre`,`apellido`,`domicilio`,`cant_usuarios`,`idioma`) VALUES ('lmurdyo@boston.com','Activo','wyeQZ6gGL','Niels','Rizziello','5455 Scoville Road',3,'castellano');
INSERT INTO `` (`mail`,`estado`,`contrasena`,`nombre`,`apellido`,`domicilio`,`cant_usuarios`,`idioma`) VALUES ('lquick1f@blogger.com','Inactivo','Ruh4Ct','Ruy','Huskisson','2313 La Follette Road',2,'castellano');
INSERT INTO `` (`mail`,`estado`,`contrasena`,`nombre`,`apellido`,`domicilio`,`cant_usuarios`,`idioma`) VALUES ('ltamblingson11@theguardian.com','Activo','QDiPHuiQP','Cilka','Rammell','5722 Havey Pass',3,'ingles');
INSERT INTO `` (`mail`,`estado`,`contrasena`,`nombre`,`apellido`,`domicilio`,`cant_usuarios`,`idioma`) VALUES ('mallix1w@comcast.net','Activo','DTjNF8zueg','Franny','Alpe','0928 Manufacturers Hill',2,'ingles');
INSERT INTO `` (`mail`,`estado`,`contrasena`,`nombre`,`apellido`,`domicilio`,`cant_usuarios`,`idioma`) VALUES ('mdohmann2h@1und1.de','Activo','H1PiRb6','Kali','Elden','6165 Maple Place',2,'castellano');
INSERT INTO `` (`mail`,`estado`,`contrasena`,`nombre`,`apellido`,`domicilio`,`cant_usuarios`,`idioma`) VALUES ('mduthy5@cbc.ca','Activo','lB0vwksHeF','Roderick','Crackett','07 Grasskamp Center',3,'castellano');
INSERT INTO `` (`mail`,`estado`,`contrasena`,`nombre`,`apellido`,`domicilio`,`cant_usuarios`,`idioma`) VALUES ('mgeorgeouj@paginegialle.it','Activo','woHyCp','Gerik','Eakle','90401 Garrison Drive',3,'castellano');
INSERT INTO `` (`mail`,`estado`,`contrasena`,`nombre`,`apellido`,`domicilio`,`cant_usuarios`,`idioma`) VALUES ('miowarch1t@stanford.edu','Activo','3iyzOUU','Lilian','Lawrance','1031 Arrowood Point',2,'castellano');
INSERT INTO `` (`mail`,`estado`,`contrasena`,`nombre`,`apellido`,`domicilio`,`cant_usuarios`,`idioma`) VALUES ('mridges24@instagram.com','Activo','u8yyVTJA','Silas','Harlin','69 Coolidge Place',2,'castellano');
INSERT INTO `` (`mail`,`estado`,`contrasena`,`nombre`,`apellido`,`domicilio`,`cant_usuarios`,`idioma`) VALUES ('mscotsbrookn@noaa.gov','Activo','ffyiUCSIy2K','Lion','Murdy','499 Upham Avenue',3,'ingles');
INSERT INTO `` (`mail`,`estado`,`contrasena`,`nombre`,`apellido`,`domicilio`,`cant_usuarios`,`idioma`) VALUES ('mwackley1q@mysql.com','Activo','LwA7Lzr','Toddy','Buckel','98340 Susan Circle',2,'ingles');
INSERT INTO `` (`mail`,`estado`,`contrasena`,`nombre`,`apellido`,`domicilio`,`cant_usuarios`,`idioma`) VALUES ('nlambersenq@nba.com','Activo','h4TnOjZG5oK','Randi','Barnwill','2 Steensland Hill',3,'castellano');
INSERT INTO `` (`mail`,`estado`,`contrasena`,`nombre`,`apellido`,`domicilio`,`cant_usuarios`,`idioma`) VALUES ('nmaryetz@dropbox.com','Inactivo','erlVqWAnVzG','Jerrine','Maypes','43 Truax Circle',3,'ingles');
INSERT INTO `` (`mail`,`estado`,`contrasena`,`nombre`,`apellido`,`domicilio`,`cant_usuarios`,`idioma`) VALUES ('nmccottera@nationalgeographic.com','Inactivo','HtLw0vTB','Taddeo','Ruhben','0276 Haas Trail',3,'castellano');
INSERT INTO `` (`mail`,`estado`,`contrasena`,`nombre`,`apellido`,`domicilio`,`cant_usuarios`,`idioma`) VALUES ('nmorettof@weibo.com','Activo','p7MiqZRv','Buck','Lages','209 Sunfield Crossing',3,'ingles');
INSERT INTO `` (`mail`,`estado`,`contrasena`,`nombre`,`apellido`,`domicilio`,`cant_usuarios`,`idioma`) VALUES ('nrizziellop@msu.edu','Activo','gFffmaW','Noam','Lambersen','368 Chinook Court',3,'ingles');
INSERT INTO `` (`mail`,`estado`,`contrasena`,`nombre`,`apellido`,`domicilio`,`cant_usuarios`,`idioma`) VALUES ('ofearnill4@opensource.org','Inactivo','F8VvbACR80oA','Mariana','Duthy','43 Merrick Point',3,'ingles');
INSERT INTO `` (`mail`,`estado`,`contrasena`,`nombre`,`apellido`,`domicilio`,`cant_usuarios`,`idioma`) VALUES ('ogoggey2e@ca.gov','Activo','MUL4u0bfT4','Verene','Durrad','1553 Clyde Gallagher Hill',2,'castellano');
INSERT INTO `` (`mail`,`estado`,`contrasena`,`nombre`,`apellido`,`domicilio`,`cant_usuarios`,`idioma`) VALUES ('owylamv@ovh.net','Activo','AGdJxvX','Ileana','Hulk','9056 Vermont Plaza',3,'castellano');
INSERT INTO `` (`mail`,`estado`,`contrasena`,`nombre`,`apellido`,`domicilio`,`cant_usuarios`,`idioma`) VALUES ('pcasterot1a@booking.com','Activo','BxkwzZu7','Brittany','Lamplough','3429 Arkansas Plaza',3,'castellano');
INSERT INTO `` (`mail`,`estado`,`contrasena`,`nombre`,`apellido`,`domicilio`,`cant_usuarios`,`idioma`) VALUES ('pfatkin1z@twitpic.com','Activo','XgK53W','Rochella','Muscott','55 Prairieview Avenue',2,'castellano');
INSERT INTO `` (`mail`,`estado`,`contrasena`,`nombre`,`apellido`,`domicilio`,`cant_usuarios`,`idioma`) VALUES ('pmcvee2a@bluehost.com','Activo','YYTDCUnX','Cammi','Skidmore','3 Northland Park',2,'castellano');
INSERT INTO `` (`mail`,`estado`,`contrasena`,`nombre`,`apellido`,`domicilio`,`cant_usuarios`,`idioma`) VALUES ('rbarnwillr@unesco.org','Activo','jyiy5d8qb','Heidi','Bessell','84 Sunnyside Crossing',3,'ingles');
INSERT INTO `` (`mail`,`estado`,`contrasena`,`nombre`,`apellido`,`domicilio`,`cant_usuarios`,`idioma`) VALUES ('rcaldarod@over-blog.com','Activo','ziMTQbORegwJ','Steffie','Coltart','6237 Buell Hill',3,'castellano');
INSERT INTO `` (`mail`,`estado`,`contrasena`,`nombre`,`apellido`,`domicilio`,`cant_usuarios`,`idioma`) VALUES ('rcrackett6@paypal.com','Activo','otLzt6t','Dora','Pietzke','15 Redwing Avenue',3,'ingles');
INSERT INTO `` (`mail`,`estado`,`contrasena`,`nombre`,`apellido`,`domicilio`,`cant_usuarios`,`idioma`) VALUES ('rhuskisson1g@china.com.cn','Activo','ZRk23Xf','Gilbertina','Suller','6115 Grim Point',2,'castellano');
INSERT INTO `` (`mail`,`estado`,`contrasena`,`nombre`,`apellido`,`domicilio`,`cant_usuarios`,`idioma`) VALUES ('rmuscott20@symantec.com','Activo','IBiQkbbP','Selene','Geockle','0166 David Crossing',2,'ingles');
INSERT INTO `` (`mail`,`estado`,`contrasena`,`nombre`,`apellido`,`domicilio`,`cant_usuarios`,`idioma`) VALUES ('rnoah1d@techcrunch.com','Activo','z8JkIO6hDKD','Janeva','Kornes','67632 Homewood Hill',2,'castellano');
INSERT INTO `` (`mail`,`estado`,`contrasena`,`nombre`,`apellido`,`domicilio`,`cant_usuarios`,`idioma`) VALUES ('rstacey27@desdev.cn','Inactivo','64kA2N','Tabby','Band','56943 Kingsford Alley',2,'ingles');
INSERT INTO `` (`mail`,`estado`,`contrasena`,`nombre`,`apellido`,`domicilio`,`cant_usuarios`,`idioma`) VALUES ('rstranks1n@shutterfly.com','Activo','EG0Y7jHRaxA','Brigitta','Bradden','34 Hauk Lane',2,'ingles');
INSERT INTO `` (`mail`,`estado`,`contrasena`,`nombre`,`apellido`,`domicilio`,`cant_usuarios`,`idioma`) VALUES ('rwynett14@cornell.edu','Inactivo','mJvd5rGM0','Angela','Margarson','1 Homewood Junction',3,'ingles');
INSERT INTO `` (`mail`,`estado`,`contrasena`,`nombre`,`apellido`,`domicilio`,`cant_usuarios`,`idioma`) VALUES ('sbligh23@qq.com','Inactivo','N64nGd','Micaela','Ridges','650 Caliangt Terrace',2,'castellano');
INSERT INTO `` (`mail`,`estado`,`contrasena`,`nombre`,`apellido`,`domicilio`,`cant_usuarios`,`idioma`) VALUES ('scoltarte@cdc.gov','Inactivo','bURyvwRNSkXp','Noah','Moretto','1 Stang Alley',3,'ingles');
INSERT INTO `` (`mail`,`estado`,`contrasena`,`nombre`,`apellido`,`domicilio`,`cant_usuarios`,`idioma`) VALUES ('sgeockle21@guardian.co.uk','Activo','SsnkbL','Carmencita','Woollacott','60426 Lindbergh Point',2,'ingles');
INSERT INTO `` (`mail`,`estado`,`contrasena`,`nombre`,`apellido`,`domicilio`,`cant_usuarios`,`idioma`) VALUES ('sharlin25@statcounter.com','Activo','fkeFfzTp','Jerrold','Tomes','6 Elgar Terrace',2,'castellano');
INSERT INTO `` (`mail`,`estado`,`contrasena`,`nombre`,`apellido`,`domicilio`,`cant_usuarios`,`idioma`) VALUES ('singold2n@newyorker.com','Inactivo','FARvmnX','Cyril','Bows','138 Sutherland Crossing',2,'ingles');
INSERT INTO `` (`mail`,`estado`,`contrasena`,`nombre`,`apellido`,`domicilio`,`cant_usuarios`,`idioma`) VALUES ('skirkup2q@earthlink.net','Activo','pJeVuc','Veronika','Keyworth','5494 Bobwhite Hill',2,'ingles');
INSERT INTO `` (`mail`,`estado`,`contrasena`,`nombre`,`apellido`,`domicilio`,`cant_usuarios`,`idioma`) VALUES ('ssidebotham1p@goodreads.com','Activo','B80r2DUQgAYE','Myrna','Wackley','6 Melody Court',2,'ingles');
INSERT INTO `` (`mail`,`estado`,`contrasena`,`nombre`,`apellido`,`domicilio`,`cant_usuarios`,`idioma`) VALUES ('stumayanm@europa.eu','Inactivo','iXUIcgf4xDC','Melly','Scotsbrook','05 Forster Pass',3,'castellano');
INSERT INTO `` (`mail`,`estado`,`contrasena`,`nombre`,`apellido`,`domicilio`,`cant_usuarios`,`idioma`) VALUES ('tband28@gravatar.com','Activo','ZvIWnxh','Thibaud','Bardey','79 Arrowood Street',2,'ingles');
INSERT INTO `` (`mail`,`estado`,`contrasena`,`nombre`,`apellido`,`domicilio`,`cant_usuarios`,`idioma`) VALUES ('tbardey29@example.com','Activo','JXR0IF8ghMn','Percival','McVee','76508 Hooker Street',2,'castellano');
INSERT INTO `` (`mail`,`estado`,`contrasena`,`nombre`,`apellido`,`domicilio`,`cant_usuarios`,`idioma`) VALUES ('tbuckel1r@slideshare.net','Activo','zQMqdlsK','Kendrick','Yakov','0 Grayhawk Lane',2,'ingles');
INSERT INTO `` (`mail`,`estado`,`contrasena`,`nombre`,`apellido`,`domicilio`,`cant_usuarios`,`idioma`) VALUES ('tguerini@walmart.com','Activo','E8zj3uFu','Maxie','Georgeou','74 Dwight Avenue',3,'castellano');
INSERT INTO `` (`mail`,`estado`,`contrasena`,`nombre`,`apellido`,`domicilio`,`cant_usuarios`,`idioma`) VALUES ('truhbenb@sciencedaily.com','Activo','0YlwNPWgcIP','Adore','Johananoff','0 Troy Way',3,'ingles');
INSERT INTO `` (`mail`,`estado`,`contrasena`,`nombre`,`apellido`,`domicilio`,`cant_usuarios`,`idioma`) VALUES ('vboydlel@kickstarter.com','Activo','kf3HT6jPJLgU','Sandy','Tumayan','7 Division Avenue',3,'ingles');
INSERT INTO `` (`mail`,`estado`,`contrasena`,`nombre`,`apellido`,`domicilio`,`cant_usuarios`,`idioma`) VALUES ('vdurrad2f@unc.edu','Activo','NYZRDxkI4Ser','Hurleigh','Gareisr','35 Gerald Circle',2,'castellano');
INSERT INTO `` (`mail`,`estado`,`contrasena`,`nombre`,`apellido`,`domicilio`,`cant_usuarios`,`idioma`) VALUES ('vhedling2k@google.com','Activo','pniNTXJam8l','Leyla','Canwell','289 Kipling Hill',2,'ingles');
INSERT INTO `` (`mail`,`estado`,`contrasena`,`nombre`,`apellido`,`domicilio`,`cant_usuarios`,`idioma`) VALUES ('wtanby0@hud.gov','Activo','PdMdedLE','Goldia','Christon','1 Golf Place',3,'ingles');
INSERT INTO `` (`mail`,`estado`,`contrasena`,`nombre`,`apellido`,`domicilio`,`cant_usuarios`,`idioma`) VALUES ('ygetty2p@si.edu','Activo','NjLpwCWNT','Stanly','Kirkup','04 Brentwood Way',2,'castellano');
