/*
-- Query: SELECT * FROM tp_bd_2023.realizar
LIMIT 0, 1000

-- Date: 2023-06-01 21:06
*/
INSERT INTO `` (`Nombre`,`idBusqueda`,`Tema`,`Descripcion`) VALUES ('Meaghan Pittel',5,'Actor','Emilio Estevez');
INSERT INTO `` (`Nombre`,`idBusqueda`,`Tema`,`Descripcion`) VALUES ('Iris Crumly',24,'Director','Quentin Tarantino');
INSERT INTO `` (`Nombre`,`idBusqueda`,`Tema`,`Descripcion`) VALUES ('Maggy Chartres',26,'Actor','Bruce Willis');
INSERT INTO `` (`Nombre`,`idBusqueda`,`Tema`,`Descripcion`) VALUES ('Brice Ord',70,'Director','Wes Anderson');
INSERT INTO `` (`Nombre`,`idBusqueda`,`Tema`,`Descripcion`) VALUES ('Bernarr Graybeal',140,'Genero','Musical');
INSERT INTO `` (`Nombre`,`idBusqueda`,`Tema`,`Descripcion`) VALUES ('Lanie Abeau',145,'Titulo','The Lion King II: Simba\'s Pride');
INSERT INTO `` (`Nombre`,`idBusqueda`,`Tema`,`Descripcion`) VALUES ('Casar Mion',149,'Calificacion','16');
INSERT INTO `` (`Nombre`,`idBusqueda`,`Tema`,`Descripcion`) VALUES ('Becky Crome',152,'Genero','Aventura');
INSERT INTO `` (`Nombre`,`idBusqueda`,`Tema`,`Descripcion`) VALUES ('Cassius Dorre',158,'Actor','Leonardo DiCaprio');
INSERT INTO `` (`Nombre`,`idBusqueda`,`Tema`,`Descripcion`) VALUES ('Madelon Kagan',178,'Titulo','The Lord of the Rings: The Fellowship of the Ring');
INSERT INTO `` (`Nombre`,`idBusqueda`,`Tema`,`Descripcion`) VALUES ('Salomi Sampey',226,'Director','David Fincher');
INSERT INTO `` (`Nombre`,`idBusqueda`,`Tema`,`Descripcion`) VALUES ('Marline Liccardi',231,'Calificacion','ATP');
INSERT INTO `` (`Nombre`,`idBusqueda`,`Tema`,`Descripcion`) VALUES ('Alexandros Presley',252,'Titulo','The Lord of the Rings: The Return of the King');
INSERT INTO `` (`Nombre`,`idBusqueda`,`Tema`,`Descripcion`) VALUES ('Margaretha Kloss',275,'Actor','Clark Gable');
INSERT INTO `` (`Nombre`,`idBusqueda`,`Tema`,`Descripcion`) VALUES ('Casar Mion',300,'Director','Christopher Nolan');
INSERT INTO `` (`Nombre`,`idBusqueda`,`Tema`,`Descripcion`) VALUES ('Kimmy Eaken',301,'Genero','Suspenso');
INSERT INTO `` (`Nombre`,`idBusqueda`,`Tema`,`Descripcion`) VALUES ('Velma Donisthorpe',303,'Calificacion','13');
INSERT INTO `` (`Nombre`,`idBusqueda`,`Tema`,`Descripcion`) VALUES ('Edmund Von Helmholtz',304,'Director','Martin Scorsese');
INSERT INTO `` (`Nombre`,`idBusqueda`,`Tema`,`Descripcion`) VALUES ('Estevan Addams',307,'Genero','Aventura');
INSERT INTO `` (`Nombre`,`idBusqueda`,`Tema`,`Descripcion`) VALUES ('Margaretha Kloss',310,'Titulo','Star Wars: Episode II - Attack of the Clones');
INSERT INTO `` (`Nombre`,`idBusqueda`,`Tema`,`Descripcion`) VALUES ('Velma Donisthorpe',335,'Director','David Fincher');
INSERT INTO `` (`Nombre`,`idBusqueda`,`Tema`,`Descripcion`) VALUES ('Maggy Chartres',376,'Titulo','Star Wars: Episode III - Revenge of the Sith');
INSERT INTO `` (`Nombre`,`idBusqueda`,`Tema`,`Descripcion`) VALUES ('Mohammed Haking',383,'Director','Quentin Tarantino');
INSERT INTO `` (`Nombre`,`idBusqueda`,`Tema`,`Descripcion`) VALUES ('Ilise Manoelli',384,'Actor','Keir Dullea');
INSERT INTO `` (`Nombre`,`idBusqueda`,`Tema`,`Descripcion`) VALUES ('Tybalt Rummery',422,'Genero','Accion');
INSERT INTO `` (`Nombre`,`idBusqueda`,`Tema`,`Descripcion`) VALUES ('Wilma Robottham',567,'Director','Christopher Nolan');
INSERT INTO `` (`Nombre`,`idBusqueda`,`Tema`,`Descripcion`) VALUES ('Cortney Giacomuzzi',568,'Genero','Aventura');
INSERT INTO `` (`Nombre`,`idBusqueda`,`Tema`,`Descripcion`) VALUES ('Janenna Rodgers',572,'Genero','Accion');
INSERT INTO `` (`Nombre`,`idBusqueda`,`Tema`,`Descripcion`) VALUES ('Velma Donisthorpe',604,'Actor','');
INSERT INTO `` (`Nombre`,`idBusqueda`,`Tema`,`Descripcion`) VALUES ('Iris Crumly',615,'Actor','Mark Hamill');
INSERT INTO `` (`Nombre`,`idBusqueda`,`Tema`,`Descripcion`) VALUES ('Casar Mion',680,'Actor','Liam Neeson');
INSERT INTO `` (`Nombre`,`idBusqueda`,`Tema`,`Descripcion`) VALUES ('Ketty Mewton',684,'Genero','Accion');
INSERT INTO `` (`Nombre`,`idBusqueda`,`Tema`,`Descripcion`) VALUES ('Ilise Manoelli',707,'Titulo','The Hateful Eight');
INSERT INTO `` (`Nombre`,`idBusqueda`,`Tema`,`Descripcion`) VALUES ('Sebastiano Ottey',742,'Genero','Terror');
INSERT INTO `` (`Nombre`,`idBusqueda`,`Tema`,`Descripcion`) VALUES ('Meaghan Pittel',755,'AnoLanzamiento','1997-01-16');
INSERT INTO `` (`Nombre`,`idBusqueda`,`Tema`,`Descripcion`) VALUES ('Berna Grocutt',759,'Genero','Romance');
INSERT INTO `` (`Nombre`,`idBusqueda`,`Tema`,`Descripcion`) VALUES ('Thalia Cusick',764,'Genero','Comedia');
INSERT INTO `` (`Nombre`,`idBusqueda`,`Tema`,`Descripcion`) VALUES ('Orelia Lotze',767,'Director','Francis Ford Coppola');
INSERT INTO `` (`Nombre`,`idBusqueda`,`Tema`,`Descripcion`) VALUES ('Lanie Abeau',785,'Director','Spike Lee');
INSERT INTO `` (`Nombre`,`idBusqueda`,`Tema`,`Descripcion`) VALUES ('Meaghan Pittel',789,'Titulo','The Iron Giant');
INSERT INTO `` (`Nombre`,`idBusqueda`,`Tema`,`Descripcion`) VALUES ('Marcello Kliesl',793,'Actor ','Tom Hanks');
INSERT INTO `` (`Nombre`,`idBusqueda`,`Tema`,`Descripcion`) VALUES ('Zechariah Dessant',802,'Genero','Comedia');
INSERT INTO `` (`Nombre`,`idBusqueda`,`Tema`,`Descripcion`) VALUES ('Margaretha Kloss',836,'AnoLanzamiento','1931-11-02');
INSERT INTO `` (`Nombre`,`idBusqueda`,`Tema`,`Descripcion`) VALUES ('Florette Khan',867,'Titulo','2001: A Space Odyssey');
INSERT INTO `` (`Nombre`,`idBusqueda`,`Tema`,`Descripcion`) VALUES ('Shari Drewe',870,'Director','Alfred Hitchcock');
INSERT INTO `` (`Nombre`,`idBusqueda`,`Tema`,`Descripcion`) VALUES ('Hunter Fife',875,'Genero','Romantica');
INSERT INTO `` (`Nombre`,`idBusqueda`,`Tema`,`Descripcion`) VALUES ('Vergil Wintringham',905,'Director','Wes Anderson');
INSERT INTO `` (`Nombre`,`idBusqueda`,`Tema`,`Descripcion`) VALUES ('Halimeda Thornham',915,'Titulo','The Hateful Eight');
INSERT INTO `` (`Nombre`,`idBusqueda`,`Tema`,`Descripcion`) VALUES ('Marline Liccardi',917,'Actor','Keanu Reeves');
INSERT INTO `` (`Nombre`,`idBusqueda`,`Tema`,`Descripcion`) VALUES ('Jorgan Fordham',925,'Actor','Cary Elwes');
INSERT INTO `` (`Nombre`,`idBusqueda`,`Tema`,`Descripcion`) VALUES ('Velvet Attack',1005,'Genero','Romantica');
INSERT INTO `` (`Nombre`,`idBusqueda`,`Tema`,`Descripcion`) VALUES ('Halimeda Thornham',1006,'Actor','Matthew Broderick');
INSERT INTO `` (`Nombre`,`idBusqueda`,`Tema`,`Descripcion`) VALUES ('Delcina Alishoner',1012,'AnoLanzamiento','1983-03-12');
INSERT INTO `` (`Nombre`,`idBusqueda`,`Tema`,`Descripcion`) VALUES ('Otes Brideaux',1037,'Genero','Musical');
INSERT INTO `` (`Nombre`,`idBusqueda`,`Tema`,`Descripcion`) VALUES ('Delly Danielsohn',1041,'Calificacion','13');
INSERT INTO `` (`Nombre`,`idBusqueda`,`Tema`,`Descripcion`) VALUES ('Tarah Petrozzi',1048,'Titulo','Star Wars: Episode I - The Phantom Menace');
INSERT INTO `` (`Nombre`,`idBusqueda`,`Tema`,`Descripcion`) VALUES ('Delly Danielsohn',1051,'Actor','Viggo Mortensen');
INSERT INTO `` (`Nombre`,`idBusqueda`,`Tema`,`Descripcion`) VALUES ('Sigvard Ditchburn',1082,'Genero','Aventura');
INSERT INTO `` (`Nombre`,`idBusqueda`,`Tema`,`Descripcion`) VALUES ('Aubert Benaine',1092,'Genero','Romantica');
INSERT INTO `` (`Nombre`,`idBusqueda`,`Tema`,`Descripcion`) VALUES ('Chauncey Juniper',1093,'Genero','Terror');
INSERT INTO `` (`Nombre`,`idBusqueda`,`Tema`,`Descripcion`) VALUES ('Rhona Abbess',1104,'Genero','Suspenso');
INSERT INTO `` (`Nombre`,`idBusqueda`,`Tema`,`Descripcion`) VALUES ('Delly Danielsohn',1119,'Director','David Fincher');
INSERT INTO `` (`Nombre`,`idBusqueda`,`Tema`,`Descripcion`) VALUES ('Vergil Wintringham',1143,'Titulo','Saving Private Ryan');
INSERT INTO `` (`Nombre`,`idBusqueda`,`Tema`,`Descripcion`) VALUES ('Dolorita Scamp',1147,'Director','Alfred Hitchcock');
INSERT INTO `` (`Nombre`,`idBusqueda`,`Tema`,`Descripcion`) VALUES ('Alexandros Presley',1186,'Actor','Jesse Eisenberg');
INSERT INTO `` (`Nombre`,`idBusqueda`,`Tema`,`Descripcion`) VALUES ('Regen Tumelty',1198,'AnoLanzamiento','1925-12-12');
INSERT INTO `` (`Nombre`,`idBusqueda`,`Tema`,`Descripcion`) VALUES ('Trace Janaszkiewicz',1226,'Titulo','Pulp Fiction');
INSERT INTO `` (`Nombre`,`idBusqueda`,`Tema`,`Descripcion`) VALUES ('Joellyn Robottham',1269,'Director','Spike Lee');
INSERT INTO `` (`Nombre`,`idBusqueda`,`Tema`,`Descripcion`) VALUES ('Wynny Kenn',1276,'Actor','Samuel L. Jackson');
INSERT INTO `` (`Nombre`,`idBusqueda`,`Tema`,`Descripcion`) VALUES ('Wynny Kenn',1278,'Director','Stanley Kubrick');
INSERT INTO `` (`Nombre`,`idBusqueda`,`Tema`,`Descripcion`) VALUES ('Piper Dunbabin',1291,'Genero','Terror');
INSERT INTO `` (`Nombre`,`idBusqueda`,`Tema`,`Descripcion`) VALUES ('Madelon Kagan',1308,'Genero','Accion');
INSERT INTO `` (`Nombre`,`idBusqueda`,`Tema`,`Descripcion`) VALUES ('Marie Whorlton',1321,'Genero','Accion');
INSERT INTO `` (`Nombre`,`idBusqueda`,`Tema`,`Descripcion`) VALUES ('Arlyne Carme',1330,'Genero','Accion');
INSERT INTO `` (`Nombre`,`idBusqueda`,`Tema`,`Descripcion`) VALUES ('Josie Churchill',1404,'Calificacion','18');
INSERT INTO `` (`Nombre`,`idBusqueda`,`Tema`,`Descripcion`) VALUES ('Maggy Chartres',1422,'AnoLanzamiento','2003-06-07');
INSERT INTO `` (`Nombre`,`idBusqueda`,`Tema`,`Descripcion`) VALUES ('Beverlee Phelps',1462,'Titulo','Mulan');
INSERT INTO `` (`Nombre`,`idBusqueda`,`Tema`,`Descripcion`) VALUES ('Regen Tumelty',1466,'Titulo','The Matrix');
INSERT INTO `` (`Nombre`,`idBusqueda`,`Tema`,`Descripcion`) VALUES ('Wynny Kenn',1473,'Calificacion','ATP');
INSERT INTO `` (`Nombre`,`idBusqueda`,`Tema`,`Descripcion`) VALUES ('Torr Bramer',1487,'Titulo','The Breakfast Club');
INSERT INTO `` (`Nombre`,`idBusqueda`,`Tema`,`Descripcion`) VALUES ('Beverlee Phelps',1510,'Director','Christopher Nolan');
INSERT INTO `` (`Nombre`,`idBusqueda`,`Tema`,`Descripcion`) VALUES ('Fran Danbi',1512,'AnoLanzamiento','1917-12-13');
INSERT INTO `` (`Nombre`,`idBusqueda`,`Tema`,`Descripcion`) VALUES ('Ichabod Beeching',1545,'Genero','Comedia');
INSERT INTO `` (`Nombre`,`idBusqueda`,`Tema`,`Descripcion`) VALUES ('Cassius Dorre',1552,'Calificacion','1900-01-17');
INSERT INTO `` (`Nombre`,`idBusqueda`,`Tema`,`Descripcion`) VALUES ('Regen Tumelty',1560,'Actor','Elijah Wood');
INSERT INTO `` (`Nombre`,`idBusqueda`,`Tema`,`Descripcion`) VALUES ('Delcina Alishoner',1566,'Actor','John Travolta');
INSERT INTO `` (`Nombre`,`idBusqueda`,`Tema`,`Descripcion`) VALUES ('Jorgan Fordham',1573,'Titulo','Star Wars: Episode IV - A New Hope');
INSERT INTO `` (`Nombre`,`idBusqueda`,`Tema`,`Descripcion`) VALUES ('Ronny Flahy',1574,'Genero','Comedia');
INSERT INTO `` (`Nombre`,`idBusqueda`,`Tema`,`Descripcion`) VALUES ('Cassius Dorre',1583,'Director','Steven Spielberg');
INSERT INTO `` (`Nombre`,`idBusqueda`,`Tema`,`Descripcion`) VALUES ('Tarah Petrozzi',1587,'Actor','Ming-Na Wen');
INSERT INTO `` (`Nombre`,`idBusqueda`,`Tema`,`Descripcion`) VALUES ('Rodie Spellward',1590,'Director','Stanley Kubrick');
INSERT INTO `` (`Nombre`,`idBusqueda`,`Tema`,`Descripcion`) VALUES ('Orelia Lotze',1592,'Calificacion','16');
INSERT INTO `` (`Nombre`,`idBusqueda`,`Tema`,`Descripcion`) VALUES ('Rodie Spellward',1598,'Titulo','Gone with the Wind');
INSERT INTO `` (`Nombre`,`idBusqueda`,`Tema`,`Descripcion`) VALUES ('Beatrice Watterson',1654,'Titulo','The Sixth Sense');
INSERT INTO `` (`Nombre`,`idBusqueda`,`Tema`,`Descripcion`) VALUES ('Vergil Wintringham',1662,'Calificacion','16');
INSERT INTO `` (`Nombre`,`idBusqueda`,`Tema`,`Descripcion`) VALUES ('Warren Jaimez',1692,'Genero','Suspenso');
INSERT INTO `` (`Nombre`,`idBusqueda`,`Tema`,`Descripcion`) VALUES ('Marcello Kliesl',1706,'Titulo','Titanic');
INSERT INTO `` (`Nombre`,`idBusqueda`,`Tema`,`Descripcion`) VALUES ('Ilise Manoelli',1707,'AnoLanzamiento','1948-10-20');
INSERT INTO `` (`Nombre`,`idBusqueda`,`Tema`,`Descripcion`) VALUES ('Iris Crumly',1745,'Calificacion','18');
INSERT INTO `` (`Nombre`,`idBusqueda`,`Tema`,`Descripcion`) VALUES ('Beverlee Phelps',1764,'Calificacion','16');
INSERT INTO `` (`Nombre`,`idBusqueda`,`Tema`,`Descripcion`) VALUES ('Sandor Zelley',1801,'Genero','Musical');
INSERT INTO `` (`Nombre`,`idBusqueda`,`Tema`,`Descripcion`) VALUES ('Hedda Di Giacomettino',1815,'Genero','Terror');
INSERT INTO `` (`Nombre`,`idBusqueda`,`Tema`,`Descripcion`) VALUES ('Melody Swinburn',1818,'Genero','Terror');
INSERT INTO `` (`Nombre`,`idBusqueda`,`Tema`,`Descripcion`) VALUES ('Karoly Nanson',1862,'Titulo','The Social Network');
INSERT INTO `` (`Nombre`,`idBusqueda`,`Tema`,`Descripcion`) VALUES ('Orelia Lotze',1872,'Titulo','The Princess Bride');
INSERT INTO `` (`Nombre`,`idBusqueda`,`Tema`,`Descripcion`) VALUES ('Josie Churchill',1925,'Actor','Hayden Christensen');
INSERT INTO `` (`Nombre`,`idBusqueda`,`Tema`,`Descripcion`) VALUES ('Delcina Alishoner',1938,'Titulo','Aladdin');
INSERT INTO `` (`Nombre`,`idBusqueda`,`Tema`,`Descripcion`) VALUES ('Karoly Nanson',1948,'Director','Francis Ford Coppola');
INSERT INTO `` (`Nombre`,`idBusqueda`,`Tema`,`Descripcion`) VALUES ('Ellen Blasiak',1987,'Genero','Romantica');
INSERT INTO `` (`Nombre`,`idBusqueda`,`Tema`,`Descripcion`) VALUES ('Marline Liccardi',1992,'Director','Alfred Hitchcock');
INSERT INTO `` (`Nombre`,`idBusqueda`,`Tema`,`Descripcion`) VALUES ('Josie Churchill',1997,'Director','Spike Lee');
INSERT INTO `` (`Nombre`,`idBusqueda`,`Tema`,`Descripcion`) VALUES ('Rodie Spellward',3098,'Calificacion','18');
INSERT INTO `` (`Nombre`,`idBusqueda`,`Tema`,`Descripcion`) VALUES ('Lanie Abeau',5829,'Calificacion','16');
INSERT INTO `` (`Nombre`,`idBusqueda`,`Tema`,`Descripcion`) VALUES ('Karoly Nanson',9437,'Calificacion','16');
