/*
-- Query: SELECT * FROM tp_bd_2023.contenido
LIMIT 0, 1000

-- Date: 2023-06-01 21:00
*/
INSERT INTO `` (`idContenido`,`TitOriginal`,`Director`,`Calificacion`,`Duracion`,`lanzamiento`) VALUES (5,'Harry Potter and the Philosopher\'s Stone','Francis Ford Coppola','18',198,'1941-04-03');
INSERT INTO `` (`idContenido`,`TitOriginal`,`Director`,`Calificacion`,`Duracion`,`lanzamiento`) VALUES (24,'True Detective','Wes Anderson','18',241,'1973-09-15');
INSERT INTO `` (`idContenido`,`TitOriginal`,`Director`,`Calificacion`,`Duracion`,`lanzamiento`) VALUES (26,'The Truman Show','Martin Scorsese','16',190,'1939-12-07');
INSERT INTO `` (`idContenido`,`TitOriginal`,`Director`,`Calificacion`,`Duracion`,`lanzamiento`) VALUES (70,'Mindhunter','David Fincher','18',185,'1931-11-02');
INSERT INTO `` (`idContenido`,`TitOriginal`,`Director`,`Calificacion`,`Duracion`,`lanzamiento`) VALUES (140,'Aladdin','Alfred Hitchcock','16',194,'1998-06-07');
INSERT INTO `` (`idContenido`,`TitOriginal`,`Director`,`Calificacion`,`Duracion`,`lanzamiento`) VALUES (145,'Chernobyl','Francis Ford Coppola','16',111,'1976-12-05');
INSERT INTO `` (`idContenido`,`TitOriginal`,`Director`,`Calificacion`,`Duracion`,`lanzamiento`) VALUES (149,'Citizenfour','Wes Anderson','ATP',108,'1976-10-04');
INSERT INTO `` (`idContenido`,`TitOriginal`,`Director`,`Calificacion`,`Duracion`,`lanzamiento`) VALUES (152,'Gone with the Wind','Spike Lee','16',72,'1959-03-07');
INSERT INTO `` (`idContenido`,`TitOriginal`,`Director`,`Calificacion`,`Duracion`,`lanzamiento`) VALUES (158,'The Wizard of Oz','Stanley Kubrick','ATP',81,'1993-09-03');
INSERT INTO `` (`idContenido`,`TitOriginal`,`Director`,`Calificacion`,`Duracion`,`lanzamiento`) VALUES (178,'Peaky Blinders','Francis Ford Coppola','18',58,'1934-09-30');
INSERT INTO `` (`idContenido`,`TitOriginal`,`Director`,`Calificacion`,`Duracion`,`lanzamiento`) VALUES (226,'The Marvelous Mrs. Maisel','Steven Spielberg','ATP',100,'1997-01-16');
INSERT INTO `` (`idContenido`,`TitOriginal`,`Director`,`Calificacion`,`Duracion`,`lanzamiento`) VALUES (231,'Man on Wire','Quentin Tarantino','13',39,'2010-03-07');
INSERT INTO `` (`idContenido`,`TitOriginal`,`Director`,`Calificacion`,`Duracion`,`lanzamiento`) VALUES (252,'Friends','Alfred Hitchcock','ATP',138,'1964-10-03');
INSERT INTO `` (`idContenido`,`TitOriginal`,`Director`,`Calificacion`,`Duracion`,`lanzamiento`) VALUES (275,'The Grand Budapest Hotel','Christopher Nolan','18',150,'1970-10-08');
INSERT INTO `` (`idContenido`,`TitOriginal`,`Director`,`Calificacion`,`Duracion`,`lanzamiento`) VALUES (300,'Lost','Steven Spielberg','ATP',115,'1975-12-26');
INSERT INTO `` (`idContenido`,`TitOriginal`,`Director`,`Calificacion`,`Duracion`,`lanzamiento`) VALUES (301,'The Little Mermaid','Steven Spielberg','18',160,'1964-09-20');
INSERT INTO `` (`idContenido`,`TitOriginal`,`Director`,`Calificacion`,`Duracion`,`lanzamiento`) VALUES (303,'Jiro Dreams of Sushi','David Fincher','18',73,'1987-03-16');
INSERT INTO `` (`idContenido`,`TitOriginal`,`Director`,`Calificacion`,`Duracion`,`lanzamiento`) VALUES (304,'Sons of Anarchy','Quentin Tarantino','18',66,'1917-12-13');
INSERT INTO `` (`idContenido`,`TitOriginal`,`Director`,`Calificacion`,`Duracion`,`lanzamiento`) VALUES (307,'Signs','Christopher Nolan','ATP',140,'1988-09-30');
INSERT INTO `` (`idContenido`,`TitOriginal`,`Director`,`Calificacion`,`Duracion`,`lanzamiento`) VALUES (310,'The Office','Quentin Tarantino','16',400,'1936-07-19');
INSERT INTO `` (`idContenido`,`TitOriginal`,`Director`,`Calificacion`,`Duracion`,`lanzamiento`) VALUES (335,'The Walking Dead','Alfred Hitchcock','13',189,'1999-08-23');
INSERT INTO `` (`idContenido`,`TitOriginal`,`Director`,`Calificacion`,`Duracion`,`lanzamiento`) VALUES (376,'Narcos','Stanley Kubrick','16',180,'1993-01-02');
INSERT INTO `` (`idContenido`,`TitOriginal`,`Director`,`Calificacion`,`Duracion`,`lanzamiento`) VALUES (383,'Parks and Recreation','Martin Scorsese','18',190,'1935-12-02');
INSERT INTO `` (`idContenido`,`TitOriginal`,`Director`,`Calificacion`,`Duracion`,`lanzamiento`) VALUES (384,'The Godfather: Part II','David Fincher','18',123,'1969-05-16');
INSERT INTO `` (`idContenido`,`TitOriginal`,`Director`,`Calificacion`,`Duracion`,`lanzamiento`) VALUES (422,'The Lord of the Rings: The Fellowship of the Ring','Alfred Hitchcock','18',123,'1912-10-08');
INSERT INTO `` (`idContenido`,`TitOriginal`,`Director`,`Calificacion`,`Duracion`,`lanzamiento`) VALUES (567,'The Boys','Christopher Nolan','18',81,'1948-10-20');
INSERT INTO `` (`idContenido`,`TitOriginal`,`Director`,`Calificacion`,`Duracion`,`lanzamiento`) VALUES (568,'The Lord of the Rings: The Fellowship of the Ring','Spike Lee','16',21,'1933-01-16');
INSERT INTO `` (`idContenido`,`TitOriginal`,`Director`,`Calificacion`,`Duracion`,`lanzamiento`) VALUES (572,'The Exorcist','Alfred Hitchcock','ATP',189,'1969-10-19');
INSERT INTO `` (`idContenido`,`TitOriginal`,`Director`,`Calificacion`,`Duracion`,`lanzamiento`) VALUES (604,'Harry Potter and the Half-Blood Prince','Alfred Hitchcock','13',126,'1932-07-04');
INSERT INTO `` (`idContenido`,`TitOriginal`,`Director`,`Calificacion`,`Duracion`,`lanzamiento`) VALUES (615,'Harry Potter and the Chamber of Secrets','Christopher Nolan','18',144,'1947-01-30');
INSERT INTO `` (`idContenido`,`TitOriginal`,`Director`,`Calificacion`,`Duracion`,`lanzamiento`) VALUES (680,'Harry Potter and the Prisoner of Azkaban','Quentin Tarantino','16',87,'2010-04-13');
INSERT INTO `` (`idContenido`,`TitOriginal`,`Director`,`Calificacion`,`Duracion`,`lanzamiento`) VALUES (684,'The Social Network','David Fincher','16',119,'1941-06-08');
INSERT INTO `` (`idContenido`,`TitOriginal`,`Director`,`Calificacion`,`Duracion`,`lanzamiento`) VALUES (707,'Better Call Saul','Steven Spielberg','16',184,'1934-11-26');
INSERT INTO `` (`idContenido`,`TitOriginal`,`Director`,`Calificacion`,`Duracion`,`lanzamiento`) VALUES (742,'2001: A Space Odyssey','Spike Lee','16',103,'2014-10-30');
INSERT INTO `` (`idContenido`,`TitOriginal`,`Director`,`Calificacion`,`Duracion`,`lanzamiento`) VALUES (755,'The Sopranos','David Fincher','ATP',140,'1964-02-26');
INSERT INTO `` (`idContenido`,`TitOriginal`,`Director`,`Calificacion`,`Duracion`,`lanzamiento`) VALUES (759,'Pulp Fiction','Wes Anderson','18',106,'1944-10-06');
INSERT INTO `` (`idContenido`,`TitOriginal`,`Director`,`Calificacion`,`Duracion`,`lanzamiento`) VALUES (764,'The Breakfast Club','David Fincher','18',180,'1932-10-17');
INSERT INTO `` (`idContenido`,`TitOriginal`,`Director`,`Calificacion`,`Duracion`,`lanzamiento`) VALUES (767,'House of Cards','Martin Scorsese','ATP',194,'1943-04-23');
INSERT INTO `` (`idContenido`,`TitOriginal`,`Director`,`Calificacion`,`Duracion`,`lanzamiento`) VALUES (785,'Brooklyn Nine-Nine','Stanley Kubrick','16',195,'2009-10-22');
INSERT INTO `` (`idContenido`,`TitOriginal`,`Director`,`Calificacion`,`Duracion`,`lanzamiento`) VALUES (789,'Vikings','Wes Anderson','13',54,'1977-10-08');
INSERT INTO `` (`idContenido`,`TitOriginal`,`Director`,`Calificacion`,`Duracion`,`lanzamiento`) VALUES (793,'Toy Story','Alfred Hitchcock','16',164,'1988-08-13');
INSERT INTO `` (`idContenido`,`TitOriginal`,`Director`,`Calificacion`,`Duracion`,`lanzamiento`) VALUES (802,'The Others','Wes Anderson','13',131,'1918-05-09');
INSERT INTO `` (`idContenido`,`TitOriginal`,`Director`,`Calificacion`,`Duracion`,`lanzamiento`) VALUES (836,'The West Wing','Francis Ford Coppola','16',95,'2002-07-28');
INSERT INTO `` (`idContenido`,`TitOriginal`,`Director`,`Calificacion`,`Duracion`,`lanzamiento`) VALUES (867,'The Crown','Quentin Tarantino','ATP',196,'1924-05-15');
INSERT INTO `` (`idContenido`,`TitOriginal`,`Director`,`Calificacion`,`Duracion`,`lanzamiento`) VALUES (870,'Lucifer','Spike Lee','ATP',200,'1925-12-12');
INSERT INTO `` (`idContenido`,`TitOriginal`,`Director`,`Calificacion`,`Duracion`,`lanzamiento`) VALUES (875,'The Lion King II: Simba\'s Pride','Stanley Kubrick','ATP',141,'1938-07-19');
INSERT INTO `` (`idContenido`,`TitOriginal`,`Director`,`Calificacion`,`Duracion`,`lanzamiento`) VALUES (905,'Grey\'s Anatomy','Alfred Hitchcock','16',119,'1919-10-16');
INSERT INTO `` (`idContenido`,`TitOriginal`,`Director`,`Calificacion`,`Duracion`,`lanzamiento`) VALUES (915,'Breaking Bad','Martin Scorsese','13',121,'1982-01-24');
INSERT INTO `` (`idContenido`,`TitOriginal`,`Director`,`Calificacion`,`Duracion`,`lanzamiento`) VALUES (917,'Harry Potter and the Order of the Phoenix','Wes Anderson','ATP',128,'2012-04-18');
INSERT INTO `` (`idContenido`,`TitOriginal`,`Director`,`Calificacion`,`Duracion`,`lanzamiento`) VALUES (925,'The Silence of the Lambs','David Fincher','18',138,'2012-05-12');
INSERT INTO `` (`idContenido`,`TitOriginal`,`Director`,`Calificacion`,`Duracion`,`lanzamiento`) VALUES (1005,'Django Unchained','Quentin Tarantino','18',100,'1950-02-14');
INSERT INTO `` (`idContenido`,`TitOriginal`,`Director`,`Calificacion`,`Duracion`,`lanzamiento`) VALUES (1006,'Star Wars: Episode V - The Empire Strikes Back','Wes Anderson','18',120,'1927-12-04');
INSERT INTO `` (`idContenido`,`TitOriginal`,`Director`,`Calificacion`,`Duracion`,`lanzamiento`) VALUES (1012,'24','Martin Scorsese','13',107,'1955-06-20');
INSERT INTO `` (`idContenido`,`TitOriginal`,`Director`,`Calificacion`,`Duracion`,`lanzamiento`) VALUES (1037,'The Princess Bride','Quentin Tarantino','13',146,'1922-01-29');
INSERT INTO `` (`idContenido`,`TitOriginal`,`Director`,`Calificacion`,`Duracion`,`lanzamiento`) VALUES (1041,'Amy','Steven Spielberg','ATP',173,'1988-12-20');
INSERT INTO `` (`idContenido`,`TitOriginal`,`Director`,`Calificacion`,`Duracion`,`lanzamiento`) VALUES (1048,'Game of Thrones','Francis Ford Coppola','ATP',139,'1912-04-12');
INSERT INTO `` (`idContenido`,`TitOriginal`,`Director`,`Calificacion`,`Duracion`,`lanzamiento`) VALUES (1051,'The Departed','Christopher Nolan','16',149,'1924-10-15');
INSERT INTO `` (`idContenido`,`TitOriginal`,`Director`,`Calificacion`,`Duracion`,`lanzamiento`) VALUES (1082,'The Hateful Eight','Stanley Kubrick','ATP',59,'1962-11-01');
INSERT INTO `` (`idContenido`,`TitOriginal`,`Director`,`Calificacion`,`Duracion`,`lanzamiento`) VALUES (1092,'The Lord of the Rings: The Return of the King','Martin Scorsese','16',69,'1932-03-13');
INSERT INTO `` (`idContenido`,`TitOriginal`,`Director`,`Calificacion`,`Duracion`,`lanzamiento`) VALUES (1093,'Star Wars: Episode III - Revenge of the Sith','Francis Ford Coppola','ATP',187,'2021-06-29');
INSERT INTO `` (`idContenido`,`TitOriginal`,`Director`,`Calificacion`,`Duracion`,`lanzamiento`) VALUES (1104,'Star Wars: Episode II - Attack of the Clones','Wes Anderson','16',125,'1954-03-06');
INSERT INTO `` (`idContenido`,`TitOriginal`,`Director`,`Calificacion`,`Duracion`,`lanzamiento`) VALUES (1119,'Homeland','Francis Ford Coppola','13',47,'1930-09-12');
INSERT INTO `` (`idContenido`,`TitOriginal`,`Director`,`Calificacion`,`Duracion`,`lanzamiento`) VALUES (1143,'Star Wars: Episode VI - Return of the Jedi','Spike Lee','13',144,'1943-03-01');
INSERT INTO `` (`idContenido`,`TitOriginal`,`Director`,`Calificacion`,`Duracion`,`lanzamiento`) VALUES (1147,'Cobra Kai','Wes Anderson','13',100,'1983-03-12');
INSERT INTO `` (`idContenido`,`TitOriginal`,`Director`,`Calificacion`,`Duracion`,`lanzamiento`) VALUES (1186,'The Incredibles','Wes Anderson','18',195,'1915-02-20');
INSERT INTO `` (`idContenido`,`TitOriginal`,`Director`,`Calificacion`,`Duracion`,`lanzamiento`) VALUES (1198,'Orange Is the New Black','Alfred Hitchcock','16',161,'1915-11-10');
INSERT INTO `` (`idContenido`,`TitOriginal`,`Director`,`Calificacion`,`Duracion`,`lanzamiento`) VALUES (1226,'The Witcher','Quentin Tarantino','13',22,'1920-06-11');
INSERT INTO `` (`idContenido`,`TitOriginal`,`Director`,`Calificacion`,`Duracion`,`lanzamiento`) VALUES (1269,'The Umbrella Academy','Alfred Hitchcock','16',100,'2003-06-07');
INSERT INTO `` (`idContenido`,`TitOriginal`,`Director`,`Calificacion`,`Duracion`,`lanzamiento`) VALUES (1276,'Inside Out','Spike Lee','ATP',162,'1936-12-23');
INSERT INTO `` (`idContenido`,`TitOriginal`,`Director`,`Calificacion`,`Duracion`,`lanzamiento`) VALUES (1278,'Fargo','Martin Scorsese','16',61,'1924-04-06');
INSERT INTO `` (`idContenido`,`TitOriginal`,`Director`,`Calificacion`,`Duracion`,`lanzamiento`) VALUES (1291,'Saving Private Ryan','Steven Spielberg','18',109,'1976-07-16');
INSERT INTO `` (`idContenido`,`TitOriginal`,`Director`,`Calificacion`,`Duracion`,`lanzamiento`) VALUES (1308,'The Shawshank Redemption','Quentin Tarantino','16',66,'1926-08-14');
INSERT INTO `` (`idContenido`,`TitOriginal`,`Director`,`Calificacion`,`Duracion`,`lanzamiento`) VALUES (1321,'The Matrix','Alfred Hitchcock','16',57,'1976-03-11');
INSERT INTO `` (`idContenido`,`TitOriginal`,`Director`,`Calificacion`,`Duracion`,`lanzamiento`) VALUES (1330,'Star Wars: Episode IV - A New Hope','Francis Ford Coppola','18',180,'1961-05-25');
INSERT INTO `` (`idContenido`,`TitOriginal`,`Director`,`Calificacion`,`Duracion`,`lanzamiento`) VALUES (1404,'March of the Penguins','Spike Lee','16',149,'1930-05-06');
INSERT INTO `` (`idContenido`,`TitOriginal`,`Director`,`Calificacion`,`Duracion`,`lanzamiento`) VALUES (1422,'The Wire','Spike Lee','18',99,'1984-08-30');
INSERT INTO `` (`idContenido`,`TitOriginal`,`Director`,`Calificacion`,`Duracion`,`lanzamiento`) VALUES (1462,'La Casa de Papel ','Spike Lee','18',146,'1954-10-27');
INSERT INTO `` (`idContenido`,`TitOriginal`,`Director`,`Calificacion`,`Duracion`,`lanzamiento`) VALUES (1466,'Sherlock','Francis Ford Coppola','13',123,'1974-09-10');
INSERT INTO `` (`idContenido`,`TitOriginal`,`Director`,`Calificacion`,`Duracion`,`lanzamiento`) VALUES (1473,'Planet Earth','Francis Ford Coppola','13',118,'1989-10-30');
INSERT INTO `` (`idContenido`,`TitOriginal`,`Director`,`Calificacion`,`Duracion`,`lanzamiento`) VALUES (1487,'The Mandalorian','David Fincher','ATP',121,'1938-04-10');
INSERT INTO `` (`idContenido`,`TitOriginal`,`Director`,`Calificacion`,`Duracion`,`lanzamiento`) VALUES (1510,'The Good Place','Martin Scorsese','13',110,'2009-04-19');
INSERT INTO `` (`idContenido`,`TitOriginal`,`Director`,`Calificacion`,`Duracion`,`lanzamiento`) VALUES (1512,'Succession','Spike Lee','ATP',175,'1979-08-23');
INSERT INTO `` (`idContenido`,`TitOriginal`,`Director`,`Calificacion`,`Duracion`,`lanzamiento`) VALUES (1545,'Goodfellas','Stanley Kubrick','16',60,'2014-11-18');
INSERT INTO `` (`idContenido`,`TitOriginal`,`Director`,`Calificacion`,`Duracion`,`lanzamiento`) VALUES (1552,'Blackfish','Francis Ford Coppola','18',102,'2005-04-04');
INSERT INTO `` (`idContenido`,`TitOriginal`,`Director`,`Calificacion`,`Duracion`,`lanzamiento`) VALUES (1560,'Jurassic Park','Alfred Hitchcock','16',162,'1924-01-21');
INSERT INTO `` (`idContenido`,`TitOriginal`,`Director`,`Calificacion`,`Duracion`,`lanzamiento`) VALUES (1566,'The Godfather: Part III','Alfred Hitchcock','ATP',96,'1915-08-29');
INSERT INTO `` (`idContenido`,`TitOriginal`,`Director`,`Calificacion`,`Duracion`,`lanzamiento`) VALUES (1573,'Stranger Things','Wes Anderson','ATP',122,'2015-02-11');
INSERT INTO `` (`idContenido`,`TitOriginal`,`Director`,`Calificacion`,`Duracion`,`lanzamiento`) VALUES (1574,'Mulan','Christopher Nolan','18',56,'2016-09-25');
INSERT INTO `` (`idContenido`,`TitOriginal`,`Director`,`Calificacion`,`Duracion`,`lanzamiento`) VALUES (1583,'The Big Bang Theory','David Fincher','13',137,'2009-06-26');
INSERT INTO `` (`idContenido`,`TitOriginal`,`Director`,`Calificacion`,`Duracion`,`lanzamiento`) VALUES (1587,'Fight Club','Stanley Kubrick','16',191,'1992-08-15');
INSERT INTO `` (`idContenido`,`TitOriginal`,`Director`,`Calificacion`,`Duracion`,`lanzamiento`) VALUES (1590,'How to Get Away with Murder','Wes Anderson','13',63,'2000-07-22');
INSERT INTO `` (`idContenido`,`TitOriginal`,`Director`,`Calificacion`,`Duracion`,`lanzamiento`) VALUES (1592,'Free Solo','Steven Spielberg','18',60,'1937-09-25');
INSERT INTO `` (`idContenido`,`TitOriginal`,`Director`,`Calificacion`,`Duracion`,`lanzamiento`) VALUES (1598,'Westworld','Alfred Hitchcock','13',156,'2008-02-05');
INSERT INTO `` (`idContenido`,`TitOriginal`,`Director`,`Calificacion`,`Duracion`,`lanzamiento`) VALUES (1654,'Ozark','Quentin Tarantino','13',150,'1974-02-09');
INSERT INTO `` (`idContenido`,`TitOriginal`,`Director`,`Calificacion`,`Duracion`,`lanzamiento`) VALUES (1662,'The Act of Killing','Martin Scorsese','ATP',88,'1955-11-08');
INSERT INTO `` (`idContenido`,`TitOriginal`,`Director`,`Calificacion`,`Duracion`,`lanzamiento`) VALUES (1692,'Star Wars: Episode I - The Phantom Menace','Quentin Tarantino','13',55,'1988-02-19');
INSERT INTO `` (`idContenido`,`TitOriginal`,`Director`,`Calificacion`,`Duracion`,`lanzamiento`) VALUES (1706,'Dark','Quentin Tarantino','16',120,'2002-06-07');
INSERT INTO `` (`idContenido`,`TitOriginal`,`Director`,`Calificacion`,`Duracion`,`lanzamiento`) VALUES (1707,'Black Sails','David Fincher','13',70,'1956-05-21');
INSERT INTO `` (`idContenido`,`TitOriginal`,`Director`,`Calificacion`,`Duracion`,`lanzamiento`) VALUES (1745,'The Cove','Wes Anderson','13',186,'1916-05-29');
INSERT INTO `` (`idContenido`,`TitOriginal`,`Director`,`Calificacion`,`Duracion`,`lanzamiento`) VALUES (1764,'COVID-19: Detras del virus','Alfred Hitchcock','',112,'2021-03-29');
INSERT INTO `` (`idContenido`,`TitOriginal`,`Director`,`Calificacion`,`Duracion`,`lanzamiento`) VALUES (1801,'The Sixth Sense','Francis Ford Coppola','ATP',73,'1970-05-03');
INSERT INTO `` (`idContenido`,`TitOriginal`,`Director`,`Calificacion`,`Duracion`,`lanzamiento`) VALUES (1815,'The Iron Giant','David Fincher','16',158,'1920-04-03');
INSERT INTO `` (`idContenido`,`TitOriginal`,`Director`,`Calificacion`,`Duracion`,`lanzamiento`) VALUES (1818,'Nemo','Martin Scorsese','16',20,'1934-09-14');
INSERT INTO `` (`idContenido`,`TitOriginal`,`Director`,`Calificacion`,`Duracion`,`lanzamiento`) VALUES (1862,'The Handmaid\'s Tale','Alfred Hitchcock','16',163,'1950-09-05');
INSERT INTO `` (`idContenido`,`TitOriginal`,`Director`,`Calificacion`,`Duracion`,`lanzamiento`) VALUES (1872,'The Expanse','Alfred Hitchcock','13',179,'1962-09-11');
INSERT INTO `` (`idContenido`,`TitOriginal`,`Director`,`Calificacion`,`Duracion`,`lanzamiento`) VALUES (1925,'Harry Potter and the Goblet of Fire','Steven Spielberg','ATP',165,'1958-11-02');
INSERT INTO `` (`idContenido`,`TitOriginal`,`Director`,`Calificacion`,`Duracion`,`lanzamiento`) VALUES (1938,'Black Mirror','Alfred Hitchcock','13',191,'1947-04-27');
INSERT INTO `` (`idContenido`,`TitOriginal`,`Director`,`Calificacion`,`Duracion`,`lanzamiento`) VALUES (1948,'The Haunting of Hill House','Spike Lee','13',179,'1913-05-16');
INSERT INTO `` (`idContenido`,`TitOriginal`,`Director`,`Calificacion`,`Duracion`,`lanzamiento`) VALUES (1987,'Titanic','Christopher Nolan','13',136,'1923-01-22');
INSERT INTO `` (`idContenido`,`TitOriginal`,`Director`,`Calificacion`,`Duracion`,`lanzamiento`) VALUES (1992,'Supernatural','Wes Anderson','ATP',187,'1938-04-26');
INSERT INTO `` (`idContenido`,`TitOriginal`,`Director`,`Calificacion`,`Duracion`,`lanzamiento`) VALUES (1997,'The Americans','Stanley Kubrick','13',109,'2008-11-03');
INSERT INTO `` (`idContenido`,`TitOriginal`,`Director`,`Calificacion`,`Duracion`,`lanzamiento`) VALUES (3098,'Virus desenmascarado','Martin Scorsese','',64,'2023-05-02');
INSERT INTO `` (`idContenido`,`TitOriginal`,`Director`,`Calificacion`,`Duracion`,`lanzamiento`) VALUES (5829,'Pandemia: Un mundo en crisis','Francis Ford Coppola','',85,'2020-07-15');
INSERT INTO `` (`idContenido`,`TitOriginal`,`Director`,`Calificacion`,`Duracion`,`lanzamiento`) VALUES (9437,'En la primera linea: Historias de la pandemia','David Fincher','',47,'2022-11-10');
