/*
-- Query: SELECT * FROM tp_bd_2023.actoressecundariosserie
LIMIT 0, 1000

-- Date: 2023-06-01 20:58
*/
INSERT INTO `` (`TitIngles`,`ActoresSecundarios`) VALUES ('The Expanse','Jared Harris');
INSERT INTO `` (`TitIngles`,`ActoresSecundarios`) VALUES ('Chernobyl','Alvaro Morte');
INSERT INTO `` (`TitIngles`,`ActoresSecundarios`) VALUES ('Money Heist','Joseph Fiennes');
INSERT INTO `` (`TitIngles`,`ActoresSecundarios`) VALUES ('The Handmaid\'s Tale','Evan Rachel Wood');
INSERT INTO `` (`TitIngles`,`ActoresSecundarios`) VALUES ('Westworld','Cillian Murphy');
INSERT INTO `` (`TitIngles`,`ActoresSecundarios`) VALUES ('Peaky Blinders','Pedro Pascal');
INSERT INTO `` (`TitIngles`,`ActoresSecundarios`) VALUES ('The Mandalorian','Henry Cavill');
INSERT INTO `` (`TitIngles`,`ActoresSecundarios`) VALUES ('The Witcher','Jason Bateman');
INSERT INTO `` (`TitIngles`,`ActoresSecundarios`) VALUES ('Ozark','Olivia Colman');
INSERT INTO `` (`TitIngles`,`ActoresSecundarios`) VALUES ('The Crown','Louis Hofmann');
INSERT INTO `` (`TitIngles`,`ActoresSecundarios`) VALUES ('Dark','Finn Wolfhard');
INSERT INTO `` (`TitIngles`,`ActoresSecundarios`) VALUES ('Stranger Things','Aaron Paul');
INSERT INTO `` (`TitIngles`,`ActoresSecundarios`) VALUES ('Breaking Bad','Jennifer Aniston');
INSERT INTO `` (`TitIngles`,`ActoresSecundarios`) VALUES ('Game of Thrones','Steve Carell');
INSERT INTO `` (`TitIngles`,`ActoresSecundarios`) VALUES ('Friends','Benedict Cumberbatch');
INSERT INTO `` (`TitIngles`,`ActoresSecundarios`) VALUES ('The Office','Travis Fimmel');
INSERT INTO `` (`TitIngles`,`ActoresSecundarios`) VALUES ('Sherlock','Various actors (anthology series)');
INSERT INTO `` (`TitIngles`,`ActoresSecundarios`) VALUES ('Vikings','Wagner Moura');
INSERT INTO `` (`TitIngles`,`ActoresSecundarios`) VALUES ('Black Mirror','Jonathan Banks');
INSERT INTO `` (`TitIngles`,`ActoresSecundarios`) VALUES ('Narcos','Johnny Galecki');
INSERT INTO `` (`TitIngles`,`ActoresSecundarios`) VALUES ('Better Call Saul','Jessica Brown');
INSERT INTO `` (`TitIngles`,`ActoresSecundarios`) VALUES ('The Big Bang Theory','Abigail Parker');
INSERT INTO `` (`TitIngles`,`ActoresSecundarios`) VALUES ('True Detective','Kevin Reed');
INSERT INTO `` (`TitIngles`,`ActoresSecundarios`) VALUES ('Fargo','Sarah Davis');
INSERT INTO `` (`TitIngles`,`ActoresSecundarios`) VALUES ('Lost','John Smith');
INSERT INTO `` (`TitIngles`,`ActoresSecundarios`) VALUES ('Homeland','Avery Peterson');
INSERT INTO `` (`TitIngles`,`ActoresSecundarios`) VALUES ('The Americans','Kenneth Torres');
INSERT INTO `` (`TitIngles`,`ActoresSecundarios`) VALUES ('Supernatural','Abigail Parker');
INSERT INTO `` (`TitIngles`,`ActoresSecundarios`) VALUES ('The Walking Dead','Emily Johnson');
INSERT INTO `` (`TitIngles`,`ActoresSecundarios`) VALUES ('Grey\'s Anatomy','Grace Bailey');
INSERT INTO `` (`TitIngles`,`ActoresSecundarios`) VALUES ('House of Cards','Andrew Adams');
INSERT INTO `` (`TitIngles`,`ActoresSecundarios`) VALUES ('Brooklyn Nine-Nine','Sarah Davis');
INSERT INTO `` (`TitIngles`,`ActoresSecundarios`) VALUES ('The Good Place','Juanita Ortiz');
INSERT INTO `` (`TitIngles`,`ActoresSecundarios`) VALUES ('The Haunting of Hill House','Juanita Ortiz');
INSERT INTO `` (`TitIngles`,`ActoresSecundarios`) VALUES ('How to Get Away with Murder','Olivia Baker');
INSERT INTO `` (`TitIngles`,`ActoresSecundarios`) VALUES ('Parks and Recreation','Lucas Collins');
INSERT INTO `` (`TitIngles`,`ActoresSecundarios`) VALUES ('Sons of Anarchy','Ava Rodriguez');
INSERT INTO `` (`TitIngles`,`ActoresSecundarios`) VALUES ('Mindhunter','Madison Turner');
INSERT INTO `` (`TitIngles`,`ActoresSecundarios`) VALUES ('Lucifer','Avery Peterson');
INSERT INTO `` (`TitIngles`,`ActoresSecundarios`) VALUES ('The Marvelous Mrs. Maisel','Steven Collins');
INSERT INTO `` (`TitIngles`,`ActoresSecundarios`) VALUES ('Cobra Kai','Paula Diaz');
INSERT INTO `` (`TitIngles`,`ActoresSecundarios`) VALUES ('The Umbrella Academy','Sophia Hernandez');
INSERT INTO `` (`TitIngles`,`ActoresSecundarios`) VALUES ('The Boys','Ava Rodriguez');
INSERT INTO `` (`TitIngles`,`ActoresSecundarios`) VALUES ('Succession','Jessica Brown');
INSERT INTO `` (`TitIngles`,`ActoresSecundarios`) VALUES ('The West Wing','Richard Ramirez');
INSERT INTO `` (`TitIngles`,`ActoresSecundarios`) VALUES ('Orange Is the New Black','Madison Turner');
INSERT INTO `` (`TitIngles`,`ActoresSecundarios`) VALUES ('The Sopranos','David Lee');
INSERT INTO `` (`TitIngles`,`ActoresSecundarios`) VALUES ('24','Richard Ramirez');
INSERT INTO `` (`TitIngles`,`ActoresSecundarios`) VALUES ('The Wire','Christopher Lopez');
INSERT INTO `` (`TitIngles`,`ActoresSecundarios`) VALUES ('Black Sails','Juanita Ortiz');
INSERT INTO `` (`TitIngles`,`ActoresSecundarios`) VALUES ('The Expanse','Willem Dafoe');
INSERT INTO `` (`TitIngles`,`ActoresSecundarios`) VALUES ('Chernobyl','Andrew Adams');
INSERT INTO `` (`TitIngles`,`ActoresSecundarios`) VALUES ('Money Heist','Richard Ramirez');
INSERT INTO `` (`TitIngles`,`ActoresSecundarios`) VALUES ('The Handmaid\'s Tale','Matthew Perez');
INSERT INTO `` (`TitIngles`,`ActoresSecundarios`) VALUES ('Westworld','Emily Johnson');
INSERT INTO `` (`TitIngles`,`ActoresSecundarios`) VALUES ('Peaky Blinders','Aria Phillips');
INSERT INTO `` (`TitIngles`,`ActoresSecundarios`) VALUES ('The Mandalorian','Juanita Ortiz');
INSERT INTO `` (`TitIngles`,`ActoresSecundarios`) VALUES ('The Witcher','Brian Flores');
INSERT INTO `` (`TitIngles`,`ActoresSecundarios`) VALUES ('Ozark','David Lee');
INSERT INTO `` (`TitIngles`,`ActoresSecundarios`) VALUES ('The Crown','Kenneth Torres');
INSERT INTO `` (`TitIngles`,`ActoresSecundarios`) VALUES ('Dark','Olivia Baker');
INSERT INTO `` (`TitIngles`,`ActoresSecundarios`) VALUES ('Stranger Things','Aria Phillips');
INSERT INTO `` (`TitIngles`,`ActoresSecundarios`) VALUES ('Breaking Bad','Christopher Lopez');
INSERT INTO `` (`TitIngles`,`ActoresSecundarios`) VALUES ('Game of Thrones','William Garcia');
INSERT INTO `` (`TitIngles`,`ActoresSecundarios`) VALUES ('Friends','Natalie Ramirez');
INSERT INTO `` (`TitIngles`,`ActoresSecundarios`) VALUES ('The Office','Natalie Ramirez');
INSERT INTO `` (`TitIngles`,`ActoresSecundarios`) VALUES ('Sherlock','Joseph Wright');
INSERT INTO `` (`TitIngles`,`ActoresSecundarios`) VALUES ('Vikings','Derek Foster');
INSERT INTO `` (`TitIngles`,`ActoresSecundarios`) VALUES ('Black Mirror','David Lee');
INSERT INTO `` (`TitIngles`,`ActoresSecundarios`) VALUES ('Narcos','Robert Campbell');
INSERT INTO `` (`TitIngles`,`ActoresSecundarios`) VALUES ('Better Call Saul','Gabriela Flores');
INSERT INTO `` (`TitIngles`,`ActoresSecundarios`) VALUES ('The Big Bang Theory','Chloe Nelson');
INSERT INTO `` (`TitIngles`,`ActoresSecundarios`) VALUES ('True Detective','Gabriela Flores');
INSERT INTO `` (`TitIngles`,`ActoresSecundarios`) VALUES ('Fargo','Victoria Howard');
INSERT INTO `` (`TitIngles`,`ActoresSecundarios`) VALUES ('Lost','Richard Ramirez');
INSERT INTO `` (`TitIngles`,`ActoresSecundarios`) VALUES ('Homeland','Steven Collins');
INSERT INTO `` (`TitIngles`,`ActoresSecundarios`) VALUES ('The Americans','Avery Peterson');
INSERT INTO `` (`TitIngles`,`ActoresSecundarios`) VALUES ('Supernatural','Paula Diaz');
INSERT INTO `` (`TitIngles`,`ActoresSecundarios`) VALUES ('The Walking Dead','Aaliyah Ross');
INSERT INTO `` (`TitIngles`,`ActoresSecundarios`) VALUES ('Grey\'s Anatomy','Olivia Baker');
INSERT INTO `` (`TitIngles`,`ActoresSecundarios`) VALUES ('House of Cards','Ella Cox');
INSERT INTO `` (`TitIngles`,`ActoresSecundarios`) VALUES ('Brooklyn Nine-Nine','Emily Johnson');
INSERT INTO `` (`TitIngles`,`ActoresSecundarios`) VALUES ('The Good Place','Elizabeth Cooper');
INSERT INTO `` (`TitIngles`,`ActoresSecundarios`) VALUES ('The Haunting of Hill House','Elizabeth Cooper');
INSERT INTO `` (`TitIngles`,`ActoresSecundarios`) VALUES ('How to Get Away with Murder','Victoria Howard');
INSERT INTO `` (`TitIngles`,`ActoresSecundarios`) VALUES ('Parks and Recreation','Mia Taylor');
INSERT INTO `` (`TitIngles`,`ActoresSecundarios`) VALUES ('Sons of Anarchy','Isabella Gonzalez');
INSERT INTO `` (`TitIngles`,`ActoresSecundarios`) VALUES ('Mindhunter','Mia Taylor');
INSERT INTO `` (`TitIngles`,`ActoresSecundarios`) VALUES ('Lucifer','Lucas Collins');
INSERT INTO `` (`TitIngles`,`ActoresSecundarios`) VALUES ('The Marvelous Mrs. Maisel','Christopher Lopez');
INSERT INTO `` (`TitIngles`,`ActoresSecundarios`) VALUES ('Cobra Kai','Ella Cox');
INSERT INTO `` (`TitIngles`,`ActoresSecundarios`) VALUES ('The Umbrella Academy','Kenneth Torres');
INSERT INTO `` (`TitIngles`,`ActoresSecundarios`) VALUES ('The Boys','Joseph Wright');
INSERT INTO `` (`TitIngles`,`ActoresSecundarios`) VALUES ('Succession','Lily Foster');
INSERT INTO `` (`TitIngles`,`ActoresSecundarios`) VALUES ('The West Wing','Jessica Brown');
INSERT INTO `` (`TitIngles`,`ActoresSecundarios`) VALUES ('Orange Is the New Black','David Lee');
INSERT INTO `` (`TitIngles`,`ActoresSecundarios`) VALUES ('The Sopranos','George Gray');
INSERT INTO `` (`TitIngles`,`ActoresSecundarios`) VALUES ('24','Mia Taylor');
INSERT INTO `` (`TitIngles`,`ActoresSecundarios`) VALUES ('The Wire','Isabella Gonzalez');
INSERT INTO `` (`TitIngles`,`ActoresSecundarios`) VALUES ('Black Sails','Christopher Lopez');
