/*
-- Query: SELECT * FROM tp_bd_2023.actoresprincipalespelicula
LIMIT 0, 1000

-- Date: 2023-06-01 20:55
*/
INSERT INTO `` (`TitIngles`,`ActoresSecundarios`) VALUES ('Saving Private Ryan','Tom Hanks');
INSERT INTO `` (`TitIngles`,`ActoresSecundarios`) VALUES ('The Princess Bride','Cary Elwes');
INSERT INTO `` (`TitIngles`,`ActoresSecundarios`) VALUES ('The Lion King II: Simba\'s Pride','Matthew Broderick');
INSERT INTO `` (`TitIngles`,`ActoresSecundarios`) VALUES ('Mulan','Ming-Na Wen');
INSERT INTO `` (`TitIngles`,`ActoresSecundarios`) VALUES ('The Social Network','Jesse Eisenberg');
INSERT INTO `` (`TitIngles`,`ActoresSecundarios`) VALUES ('Gone with the Wind','Clark Gable');
INSERT INTO `` (`TitIngles`,`ActoresSecundarios`) VALUES ('The Breakfast Club','Emilio Estevez');
INSERT INTO `` (`TitIngles`,`ActoresSecundarios`) VALUES ('Pulp Fiction','John Travolta');
INSERT INTO `` (`TitIngles`,`ActoresSecundarios`) VALUES ('The Sixth Sense','Bruce Willis');
INSERT INTO `` (`TitIngles`,`ActoresSecundarios`) VALUES ('2001: A Space Odyssey','Keir Dullea');
INSERT INTO `` (`TitIngles`,`ActoresSecundarios`) VALUES ('Titanic','Leonardo DiCaprio');
INSERT INTO `` (`TitIngles`,`ActoresSecundarios`) VALUES ('Star Wars: Episode IV - A New Hope','Mark Hamill');
INSERT INTO `` (`TitIngles`,`ActoresSecundarios`) VALUES ('The Hateful Eight','Samuel L. Jackson');
INSERT INTO `` (`TitIngles`,`ActoresSecundarios`) VALUES ('Star Wars: Episode I - The Phantom Menace','Liam Neeson');
INSERT INTO `` (`TitIngles`,`ActoresSecundarios`) VALUES ('The Lord of the Rings: The Return of the King','Viggo Mortensen');
INSERT INTO `` (`TitIngles`,`ActoresSecundarios`) VALUES ('Star Wars: Episode II - Attack of the Clones','Hayden Christensen');
INSERT INTO `` (`TitIngles`,`ActoresSecundarios`) VALUES ('The Matrix','Keanu Reeves');
INSERT INTO `` (`TitIngles`,`ActoresSecundarios`) VALUES ('The Iron Giant','Vin Diesel (voice)');
INSERT INTO `` (`TitIngles`,`ActoresSecundarios`) VALUES ('Aladdin','Scott Weinger (voice)');
INSERT INTO `` (`TitIngles`,`ActoresSecundarios`) VALUES ('Star Wars: Episode III - Revenge of the Sith','Ewan McGregor');
INSERT INTO `` (`TitIngles`,`ActoresSecundarios`) VALUES ('The Exorcist','Linda Blair');
INSERT INTO `` (`TitIngles`,`ActoresSecundarios`) VALUES ('Goodfellas','Robert De Niro');
INSERT INTO `` (`TitIngles`,`ActoresSecundarios`) VALUES ('Django Unchained','Jamie Foxx');
INSERT INTO `` (`TitIngles`,`ActoresSecundarios`) VALUES ('Nemo','Albert Brooks (voice)');
INSERT INTO `` (`TitIngles`,`ActoresSecundarios`) VALUES ('The Little Mermaid','Jodi Benson (voice)');
INSERT INTO `` (`TitIngles`,`ActoresSecundarios`) VALUES ('The Others','Nicole Kidman');
INSERT INTO `` (`TitIngles`,`ActoresSecundarios`) VALUES ('Signs','Mel Gibson');
INSERT INTO `` (`TitIngles`,`ActoresSecundarios`) VALUES ('The Shawshank Redemption','Tim Robbins');
INSERT INTO `` (`TitIngles`,`ActoresSecundarios`) VALUES ('Toy Story','Tom Hanks (voice)');
INSERT INTO `` (`TitIngles`,`ActoresSecundarios`) VALUES ('The Silence of the Lambs','Jodie Foster');
INSERT INTO `` (`TitIngles`,`ActoresSecundarios`) VALUES ('Fight Club','Brad Pitt');
INSERT INTO `` (`TitIngles`,`ActoresSecundarios`) VALUES ('The Incredibles','Craig T. Nelson (voice)');
INSERT INTO `` (`TitIngles`,`ActoresSecundarios`) VALUES ('The Grand Budapest Hotel','Ralph Fiennes');
INSERT INTO `` (`TitIngles`,`ActoresSecundarios`) VALUES ('Jurassic Park','Sam Neill');
INSERT INTO `` (`TitIngles`,`ActoresSecundarios`) VALUES ('Harry Potter and the Philosopher\'s Stone','Daniel Radcliffe');
INSERT INTO `` (`TitIngles`,`ActoresSecundarios`) VALUES ('The Godfather: Part III','Al Pacino');
INSERT INTO `` (`TitIngles`,`ActoresSecundarios`) VALUES ('The Truman Show','Jim Carrey');
INSERT INTO `` (`TitIngles`,`ActoresSecundarios`) VALUES ('The Godfather: Part II','Judy Garland');
INSERT INTO `` (`TitIngles`,`ActoresSecundarios`) VALUES ('The Wizard of Oz','Amy Poehler (voice)');
INSERT INTO `` (`TitIngles`,`ActoresSecundarios`) VALUES ('Harry Potter and the Chamber of Secrets','Leonardo DiCaprio');
INSERT INTO `` (`TitIngles`,`ActoresSecundarios`) VALUES ('Inside Out','Daniel Radcliffe');
INSERT INTO `` (`TitIngles`,`ActoresSecundarios`) VALUES ('Harry Potter and the Prisoner of Azkaban','Daniel Radcliffe');
INSERT INTO `` (`TitIngles`,`ActoresSecundarios`) VALUES ('The Departed','Daniel Radcliffe');
INSERT INTO `` (`TitIngles`,`ActoresSecundarios`) VALUES ('Harry Potter and the Goblet of Fire','Daniel Radcliffe');
INSERT INTO `` (`TitIngles`,`ActoresSecundarios`) VALUES ('Harry Potter and the Order of the Phoenix','Mark Hamill');
INSERT INTO `` (`TitIngles`,`ActoresSecundarios`) VALUES ('Harry Potter and the Half-Blood Prince','Steven Strait');
INSERT INTO `` (`TitIngles`,`ActoresSecundarios`) VALUES ('Star Wars: Episode VI - Return of the Jedi','Jared Harris');
INSERT INTO `` (`TitIngles`,`ActoresSecundarios`) VALUES ('Saving Private Ryan','Matt Damon');
INSERT INTO `` (`TitIngles`,`ActoresSecundarios`) VALUES ('The Princess Bride','Robin Wright');
INSERT INTO `` (`TitIngles`,`ActoresSecundarios`) VALUES ('The Lion King II: Simba\'s Pride','Neve Campbell (voice)');
INSERT INTO `` (`TitIngles`,`ActoresSecundarios`) VALUES ('Mulan','Eddie Murphy (voice)');
INSERT INTO `` (`TitIngles`,`ActoresSecundarios`) VALUES ('The Social Network','Andrew Garfield');
INSERT INTO `` (`TitIngles`,`ActoresSecundarios`) VALUES ('Gone with the Wind','Vivien Leigh');
INSERT INTO `` (`TitIngles`,`ActoresSecundarios`) VALUES ('The Breakfast Club','Molly Ringwald');
INSERT INTO `` (`TitIngles`,`ActoresSecundarios`) VALUES ('Pulp Fiction','Uma Thurman');
INSERT INTO `` (`TitIngles`,`ActoresSecundarios`) VALUES ('The Sixth Sense','Haley Joel Osment');
INSERT INTO `` (`TitIngles`,`ActoresSecundarios`) VALUES ('2001: A Space Odyssey','Keir Dullea');
INSERT INTO `` (`TitIngles`,`ActoresSecundarios`) VALUES ('Titanic','Kate Winslet');
INSERT INTO `` (`TitIngles`,`ActoresSecundarios`) VALUES ('Star Wars: Episode IV - A New Hope','Carrie Fisher');
INSERT INTO `` (`TitIngles`,`ActoresSecundarios`) VALUES ('The Hateful Eight','Kurt Russell');
INSERT INTO `` (`TitIngles`,`ActoresSecundarios`) VALUES ('Star Wars: Episode I - The Phantom Menace','Natalie Portman');
INSERT INTO `` (`TitIngles`,`ActoresSecundarios`) VALUES ('The Lord of the Rings: The Return of the King','Sean Astin');
INSERT INTO `` (`TitIngles`,`ActoresSecundarios`) VALUES ('Star Wars: Episode II - Attack of the Clones','Natalie Portman');
INSERT INTO `` (`TitIngles`,`ActoresSecundarios`) VALUES ('The Matrix','Laurence Fishburne');
INSERT INTO `` (`TitIngles`,`ActoresSecundarios`) VALUES ('The Iron Giant','Jennifer Aniston (voice)');
INSERT INTO `` (`TitIngles`,`ActoresSecundarios`) VALUES ('Aladdin','Robin Williams (voice)');
INSERT INTO `` (`TitIngles`,`ActoresSecundarios`) VALUES ('Star Wars: Episode III - Revenge of the Sith','Natalie Portman');
INSERT INTO `` (`TitIngles`,`ActoresSecundarios`) VALUES ('The Exorcist','Ellen Burstyn');
INSERT INTO `` (`TitIngles`,`ActoresSecundarios`) VALUES ('Goodfellas','Christoph Waltz');
INSERT INTO `` (`TitIngles`,`ActoresSecundarios`) VALUES ('Django Unchained','Ellen DeGeneres (voice)');
INSERT INTO `` (`TitIngles`,`ActoresSecundarios`) VALUES ('Nemo','Pat Carroll (voice)');
INSERT INTO `` (`TitIngles`,`ActoresSecundarios`) VALUES ('The Little Mermaid','Joaquin Phoenix');
INSERT INTO `` (`TitIngles`,`ActoresSecundarios`) VALUES ('The Others','Morgan Freeman');
INSERT INTO `` (`TitIngles`,`ActoresSecundarios`) VALUES ('Signs','Tim Allen (voice)');
INSERT INTO `` (`TitIngles`,`ActoresSecundarios`) VALUES ('The Shawshank Redemption','Anthony Hopkins');
INSERT INTO `` (`TitIngles`,`ActoresSecundarios`) VALUES ('Toy Story','Harrison Ford');
INSERT INTO `` (`TitIngles`,`ActoresSecundarios`) VALUES ('The Silence of the Lambs','Edward Norton');
INSERT INTO `` (`TitIngles`,`ActoresSecundarios`) VALUES ('Fight Club','Ralph Fiennes');
INSERT INTO `` (`TitIngles`,`ActoresSecundarios`) VALUES ('The Incredibles','Sam Neill');
INSERT INTO `` (`TitIngles`,`ActoresSecundarios`) VALUES ('The Grand Budapest Hotel','Rupert Grint');
INSERT INTO `` (`TitIngles`,`ActoresSecundarios`) VALUES ('Jurassic Park','Al Pacino');
INSERT INTO `` (`TitIngles`,`ActoresSecundarios`) VALUES ('Harry Potter and the Philosopher\'s Stone','Jim Carrey');
INSERT INTO `` (`TitIngles`,`ActoresSecundarios`) VALUES ('The Godfather: Part III','Al Pacino');
INSERT INTO `` (`TitIngles`,`ActoresSecundarios`) VALUES ('The Truman Show','Judy Garland');
INSERT INTO `` (`TitIngles`,`ActoresSecundarios`) VALUES ('The Godfather: Part II','Emma Watson');
INSERT INTO `` (`TitIngles`,`ActoresSecundarios`) VALUES ('The Wizard of Oz','Phyllis Smith (voice)');
INSERT INTO `` (`TitIngles`,`ActoresSecundarios`) VALUES ('Harry Potter and the Chamber of Secrets','Rupert Grint');
INSERT INTO `` (`TitIngles`,`ActoresSecundarios`) VALUES ('Inside Out','Leonardo DiCaprio');
INSERT INTO `` (`TitIngles`,`ActoresSecundarios`) VALUES ('Harry Potter and the Prisoner of Azkaban','Daniel Radcliffe');
INSERT INTO `` (`TitIngles`,`ActoresSecundarios`) VALUES ('The Departed','Emma Watson');
INSERT INTO `` (`TitIngles`,`ActoresSecundarios`) VALUES ('Harry Potter and the Goblet of Fire','Rupert Grint');
INSERT INTO `` (`TitIngles`,`ActoresSecundarios`) VALUES ('Harry Potter and the Order of the Phoenix','Carrie Fisher');
INSERT INTO `` (`TitIngles`,`ActoresSecundarios`) VALUES ('Harry Potter and the Half-Blood Prince','Thomas Jane');
INSERT INTO `` (`TitIngles`,`ActoresSecundarios`) VALUES ('Star Wars: Episode VI - Return of the Jedi','Jared Harris');
