/*
-- Query: SELECT * FROM tp_bd_2023.actoresprincipalesserie
LIMIT 0, 1000

-- Date: 2023-06-01 20:55
*/
INSERT INTO `` (`TitIngles`,`ActoresPrincipales`) VALUES ('The Expanse','Ursula Corbero');
INSERT INTO `` (`TitIngles`,`ActoresPrincipales`) VALUES ('Chernobyl','Elisabeth Moss');
INSERT INTO `` (`TitIngles`,`ActoresPrincipales`) VALUES ('Money Heist','Evan Rachel Wood');
INSERT INTO `` (`TitIngles`,`ActoresPrincipales`) VALUES ('The Handmaid\'s Tale','Cillian Murphy');
INSERT INTO `` (`TitIngles`,`ActoresPrincipales`) VALUES ('Westworld','Pedro Pascal');
INSERT INTO `` (`TitIngles`,`ActoresPrincipales`) VALUES ('Peaky Blinders','Henry Cavill');
INSERT INTO `` (`TitIngles`,`ActoresPrincipales`) VALUES ('The Mandalorian','Jason Bateman');
INSERT INTO `` (`TitIngles`,`ActoresPrincipales`) VALUES ('The Witcher','Claire Foy');
INSERT INTO `` (`TitIngles`,`ActoresPrincipales`) VALUES ('Ozark','Louis Hofmann');
INSERT INTO `` (`TitIngles`,`ActoresPrincipales`) VALUES ('The Crown','Millie Bobby Brown');
INSERT INTO `` (`TitIngles`,`ActoresPrincipales`) VALUES ('Dark','Bryan Cranston');
INSERT INTO `` (`TitIngles`,`ActoresPrincipales`) VALUES ('Stranger Things','Jennifer Aniston');
INSERT INTO `` (`TitIngles`,`ActoresPrincipales`) VALUES ('Breaking Bad','Steve Carell');
INSERT INTO `` (`TitIngles`,`ActoresPrincipales`) VALUES ('Game of Thrones','Benedict Cumberbatch');
INSERT INTO `` (`TitIngles`,`ActoresPrincipales`) VALUES ('Friends','Travis Fimmel');
INSERT INTO `` (`TitIngles`,`ActoresPrincipales`) VALUES ('The Office','Various actors (anthology series)');
INSERT INTO `` (`TitIngles`,`ActoresPrincipales`) VALUES ('Sherlock','Wagner Moura');
INSERT INTO `` (`TitIngles`,`ActoresPrincipales`) VALUES ('Vikings','Bob Odenkirk');
INSERT INTO `` (`TitIngles`,`ActoresPrincipales`) VALUES ('Black Mirror','Johnny');
INSERT INTO `` (`TitIngles`,`ActoresPrincipales`) VALUES ('Narcos','Michelle Rodriguez');
INSERT INTO `` (`TitIngles`,`ActoresPrincipales`) VALUES ('Better Call Saul','Emma Watson');
INSERT INTO `` (`TitIngles`,`ActoresPrincipales`) VALUES ('The Big Bang Theory','Amy Adams');
INSERT INTO `` (`TitIngles`,`ActoresPrincipales`) VALUES ('True Detective','Johnny Depp');
INSERT INTO `` (`TitIngles`,`ActoresPrincipales`) VALUES ('Fargo','Hugh Jackman');
INSERT INTO `` (`TitIngles`,`ActoresPrincipales`) VALUES ('Lost','Jason Momoa');
INSERT INTO `` (`TitIngles`,`ActoresPrincipales`) VALUES ('Homeland','Scarlett Johansson');
INSERT INTO `` (`TitIngles`,`ActoresPrincipales`) VALUES ('The Americans','Julia Roberts');
INSERT INTO `` (`TitIngles`,`ActoresPrincipales`) VALUES ('Supernatural','Emma Watson');
INSERT INTO `` (`TitIngles`,`ActoresPrincipales`) VALUES ('The Walking Dead','Ryan Gosling');
INSERT INTO `` (`TitIngles`,`ActoresPrincipales`) VALUES ('Grey\'s Anatomy','Scarlett Johansson');
INSERT INTO `` (`TitIngles`,`ActoresPrincipales`) VALUES ('House of Cards','Brie Larson');
INSERT INTO `` (`TitIngles`,`ActoresPrincipales`) VALUES ('Brooklyn Nine-Nine','Margot Robbie');
INSERT INTO `` (`TitIngles`,`ActoresPrincipales`) VALUES ('The Good Place','Emma Stone');
INSERT INTO `` (`TitIngles`,`ActoresPrincipales`) VALUES ('The Haunting of Hill House','Angelina Jolie');
INSERT INTO `` (`TitIngles`,`ActoresPrincipales`) VALUES ('How to Get Away with Murder','Idris Elba');
INSERT INTO `` (`TitIngles`,`ActoresPrincipales`) VALUES ('Parks and Recreation','Johnny Depp');
INSERT INTO `` (`TitIngles`,`ActoresPrincipales`) VALUES ('Sons of Anarchy','Joaquin Phoenix');
INSERT INTO `` (`TitIngles`,`ActoresPrincipales`) VALUES ('Mindhunter','Emma Watson');
INSERT INTO `` (`TitIngles`,`ActoresPrincipales`) VALUES ('Lucifer','Gal Gadot');
INSERT INTO `` (`TitIngles`,`ActoresPrincipales`) VALUES ('The Marvelous Mrs. Maisel','Chris Pratt');
INSERT INTO `` (`TitIngles`,`ActoresPrincipales`) VALUES ('Cobra Kai','Tom Hanks');
INSERT INTO `` (`TitIngles`,`ActoresPrincipales`) VALUES ('The Umbrella Academy','Kristen Bell');
INSERT INTO `` (`TitIngles`,`ActoresPrincipales`) VALUES ('The Boys','Kristen Bell');
INSERT INTO `` (`TitIngles`,`ActoresPrincipales`) VALUES ('Succession','Chris Hemsworth');
INSERT INTO `` (`TitIngles`,`ActoresPrincipales`) VALUES ('The West Wing','Leonardo DiCaprio');
INSERT INTO `` (`TitIngles`,`ActoresPrincipales`) VALUES ('Orange Is the New Black','Jessica Chastain');
INSERT INTO `` (`TitIngles`,`ActoresPrincipales`) VALUES ('The Sopranos','Michael Fassbender');
INSERT INTO `` (`TitIngles`,`ActoresPrincipales`) VALUES ('24','Jessica Chastain');
INSERT INTO `` (`TitIngles`,`ActoresPrincipales`) VALUES ('The Wire','Matt Damon');
INSERT INTO `` (`TitIngles`,`ActoresPrincipales`) VALUES ('Black Sails','Brie Larson');
INSERT INTO `` (`TitIngles`,`ActoresPrincipales`) VALUES ('The Expanse','Alvaro Morte');
INSERT INTO `` (`TitIngles`,`ActoresPrincipales`) VALUES ('Chernobyl','Joseph Fiennes');
INSERT INTO `` (`TitIngles`,`ActoresPrincipales`) VALUES ('Money Heist','Evan Rachel Wood');
INSERT INTO `` (`TitIngles`,`ActoresPrincipales`) VALUES ('The Handmaid\'s Tale','Cillian Murphy');
INSERT INTO `` (`TitIngles`,`ActoresPrincipales`) VALUES ('Westworld','Pedro Pascal');
INSERT INTO `` (`TitIngles`,`ActoresPrincipales`) VALUES ('Peaky Blinders','Henry Cavill');
INSERT INTO `` (`TitIngles`,`ActoresPrincipales`) VALUES ('The Mandalorian','Jason Bateman');
INSERT INTO `` (`TitIngles`,`ActoresPrincipales`) VALUES ('The Witcher','Olivia Colman');
INSERT INTO `` (`TitIngles`,`ActoresPrincipales`) VALUES ('Ozark','Louis Hofmann');
INSERT INTO `` (`TitIngles`,`ActoresPrincipales`) VALUES ('The Crown','Finn Wolfhard');
INSERT INTO `` (`TitIngles`,`ActoresPrincipales`) VALUES ('Dark','Aaron Paul');
INSERT INTO `` (`TitIngles`,`ActoresPrincipales`) VALUES ('Stranger Things','Courteney Cox');
INSERT INTO `` (`TitIngles`,`ActoresPrincipales`) VALUES ('Breaking Bad','Rainn Wilson');
INSERT INTO `` (`TitIngles`,`ActoresPrincipales`) VALUES ('Game of Thrones','Martin Freeman');
INSERT INTO `` (`TitIngles`,`ActoresPrincipales`) VALUES ('Friends','Alexander Ludwig');
INSERT INTO `` (`TitIngles`,`ActoresPrincipales`) VALUES ('The Office','Various actors (anthology series)');
INSERT INTO `` (`TitIngles`,`ActoresPrincipales`) VALUES ('Sherlock','Wagner Moura');
INSERT INTO `` (`TitIngles`,`ActoresPrincipales`) VALUES ('Vikings','Bob Odenkirk');
INSERT INTO `` (`TitIngles`,`ActoresPrincipales`) VALUES ('Black Mirror','Jim Parsons');
INSERT INTO `` (`TitIngles`,`ActoresPrincipales`) VALUES ('Narcos','Matthew McConaughey');
INSERT INTO `` (`TitIngles`,`ActoresPrincipales`) VALUES ('Better Call Saul','David Harbour');
INSERT INTO `` (`TitIngles`,`ActoresPrincipales`) VALUES ('The Big Bang Theory','Kevin Spacey');
INSERT INTO `` (`TitIngles`,`ActoresPrincipales`) VALUES ('True Detective','Andy Samberg');
INSERT INTO `` (`TitIngles`,`ActoresPrincipales`) VALUES ('Fargo','Kristen Bell');
INSERT INTO `` (`TitIngles`,`ActoresPrincipales`) VALUES ('Lost','Victoria Pedretti');
INSERT INTO `` (`TitIngles`,`ActoresPrincipales`) VALUES ('Homeland','Viola Davis');
INSERT INTO `` (`TitIngles`,`ActoresPrincipales`) VALUES ('The Americans','Amy Poehler');
INSERT INTO `` (`TitIngles`,`ActoresPrincipales`) VALUES ('Supernatural','Chris Pratt');
INSERT INTO `` (`TitIngles`,`ActoresPrincipales`) VALUES ('The Walking Dead','Charlie Cox');
INSERT INTO `` (`TitIngles`,`ActoresPrincipales`) VALUES ('Grey\'s Anatomy','Tom Ellis');
INSERT INTO `` (`TitIngles`,`ActoresPrincipales`) VALUES ('House of Cards','Rachel Brosnahan');
INSERT INTO `` (`TitIngles`,`ActoresPrincipales`) VALUES ('Brooklyn Nine-Nine','Ralph Macchio');
INSERT INTO `` (`TitIngles`,`ActoresPrincipales`) VALUES ('The Good Place','Tom Hopper');
INSERT INTO `` (`TitIngles`,`ActoresPrincipales`) VALUES ('The Haunting of Hill House','Karl Urban');
INSERT INTO `` (`TitIngles`,`ActoresPrincipales`) VALUES ('How to Get Away with Murder','Jeremy Strong');
INSERT INTO `` (`TitIngles`,`ActoresPrincipales`) VALUES ('Parks and Recreation','Martin Sheen');
INSERT INTO `` (`TitIngles`,`ActoresPrincipales`) VALUES ('Sons of Anarchy','Taylor Schilling');
INSERT INTO `` (`TitIngles`,`ActoresPrincipales`) VALUES ('Mindhunter','James Gandolfini');
INSERT INTO `` (`TitIngles`,`ActoresPrincipales`) VALUES ('Lucifer','Kiefer Sutherland');
INSERT INTO `` (`TitIngles`,`ActoresPrincipales`) VALUES ('The Marvelous Mrs. Maisel','Dominic West');
INSERT INTO `` (`TitIngles`,`ActoresPrincipales`) VALUES ('Cobra Kai','Toby Stephens');
INSERT INTO `` (`TitIngles`,`ActoresPrincipales`) VALUES ('The Umbrella Academy','Idris Elba');
INSERT INTO `` (`TitIngles`,`ActoresPrincipales`) VALUES ('The Boys','Jared Padalecki');
INSERT INTO `` (`TitIngles`,`ActoresPrincipales`) VALUES ('Succession','Ellen Pompeo');
INSERT INTO `` (`TitIngles`,`ActoresPrincipales`) VALUES ('The West Wing','Kevin Spacey');
INSERT INTO `` (`TitIngles`,`ActoresPrincipales`) VALUES ('Orange Is the New Black','Andy Samberg');
INSERT INTO `` (`TitIngles`,`ActoresPrincipales`) VALUES ('The Sopranos','Kristen Bell');
INSERT INTO `` (`TitIngles`,`ActoresPrincipales`) VALUES ('24','Hugh Laurie');
INSERT INTO `` (`TitIngles`,`ActoresPrincipales`) VALUES ('The Wire','Michael C. Hall');
INSERT INTO `` (`TitIngles`,`ActoresPrincipales`) VALUES ('Black Sails','Bryan Cranston');
