/*
-- Query: SELECT * FROM tp_bd_2023.serie
LIMIT 0, 1000

-- Date: 2023-06-01 21:06
*/
INSERT INTO `` (`TitIngles`,`TitEspanol`,`Calificacion`,`Productor`,`Genero`,`Resumen`) VALUES ('24','24','Me gusto bastante','Joel Surnow, Robert Cochran','Action, Drama, Thriller','Agentes gubernamentales luchan contra amenazas terroristas en tiempo real.');
INSERT INTO `` (`TitIngles`,`TitEspanol`,`Calificacion`,`Productor`,`Genero`,`Resumen`) VALUES ('Better Call Saul','Better Call Saul','No me decido','Vince Gilligan, Peter Gould','Sitcom','Precuela de Breaking Bad que narra la historia de Saul Goodman.');
INSERT INTO `` (`TitIngles`,`TitEspanol`,`Calificacion`,`Productor`,`Genero`,`Resumen`) VALUES ('Black Mirror','Black Mirror','Me encanto','Charlie Brooker','Sci-Fi, Anthology','Reflexiones oscuras sobre la tecnologia y la sociedad moderna.');
INSERT INTO `` (`TitIngles`,`TitEspanol`,`Calificacion`,`Productor`,`Genero`,`Resumen`) VALUES ('Black Sails','Black Sails','Me encanto','Jonathan E. Steinberg, Robert Levine','Adventure, Drama','Aventuras piratas en el Caribe del siglo XVIII.');
INSERT INTO `` (`TitIngles`,`TitEspanol`,`Calificacion`,`Productor`,`Genero`,`Resumen`) VALUES ('Breaking Bad','Breaking Bad','No me gusto','Vince Gilligan','Crime, Drama, Thriller','Un profesor de quimica se convierte en fabricante de metanfetaminas.');
INSERT INTO `` (`TitIngles`,`TitEspanol`,`Calificacion`,`Productor`,`Genero`,`Resumen`) VALUES ('Brooklyn Nine-Nine','Brooklyn Nine-Nine','Me gusto bastante','Dan Goor, Michael Schur','Comedy, Police Procedural','Una comisarÃ­a de policÃ­a llena de personajes excentricos.');
INSERT INTO `` (`TitIngles`,`TitEspanol`,`Calificacion`,`Productor`,`Genero`,`Resumen`) VALUES ('Chernobyl','Chernobyl','Me encanto','Craig Mazin','Historical Drama','Basada en el desastre nuclear de Chernobyl y sus consecuencias.');
INSERT INTO `` (`TitIngles`,`TitEspanol`,`Calificacion`,`Productor`,`Genero`,`Resumen`) VALUES ('Cobra Kai','Cobra Kai','Me encanto','Jon Hurwitz, Hayden Schlossberg, Josh Heald','Action, Comedy, Drama','Tres jovenes intentan revitalizar el karate y lidiar con su pasado.');
INSERT INTO `` (`TitIngles`,`TitEspanol`,`Calificacion`,`Productor`,`Genero`,`Resumen`) VALUES ('Dark','Dark','Me gusto bastante','Baran bo Odar','Science Fiction, Thriller','Misteriosas desapariciones y eventos sobrenaturales en una pequena ciudad alemana.');
INSERT INTO `` (`TitIngles`,`TitEspanol`,`Calificacion`,`Productor`,`Genero`,`Resumen`) VALUES ('Fargo','Fargo','Me encanto','Noah Hawley','Crime, Drama, Thriller','Intriga y violencia en una ciudad envuelta en crimen organizado.');
INSERT INTO `` (`TitIngles`,`TitEspanol`,`Calificacion`,`Productor`,`Genero`,`Resumen`) VALUES ('Friends','Friends','Me encanto','David Crane, Marta Kauffman','Sitcom','Las vidas y amistades de un grupo de amigos en Nueva York.');
INSERT INTO `` (`TitIngles`,`TitEspanol`,`Calificacion`,`Productor`,`Genero`,`Resumen`) VALUES ('Game of Thrones','Game of Thrones','Me gusto un poco','David Benioff, D.B. Weiss','Fantasy, Drama','Intrigas, batallas y alianzas en la lucha por el Trono de Hierro.');
INSERT INTO `` (`TitIngles`,`TitEspanol`,`Calificacion`,`Productor`,`Genero`,`Resumen`) VALUES ('Grey\'s Anatomy','Anatomia segun Grey','Me encanto','Shonda Rhimes','Medical Drama, Romance','Drama medico que sigue la vida de cirujanos internos en un hospital.');
INSERT INTO `` (`TitIngles`,`TitEspanol`,`Calificacion`,`Productor`,`Genero`,`Resumen`) VALUES ('Homeland','Homeland','No me decido','Alex Gansa, Howard Gordon','Drama, Thriller','Espionaje y amenazas terroristas en Estados Unidos.');
INSERT INTO `` (`TitIngles`,`TitEspanol`,`Calificacion`,`Productor`,`Genero`,`Resumen`) VALUES ('House of Cards','House of Cards','No me gusto','Beau Willimon','Political Drama','Intrigas politicas y manipulaciones en el mundo de la politica estadounidense.');
INSERT INTO `` (`TitIngles`,`TitEspanol`,`Calificacion`,`Productor`,`Genero`,`Resumen`) VALUES ('How to Get Away with Murder','Como defender a un asesino','Me gusto bastante','Peter Nowalk','Legal Drama, Mystery','Un grupo de estudiantes de derecho se involucra en un asesinato.');
INSERT INTO `` (`TitIngles`,`TitEspanol`,`Calificacion`,`Productor`,`Genero`,`Resumen`) VALUES ('Lost','Lost','No me gusto','J.J. Abrams, Damon Lindelof','Adventure, Drama, Mystery','Supervivencia en una isla misteriosa llena de peligros.');
INSERT INTO `` (`TitIngles`,`TitEspanol`,`Calificacion`,`Productor`,`Genero`,`Resumen`) VALUES ('Lucifer','Lucifer','Me encanto','Tom Kapinos','Fantasy, Drama','Un escritor se involucra con el Diablo en Los Angeles.');
INSERT INTO `` (`TitIngles`,`TitEspanol`,`Calificacion`,`Productor`,`Genero`,`Resumen`) VALUES ('Mindhunter','Mindhunter','Me gusto un poco','David Fincher, Joe Penhall','Crime, Drama, Thriller','Agentes del FBI entrevistan a asesinos en serie encarcelados.');
INSERT INTO `` (`TitIngles`,`TitEspanol`,`Calificacion`,`Productor`,`Genero`,`Resumen`) VALUES ('Money Heist','La Casa de Papel','Me gusto un poco','Alex Pina','Heist, Crime','Planificacion y ejecucion de un gran robo a la Fabrica Nacional de Moneda y Timbre de Espana.');
INSERT INTO `` (`TitIngles`,`TitEspanol`,`Calificacion`,`Productor`,`Genero`,`Resumen`) VALUES ('Narcos','Narcos','Me gusto bastante','Chris Brancato, Carlo Bernard, Doug Miro','Crime, Drama','La vida del narcotraficante Pablo Escobar y el mundo del trafico de drogas.');
INSERT INTO `` (`TitIngles`,`TitEspanol`,`Calificacion`,`Productor`,`Genero`,`Resumen`) VALUES ('Orange Is the New Black','Orange Is the New Black','Me encanto','Jenji Kohan','Comedy-drama, Crime','Una exconvicta se involucra en el mundo del narcotrafico.');
INSERT INTO `` (`TitIngles`,`TitEspanol`,`Calificacion`,`Productor`,`Genero`,`Resumen`) VALUES ('Ozark','Ozark','No me gusto','Bill Dubuque','Crime, Drama','Lavar dinero para un cartel de drogas mientras se mantiene a salvo la familia.');
INSERT INTO `` (`TitIngles`,`TitEspanol`,`Calificacion`,`Productor`,`Genero`,`Resumen`) VALUES ('Parks and Recreation','Parks and Recreation','No me decido','Greg Daniels, Michael Schur','Mockumentary, Sitcom','Las divertidas situaciones de un departamento de parques y recreacion.');
INSERT INTO `` (`TitIngles`,`TitEspanol`,`Calificacion`,`Productor`,`Genero`,`Resumen`) VALUES ('Peaky Blinders','Peaky Blinders','Me gusto bastante','Steven Knight','Crime, Drama','Familia de gansters en la decada de 1920 en Birmingham, Inglaterra.');
INSERT INTO `` (`TitIngles`,`TitEspanol`,`Calificacion`,`Productor`,`Genero`,`Resumen`) VALUES ('Sherlock','Sherlock','No me gusto','Mark Gatiss, Steven Moffat','Crime, Mystery','Adaptacion moderna de las historias clasicas de Sherlock Holmes.');
INSERT INTO `` (`TitIngles`,`TitEspanol`,`Calificacion`,`Productor`,`Genero`,`Resumen`) VALUES ('Sons of Anarchy','Hijos de la Anarquia','No me gusto','Kurt Sutter','Crime, Drama, Thriller','Un club de motociclistas ilegales y sus actividades criminales.');
INSERT INTO `` (`TitIngles`,`TitEspanol`,`Calificacion`,`Productor`,`Genero`,`Resumen`) VALUES ('Stranger Things','Stranger Things','Me encanto','The Duffer Brothers','Science Fiction, Horror, Drama','Aventuras sobrenaturales de un grupo de amigos en la decada de 1980.');
INSERT INTO `` (`TitIngles`,`TitEspanol`,`Calificacion`,`Productor`,`Genero`,`Resumen`) VALUES ('Succession','Succession','No me gusto','Jesse Armstrong','Drama','Drama familiar sobre una poderosa familia de medios de comunicacion.');
INSERT INTO `` (`TitIngles`,`TitEspanol`,`Calificacion`,`Productor`,`Genero`,`Resumen`) VALUES ('Supernatural','Sobrenatural','Me encanto','Eric Kripke','Supernatural, Drama, Mystery','Cazadores de lo sobrenatural mientras enfrentan sus propios demonios.');
INSERT INTO `` (`TitIngles`,`TitEspanol`,`Calificacion`,`Productor`,`Genero`,`Resumen`) VALUES ('The Americans','Los Americanos','Me gusto bastante','Joe Weisberg','Drama, Thriller','Una pareja de espias sovieticos que vive como ciudadanos estadounidenses.');
INSERT INTO `` (`TitIngles`,`TitEspanol`,`Calificacion`,`Productor`,`Genero`,`Resumen`) VALUES ('The Big Bang Theory','The Big Bang Theory','Me gusto un poco','Chuck Lorre, Bill Prady','Sitcom','Las peripecias de un grupo de cientificos y su vecino geek.');
INSERT INTO `` (`TitIngles`,`TitEspanol`,`Calificacion`,`Productor`,`Genero`,`Resumen`) VALUES ('The Boys','The Boys','Me gusto bastante','Eric Kripke','Crime, Action, Drama','Un grupo de vigilantes lucha contra superheroes corruptos.');
INSERT INTO `` (`TitIngles`,`TitEspanol`,`Calificacion`,`Productor`,`Genero`,`Resumen`) VALUES ('The Crown','The Crown','No me decido','Peter Morgan','Historical Drama','Drama sobre la reina Isabel II y su reinado en el Reino Unido.');
INSERT INTO `` (`TitIngles`,`TitEspanol`,`Calificacion`,`Productor`,`Genero`,`Resumen`) VALUES ('The Expanse','The Expanse','No me gusto','Mark Fergus','Science Fiction','Serie de ciencia ficcion ambientada en un sistema solar colonizado.');
INSERT INTO `` (`TitIngles`,`TitEspanol`,`Calificacion`,`Productor`,`Genero`,`Resumen`) VALUES ('The Good Place','The Good Place','Me encanto','Michael Schur','Fantasy, Comedy','Un grupo de personas intenta encontrar la redencion en el Mas Alla.');
INSERT INTO `` (`TitIngles`,`TitEspanol`,`Calificacion`,`Productor`,`Genero`,`Resumen`) VALUES ('The Handmaid\'s Tale','El Cuento de la Criada','No me decido','Bruce Miller','Dystopian, Drama','Distopia donde mujeres son esclavizadas para fines reproductivos.');
INSERT INTO `` (`TitIngles`,`TitEspanol`,`Calificacion`,`Productor`,`Genero`,`Resumen`) VALUES ('The Haunting of Hill House','La Maldicion de Hill House','Me gusto un poco','Mike Flanagan','Supernatural, Horror, Drama','Una familia enfrenta su pasado en una casa encantada.');
INSERT INTO `` (`TitIngles`,`TitEspanol`,`Calificacion`,`Productor`,`Genero`,`Resumen`) VALUES ('The Mandalorian','The Mandalorian','No me gusto','Jon Favreau','Science Fiction, Adventure','Aventuras en el universo de Star Wars tras la caida del Imperio.');
INSERT INTO `` (`TitIngles`,`TitEspanol`,`Calificacion`,`Productor`,`Genero`,`Resumen`) VALUES ('The Marvelous Mrs. Maisel','La Maravillosa Senora Maisel','No me decido','Amy Sherman-Palladino','Comedy-drama','Las vidas de una madre y su hija en un pequeÃ±o pueblo de Connecticut.');
INSERT INTO `` (`TitIngles`,`TitEspanol`,`Calificacion`,`Productor`,`Genero`,`Resumen`) VALUES ('The Office','The Office','Me gusto bastante','Greg Daniels','Mockumentary, Sitcom','Locuras y relaciones en una oficina de ventas de papel.');
INSERT INTO `` (`TitIngles`,`TitEspanol`,`Calificacion`,`Productor`,`Genero`,`Resumen`) VALUES ('The Sopranos','Los Soprano','No me decido','David Chase','Crime, Drama','Un mafioso de Nueva Jersey equilibra su vida familiar y su carrera criminal.');
INSERT INTO `` (`TitIngles`,`TitEspanol`,`Calificacion`,`Productor`,`Genero`,`Resumen`) VALUES ('The Umbrella Academy','The Umbrella Academy','No me gusto','Steve Blackman','Action, Fantasy, Drama','Siete hermanos adoptivos con poderes unicos deben salvar el mundo.');
INSERT INTO `` (`TitIngles`,`TitEspanol`,`Calificacion`,`Productor`,`Genero`,`Resumen`) VALUES ('The Walking Dead','The Walking Dead','Me gusto un poco','Frank Darabont, Angela Kang','Horror, Drama','Un grupo de supervivientes lucha contra zombis y amenazas humanas.');
INSERT INTO `` (`TitIngles`,`TitEspanol`,`Calificacion`,`Productor`,`Genero`,`Resumen`) VALUES ('The West Wing','El Ala Oeste de la Casa Blanca','Me gusto un poco','Aaron Sorkin','Political Drama','Intrigas politicas en la Casa Blanca y el gobierno estadounidense.');
INSERT INTO `` (`TitIngles`,`TitEspanol`,`Calificacion`,`Productor`,`Genero`,`Resumen`) VALUES ('The Wire','The Wire','No me gusto','David Simon','Crime, Drama, Thriller','Crimen y corrupcion en las calles de Baltimore.');
INSERT INTO `` (`TitIngles`,`TitEspanol`,`Calificacion`,`Productor`,`Genero`,`Resumen`) VALUES ('The Witcher','The Witcher','Me gusto un poco','Lauren Schmidt Hissrich','Fantasy, Adventure','Adaptacion de las novelas de fantasÃ­a de Geralt de Rivia.');
INSERT INTO `` (`TitIngles`,`TitEspanol`,`Calificacion`,`Productor`,`Genero`,`Resumen`) VALUES ('True Detective','True Detective','No me gusto','Nic Pizzolatto','Crime, Drama, Mystery','Investigaciones de casos criminales con narrativa no lineal.');
INSERT INTO `` (`TitIngles`,`TitEspanol`,`Calificacion`,`Productor`,`Genero`,`Resumen`) VALUES ('Vikings','Vikingos','Me gusto un poco','Michael Hirst','Historical Drama','Vikingos y sus incursiones en Europa occidental.');
INSERT INTO `` (`TitIngles`,`TitEspanol`,`Calificacion`,`Productor`,`Genero`,`Resumen`) VALUES ('Westworld','Westworld','Me encanto','Jonathan Nolan','Science Fiction, Western','Parque tematico futurista habitado por androides.');
