/*
-- Query: SELECT * FROM tp_bd_2023.contiene
LIMIT 0, 1000

-- Date: 2023-06-01 21:01
*/
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (100829,'24');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (110169,'24');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (112904,'24');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (113178,'24');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (121980,'24');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (123269,'24');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (124693,'24');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (130220,'24');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (137091,'24');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (138698,'24');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (139396,'24');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (144005,'24');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (161646,'24');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (165611,'24');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (172612,'24');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (177216,'24');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (178065,'24');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (189188,'24');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (189685,'24');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (199051,'24');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (101886,'Better Call Saul');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (105039,'Better Call Saul');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (107066,'Better Call Saul');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (110773,'Better Call Saul');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (111673,'Better Call Saul');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (113041,'Better Call Saul');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (117753,'Better Call Saul');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (134355,'Better Call Saul');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (134406,'Better Call Saul');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (149275,'Better Call Saul');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (154853,'Better Call Saul');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (159228,'Better Call Saul');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (162135,'Better Call Saul');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (169020,'Better Call Saul');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (178994,'Better Call Saul');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (181799,'Better Call Saul');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (186347,'Better Call Saul');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (188842,'Better Call Saul');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (194237,'Better Call Saul');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (195237,'Better Call Saul');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (106159,'Black Mirror');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (109358,'Black Mirror');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (113338,'Black Mirror');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (121701,'Black Mirror');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (123236,'Black Mirror');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (128910,'Black Mirror');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (132956,'Black Mirror');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (134507,'Black Mirror');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (134550,'Black Mirror');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (136685,'Black Mirror');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (141642,'Black Mirror');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (145248,'Black Mirror');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (150098,'Black Mirror');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (168960,'Black Mirror');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (174687,'Black Mirror');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (186322,'Black Mirror');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (188674,'Black Mirror');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (190517,'Black Mirror');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (193078,'Black Mirror');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (193498,'Black Mirror');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (102208,'Black Sails');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (110421,'Black Sails');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (114189,'Black Sails');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (124975,'Black Sails');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (135832,'Black Sails');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (135860,'Black Sails');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (140942,'Black Sails');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (145909,'Black Sails');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (146214,'Black Sails');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (148021,'Black Sails');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (148619,'Black Sails');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (155777,'Black Sails');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (162112,'Black Sails');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (168951,'Black Sails');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (175447,'Black Sails');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (179252,'Black Sails');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (180101,'Black Sails');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (183767,'Black Sails');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (191690,'Black Sails');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (109264,'Breaking Bad');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (119931,'Breaking Bad');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (121585,'Breaking Bad');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (126556,'Breaking Bad');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (135467,'Breaking Bad');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (138647,'Breaking Bad');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (151276,'Breaking Bad');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (153565,'Breaking Bad');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (154901,'Breaking Bad');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (168790,'Breaking Bad');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (169038,'Breaking Bad');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (171093,'Breaking Bad');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (174948,'Breaking Bad');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (178605,'Breaking Bad');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (178886,'Breaking Bad');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (180961,'Breaking Bad');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (189590,'Breaking Bad');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (193104,'Breaking Bad');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (193367,'Breaking Bad');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (193391,'Breaking Bad');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (107256,'Brooklyn Nine-Nine');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (112690,'Brooklyn Nine-Nine');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (112929,'Brooklyn Nine-Nine');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (117166,'Brooklyn Nine-Nine');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (121005,'Brooklyn Nine-Nine');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (121823,'Brooklyn Nine-Nine');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (129507,'Brooklyn Nine-Nine');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (132650,'Brooklyn Nine-Nine');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (138018,'Brooklyn Nine-Nine');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (140343,'Brooklyn Nine-Nine');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (144577,'Brooklyn Nine-Nine');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (149397,'Brooklyn Nine-Nine');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (154445,'Brooklyn Nine-Nine');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (157444,'Brooklyn Nine-Nine');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (170170,'Brooklyn Nine-Nine');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (180806,'Brooklyn Nine-Nine');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (184197,'Brooklyn Nine-Nine');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (185505,'Brooklyn Nine-Nine');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (186942,'Brooklyn Nine-Nine');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (193485,'Brooklyn Nine-Nine');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (108987,'Chernobyl');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (111767,'Chernobyl');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (112787,'Chernobyl');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (121967,'Chernobyl');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (126892,'Chernobyl');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (133556,'Chernobyl');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (146263,'Chernobyl');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (153050,'Chernobyl');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (153946,'Chernobyl');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (156105,'Chernobyl');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (163078,'Chernobyl');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (165587,'Chernobyl');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (169925,'Chernobyl');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (180927,'Chernobyl');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (181210,'Chernobyl');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (185340,'Chernobyl');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (188511,'Chernobyl');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (189698,'Chernobyl');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (190432,'Chernobyl');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (194377,'Chernobyl');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (108713,'Cobra Kai');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (109213,'Cobra Kai');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (110407,'Cobra Kai');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (111172,'Cobra Kai');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (129364,'Cobra Kai');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (129682,'Cobra Kai');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (132540,'Cobra Kai');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (134450,'Cobra Kai');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (141966,'Cobra Kai');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (146796,'Cobra Kai');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (147015,'Cobra Kai');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (154103,'Cobra Kai');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (160485,'Cobra Kai');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (167683,'Cobra Kai');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (168860,'Cobra Kai');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (176730,'Cobra Kai');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (181174,'Cobra Kai');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (182546,'Cobra Kai');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (187647,'Cobra Kai');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (199611,'Cobra Kai');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (100584,'Dark');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (102612,'Dark');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (122884,'Dark');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (129807,'Dark');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (131367,'Dark');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (133785,'Dark');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (135314,'Dark');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (140133,'Dark');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (141727,'Dark');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (142901,'Dark');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (145625,'Dark');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (153499,'Dark');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (155189,'Dark');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (156846,'Dark');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (163955,'Dark');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (171738,'Dark');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (184024,'Dark');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (185523,'Dark');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (187676,'Dark');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (188377,'Dark');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (100817,'Fargo');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (115928,'Fargo');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (116221,'Fargo');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (123716,'Fargo');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (124276,'Fargo');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (127009,'Fargo');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (128486,'Fargo');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (134948,'Fargo');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (139665,'Fargo');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (146120,'Fargo');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (146368,'Fargo');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (153396,'Fargo');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (161258,'Fargo');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (161369,'Fargo');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (162775,'Fargo');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (163178,'Fargo');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (188356,'Fargo');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (190799,'Fargo');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (196053,'Fargo');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (100293,'Friends');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (100495,'Friends');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (102059,'Friends');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (108586,'Friends');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (112600,'Friends');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (114246,'Friends');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (114835,'Friends');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (120095,'Friends');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (124207,'Friends');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (134544,'Friends');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (135801,'Friends');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (136290,'Friends');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (142714,'Friends');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (149219,'Friends');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (158008,'Friends');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (162509,'Friends');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (167626,'Friends');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (171979,'Friends');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (189454,'Friends');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (196434,'Friends');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (100793,'Game of Thrones');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (101564,'Game of Thrones');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (104961,'Game of Thrones');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (107707,'Game of Thrones');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (112970,'Game of Thrones');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (118629,'Game of Thrones');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (123094,'Game of Thrones');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (126516,'Game of Thrones');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (128113,'Game of Thrones');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (129855,'Game of Thrones');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (130891,'Game of Thrones');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (146584,'Game of Thrones');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (147189,'Game of Thrones');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (165061,'Game of Thrones');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (176348,'Game of Thrones');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (177861,'Game of Thrones');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (185873,'Game of Thrones');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (186070,'Game of Thrones');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (189232,'Game of Thrones');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (194092,'Game of Thrones');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (105674,'Grey\'s Anatomy');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (108247,'Grey\'s Anatomy');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (118274,'Grey\'s Anatomy');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (122035,'Grey\'s Anatomy');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (122499,'Grey\'s Anatomy');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (137293,'Grey\'s Anatomy');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (138221,'Grey\'s Anatomy');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (150610,'Grey\'s Anatomy');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (154489,'Grey\'s Anatomy');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (158057,'Grey\'s Anatomy');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (158775,'Grey\'s Anatomy');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (159557,'Grey\'s Anatomy');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (171784,'Grey\'s Anatomy');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (177349,'Grey\'s Anatomy');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (177470,'Grey\'s Anatomy');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (184482,'Grey\'s Anatomy');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (184655,'Grey\'s Anatomy');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (185663,'Grey\'s Anatomy');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (191980,'Grey\'s Anatomy');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (192566,'Grey\'s Anatomy');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (124283,'Homeland');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (136538,'Homeland');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (147497,'Homeland');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (148027,'Homeland');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (151463,'Homeland');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (153400,'Homeland');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (154183,'Homeland');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (155689,'Homeland');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (155751,'Homeland');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (159057,'Homeland');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (159833,'Homeland');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (163818,'Homeland');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (167075,'Homeland');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (168947,'Homeland');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (170561,'Homeland');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (171053,'Homeland');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (178202,'Homeland');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (178690,'Homeland');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (182341,'Homeland');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (191759,'Homeland');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (104169,'House of Cards');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (106417,'House of Cards');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (110594,'House of Cards');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (112528,'House of Cards');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (113083,'House of Cards');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (125848,'House of Cards');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (125907,'House of Cards');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (131071,'House of Cards');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (136272,'House of Cards');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (139370,'House of Cards');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (141492,'House of Cards');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (145325,'House of Cards');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (148100,'House of Cards');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (148219,'House of Cards');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (152159,'House of Cards');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (156094,'House of Cards');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (190561,'House of Cards');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (193321,'House of Cards');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (195020,'House of Cards');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (197243,'House of Cards');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (100674,'How to Get Away with Murder');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (109363,'How to Get Away with Murder');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (111786,'How to Get Away with Murder');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (116578,'How to Get Away with Murder');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (118098,'How to Get Away with Murder');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (118966,'How to Get Away with Murder');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (121228,'How to Get Away with Murder');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (122301,'How to Get Away with Murder');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (123493,'How to Get Away with Murder');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (133641,'How to Get Away with Murder');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (141972,'How to Get Away with Murder');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (147777,'How to Get Away with Murder');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (149680,'How to Get Away with Murder');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (150703,'How to Get Away with Murder');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (151640,'How to Get Away with Murder');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (152897,'How to Get Away with Murder');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (180131,'How to Get Away with Murder');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (181972,'How to Get Away with Murder');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (186613,'How to Get Away with Murder');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (190146,'How to Get Away with Murder');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (107731,'Lost');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (116079,'Lost');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (124711,'Lost');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (126741,'Lost');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (128945,'Lost');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (135120,'Lost');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (140184,'Lost');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (143396,'Lost');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (150486,'Lost');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (150705,'Lost');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (159466,'Lost');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (160890,'Lost');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (162540,'Lost');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (169141,'Lost');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (171323,'Lost');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (174553,'Lost');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (178220,'Lost');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (178679,'Lost');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (188584,'Lost');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (194292,'Lost');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (106958,'Lucifer');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (116588,'Lucifer');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (127827,'Lucifer');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (136422,'Lucifer');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (136737,'Lucifer');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (136872,'Lucifer');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (136910,'Lucifer');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (137964,'Lucifer');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (140932,'Lucifer');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (167240,'Lucifer');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (171515,'Lucifer');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (176551,'Lucifer');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (180389,'Lucifer');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (183796,'Lucifer');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (187716,'Lucifer');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (192678,'Lucifer');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (193227,'Lucifer');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (195111,'Lucifer');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (195747,'Lucifer');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (199074,'Lucifer');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (106075,'Mindhunter');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (109217,'Mindhunter');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (110280,'Mindhunter');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (115569,'Mindhunter');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (128547,'Mindhunter');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (130323,'Mindhunter');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (134449,'Mindhunter');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (136837,'Mindhunter');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (140754,'Mindhunter');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (153408,'Mindhunter');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (155738,'Mindhunter');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (161323,'Mindhunter');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (166049,'Mindhunter');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (167358,'Mindhunter');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (169183,'Mindhunter');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (170188,'Mindhunter');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (171109,'Mindhunter');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (180072,'Mindhunter');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (190613,'Mindhunter');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (198441,'Mindhunter');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (102951,'Money Heist');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (108676,'Money Heist');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (109993,'Money Heist');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (116846,'Money Heist');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (126915,'Money Heist');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (128751,'Money Heist');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (130006,'Money Heist');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (132136,'Money Heist');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (144195,'Money Heist');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (155419,'Money Heist');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (159232,'Money Heist');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (169831,'Money Heist');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (174055,'Money Heist');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (174103,'Money Heist');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (175627,'Money Heist');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (182318,'Money Heist');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (182921,'Money Heist');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (191962,'Money Heist');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (192285,'Money Heist');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (197409,'Money Heist');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (100751,'Narcos');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (100769,'Narcos');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (106223,'Narcos');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (109032,'Narcos');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (113979,'Narcos');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (118218,'Narcos');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (123711,'Narcos');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (124378,'Narcos');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (127184,'Narcos');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (127989,'Narcos');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (140084,'Narcos');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (140411,'Narcos');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (148895,'Narcos');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (154602,'Narcos');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (158374,'Narcos');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (162141,'Narcos');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (168287,'Narcos');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (171299,'Narcos');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (182485,'Narcos');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (187585,'Narcos');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (103498,'Orange Is the New Black');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (105272,'Orange Is the New Black');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (120786,'Orange Is the New Black');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (125198,'Orange Is the New Black');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (138188,'Orange Is the New Black');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (146439,'Orange Is the New Black');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (147016,'Orange Is the New Black');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (148326,'Orange Is the New Black');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (148514,'Orange Is the New Black');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (153478,'Orange Is the New Black');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (153742,'Orange Is the New Black');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (162210,'Orange Is the New Black');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (163779,'Orange Is the New Black');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (173707,'Orange Is the New Black');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (175620,'Orange Is the New Black');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (181628,'Orange Is the New Black');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (182170,'Orange Is the New Black');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (184318,'Orange Is the New Black');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (194467,'Orange Is the New Black');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (100638,'Ozark');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (107936,'Ozark');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (112265,'Ozark');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (119563,'Ozark');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (121055,'Ozark');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (129324,'Ozark');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (130675,'Ozark');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (131646,'Ozark');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (134424,'Ozark');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (140940,'Ozark');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (142285,'Ozark');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (152903,'Ozark');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (156623,'Ozark');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (159720,'Ozark');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (162297,'Ozark');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (164121,'Ozark');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (164151,'Ozark');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (173902,'Ozark');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (175031,'Ozark');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (194497,'Ozark');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (113254,'Parks and Recreation');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (113601,'Parks and Recreation');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (114458,'Parks and Recreation');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (119212,'Parks and Recreation');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (126798,'Parks and Recreation');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (127094,'Parks and Recreation');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (133509,'Parks and Recreation');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (143358,'Parks and Recreation');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (143780,'Parks and Recreation');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (147843,'Parks and Recreation');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (156438,'Parks and Recreation');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (158336,'Parks and Recreation');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (161857,'Parks and Recreation');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (168044,'Parks and Recreation');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (169279,'Parks and Recreation');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (173398,'Parks and Recreation');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (180208,'Parks and Recreation');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (183116,'Parks and Recreation');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (195340,'Parks and Recreation');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (198037,'Parks and Recreation');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (107678,'Peaky Blinders');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (112115,'Peaky Blinders');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (116698,'Peaky Blinders');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (126105,'Peaky Blinders');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (131682,'Peaky Blinders');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (132192,'Peaky Blinders');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (138747,'Peaky Blinders');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (142342,'Peaky Blinders');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (142401,'Peaky Blinders');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (148680,'Peaky Blinders');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (149132,'Peaky Blinders');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (155187,'Peaky Blinders');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (169437,'Peaky Blinders');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (173923,'Peaky Blinders');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (174361,'Peaky Blinders');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (174402,'Peaky Blinders');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (181095,'Peaky Blinders');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (183605,'Peaky Blinders');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (186007,'Peaky Blinders');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (190416,'Peaky Blinders');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (101078,'Sherlock');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (106016,'Sherlock');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (108889,'Sherlock');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (109112,'Sherlock');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (110500,'Sherlock');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (117027,'Sherlock');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (118502,'Sherlock');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (121712,'Sherlock');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (124724,'Sherlock');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (126320,'Sherlock');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (133244,'Sherlock');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (146963,'Sherlock');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (153375,'Sherlock');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (165295,'Sherlock');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (171570,'Sherlock');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (173263,'Sherlock');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (173281,'Sherlock');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (189364,'Sherlock');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (191967,'Sherlock');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (195025,'Sherlock');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (100263,'Sons of Anarchy');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (100781,'Sons of Anarchy');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (107252,'Sons of Anarchy');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (113590,'Sons of Anarchy');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (125440,'Sons of Anarchy');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (128975,'Sons of Anarchy');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (129625,'Sons of Anarchy');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (134153,'Sons of Anarchy');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (136710,'Sons of Anarchy');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (144311,'Sons of Anarchy');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (150054,'Sons of Anarchy');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (159873,'Sons of Anarchy');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (161836,'Sons of Anarchy');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (170838,'Sons of Anarchy');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (170993,'Sons of Anarchy');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (187235,'Sons of Anarchy');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (191149,'Sons of Anarchy');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (192491,'Sons of Anarchy');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (199441,'Sons of Anarchy');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (110609,'Stranger Things');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (111013,'Stranger Things');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (115644,'Stranger Things');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (123594,'Stranger Things');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (126244,'Stranger Things');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (126857,'Stranger Things');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (130875,'Stranger Things');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (137705,'Stranger Things');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (142642,'Stranger Things');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (155245,'Stranger Things');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (155373,'Stranger Things');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (156645,'Stranger Things');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (170359,'Stranger Things');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (172226,'Stranger Things');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (178909,'Stranger Things');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (181020,'Stranger Things');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (182530,'Stranger Things');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (184946,'Stranger Things');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (190154,'Stranger Things');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (191078,'Stranger Things');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (101651,'Succession');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (107378,'Succession');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (116663,'Succession');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (122496,'Succession');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (126203,'Succession');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (138297,'Succession');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (142765,'Succession');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (144850,'Succession');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (146349,'Succession');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (146733,'Succession');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (150151,'Succession');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (153167,'Succession');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (155626,'Succession');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (156552,'Succession');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (164146,'Succession');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (169922,'Succession');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (176392,'Succession');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (177377,'Succession');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (187457,'Succession');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (192607,'Succession');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (100423,'Supernatural');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (106744,'Supernatural');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (111996,'Supernatural');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (116248,'Supernatural');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (117403,'Supernatural');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (135754,'Supernatural');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (137473,'Supernatural');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (143872,'Supernatural');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (144824,'Supernatural');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (148640,'Supernatural');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (149116,'Supernatural');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (150071,'Supernatural');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (154088,'Supernatural');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (154864,'Supernatural');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (156656,'Supernatural');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (158725,'Supernatural');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (162800,'Supernatural');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (170685,'Supernatural');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (184643,'Supernatural');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (190166,'Supernatural');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (103018,'The Americans');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (113946,'The Americans');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (115550,'The Americans');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (118548,'The Americans');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (124738,'The Americans');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (141672,'The Americans');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (144651,'The Americans');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (144897,'The Americans');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (149273,'The Americans');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (152243,'The Americans');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (159915,'The Americans');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (174851,'The Americans');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (177065,'The Americans');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (189400,'The Americans');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (190570,'The Americans');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (191669,'The Americans');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (197424,'The Americans');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (197665,'The Americans');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (197719,'The Americans');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (113015,'The Big Bang Theory');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (117507,'The Big Bang Theory');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (121298,'The Big Bang Theory');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (132734,'The Big Bang Theory');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (134486,'The Big Bang Theory');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (137874,'The Big Bang Theory');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (148938,'The Big Bang Theory');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (152745,'The Big Bang Theory');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (159442,'The Big Bang Theory');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (159638,'The Big Bang Theory');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (170404,'The Big Bang Theory');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (176286,'The Big Bang Theory');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (177517,'The Big Bang Theory');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (189394,'The Big Bang Theory');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (190488,'The Big Bang Theory');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (193464,'The Big Bang Theory');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (196519,'The Big Bang Theory');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (197058,'The Big Bang Theory');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (197492,'The Big Bang Theory');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (198542,'The Big Bang Theory');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (107910,'The Boys');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (111417,'The Boys');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (112602,'The Boys');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (117745,'The Boys');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (126751,'The Boys');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (128257,'The Boys');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (130075,'The Boys');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (133573,'The Boys');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (137818,'The Boys');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (140641,'The Boys');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (148490,'The Boys');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (149531,'The Boys');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (159427,'The Boys');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (179903,'The Boys');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (180383,'The Boys');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (185607,'The Boys');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (185608,'The Boys');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (189318,'The Boys');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (192493,'The Boys');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (199264,'The Boys');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (102065,'The Crown');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (117310,'The Crown');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (119321,'The Crown');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (120133,'The Crown');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (130213,'The Crown');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (133250,'The Crown');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (142653,'The Crown');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (151551,'The Crown');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (155771,'The Crown');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (159382,'The Crown');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (162016,'The Crown');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (165860,'The Crown');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (173881,'The Crown');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (175165,'The Crown');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (177694,'The Crown');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (185715,'The Crown');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (186522,'The Crown');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (189171,'The Crown');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (193491,'The Crown');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (196708,'The Crown');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (104503,'The Expanse');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (108535,'The Expanse');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (109680,'The Expanse');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (117363,'The Expanse');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (123896,'The Expanse');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (130381,'The Expanse');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (139438,'The Expanse');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (146164,'The Expanse');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (151235,'The Expanse');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (154981,'The Expanse');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (157406,'The Expanse');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (162434,'The Expanse');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (169985,'The Expanse');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (178973,'The Expanse');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (180781,'The Expanse');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (183403,'The Expanse');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (184141,'The Expanse');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (190232,'The Expanse');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (193476,'The Expanse');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (198597,'The Expanse');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (104041,'The Good Place');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (119213,'The Good Place');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (124583,'The Good Place');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (130035,'The Good Place');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (134980,'The Good Place');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (140808,'The Good Place');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (144341,'The Good Place');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (152864,'The Good Place');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (153553,'The Good Place');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (154387,'The Good Place');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (160522,'The Good Place');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (161919,'The Good Place');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (167651,'The Good Place');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (169387,'The Good Place');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (170580,'The Good Place');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (171893,'The Good Place');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (182577,'The Good Place');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (183239,'The Good Place');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (189657,'The Good Place');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (194255,'The Good Place');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (103919,'The Handmaid\'s Tale');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (111537,'The Handmaid\'s Tale');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (133094,'The Handmaid\'s Tale');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (134331,'The Handmaid\'s Tale');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (137360,'The Handmaid\'s Tale');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (139201,'The Handmaid\'s Tale');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (143473,'The Handmaid\'s Tale');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (146418,'The Handmaid\'s Tale');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (153092,'The Handmaid\'s Tale');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (159308,'The Handmaid\'s Tale');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (163338,'The Handmaid\'s Tale');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (164455,'The Handmaid\'s Tale');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (164692,'The Handmaid\'s Tale');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (165543,'The Handmaid\'s Tale');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (166579,'The Handmaid\'s Tale');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (167520,'The Handmaid\'s Tale');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (178796,'The Handmaid\'s Tale');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (181067,'The Handmaid\'s Tale');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (184727,'The Handmaid\'s Tale');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (194801,'The Handmaid\'s Tale');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (105802,'The Haunting of Hill House');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (116189,'The Haunting of Hill House');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (117818,'The Haunting of Hill House');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (124144,'The Haunting of Hill House');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (132538,'The Haunting of Hill House');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (137288,'The Haunting of Hill House');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (140019,'The Haunting of Hill House');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (147415,'The Haunting of Hill House');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (149667,'The Haunting of Hill House');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (157583,'The Haunting of Hill House');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (159511,'The Haunting of Hill House');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (159728,'The Haunting of Hill House');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (162875,'The Haunting of Hill House');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (168643,'The Haunting of Hill House');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (171079,'The Haunting of Hill House');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (185470,'The Haunting of Hill House');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (186406,'The Haunting of Hill House');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (190084,'The Haunting of Hill House');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (197041,'The Haunting of Hill House');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (103296,'The Mandalorian');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (103893,'The Mandalorian');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (108046,'The Mandalorian');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (110413,'The Mandalorian');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (110796,'The Mandalorian');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (110932,'The Mandalorian');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (111532,'The Mandalorian');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (113731,'The Mandalorian');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (115123,'The Mandalorian');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (118921,'The Mandalorian');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (120362,'The Mandalorian');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (125348,'The Mandalorian');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (126779,'The Mandalorian');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (134443,'The Mandalorian');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (136867,'The Mandalorian');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (167419,'The Mandalorian');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (181530,'The Mandalorian');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (187056,'The Mandalorian');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (193415,'The Mandalorian');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (193514,'The Mandalorian');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (111886,'The Marvelous Mrs. Maisel');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (122037,'The Marvelous Mrs. Maisel');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (124420,'The Marvelous Mrs. Maisel');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (131473,'The Marvelous Mrs. Maisel');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (132471,'The Marvelous Mrs. Maisel');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (135663,'The Marvelous Mrs. Maisel');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (137599,'The Marvelous Mrs. Maisel');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (138342,'The Marvelous Mrs. Maisel');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (138991,'The Marvelous Mrs. Maisel');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (143283,'The Marvelous Mrs. Maisel');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (145452,'The Marvelous Mrs. Maisel');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (150717,'The Marvelous Mrs. Maisel');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (154814,'The Marvelous Mrs. Maisel');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (156444,'The Marvelous Mrs. Maisel');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (165094,'The Marvelous Mrs. Maisel');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (168050,'The Marvelous Mrs. Maisel');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (179305,'The Marvelous Mrs. Maisel');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (191184,'The Marvelous Mrs. Maisel');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (197175,'The Marvelous Mrs. Maisel');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (197242,'The Marvelous Mrs. Maisel');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (100222,'The Office');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (113543,'The Office');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (118359,'The Office');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (122415,'The Office');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (141129,'The Office');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (141994,'The Office');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (144093,'The Office');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (150546,'The Office');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (153007,'The Office');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (155752,'The Office');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (162959,'The Office');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (169418,'The Office');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (170262,'The Office');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (176987,'The Office');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (185960,'The Office');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (186314,'The Office');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (190369,'The Office');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (192226,'The Office');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (193333,'The Office');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (193816,'The Office');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (102489,'The Sopranos');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (102642,'The Sopranos');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (116775,'The Sopranos');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (117424,'The Sopranos');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (121981,'The Sopranos');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (122718,'The Sopranos');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (123248,'The Sopranos');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (133342,'The Sopranos');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (134200,'The Sopranos');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (135945,'The Sopranos');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (136127,'The Sopranos');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (137487,'The Sopranos');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (140460,'The Sopranos');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (140798,'The Sopranos');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (169553,'The Sopranos');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (170191,'The Sopranos');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (184094,'The Sopranos');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (187248,'The Sopranos');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (189355,'The Sopranos');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (191136,'The Sopranos');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (102771,'The Umbrella Academy');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (112353,'The Umbrella Academy');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (115714,'The Umbrella Academy');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (116269,'The Umbrella Academy');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (118295,'The Umbrella Academy');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (120679,'The Umbrella Academy');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (126677,'The Umbrella Academy');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (126980,'The Umbrella Academy');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (131703,'The Umbrella Academy');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (139903,'The Umbrella Academy');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (140095,'The Umbrella Academy');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (142138,'The Umbrella Academy');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (159682,'The Umbrella Academy');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (170564,'The Umbrella Academy');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (173608,'The Umbrella Academy');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (174644,'The Umbrella Academy');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (187047,'The Umbrella Academy');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (188226,'The Umbrella Academy');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (194068,'The Umbrella Academy');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (102122,'The Walking Dead');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (111181,'The Walking Dead');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (114581,'The Walking Dead');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (118082,'The Walking Dead');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (121357,'The Walking Dead');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (126863,'The Walking Dead');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (127709,'The Walking Dead');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (130512,'The Walking Dead');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (148365,'The Walking Dead');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (150487,'The Walking Dead');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (154424,'The Walking Dead');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (159152,'The Walking Dead');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (164394,'The Walking Dead');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (174222,'The Walking Dead');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (180581,'The Walking Dead');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (182470,'The Walking Dead');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (188672,'The Walking Dead');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (188745,'The Walking Dead');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (189914,'The Walking Dead');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (194116,'The Walking Dead');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (100779,'The West Wing');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (100992,'The West Wing');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (106516,'The West Wing');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (110625,'The West Wing');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (116667,'The West Wing');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (128977,'The West Wing');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (133078,'The West Wing');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (134774,'The West Wing');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (142222,'The West Wing');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (146612,'The West Wing');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (147714,'The West Wing');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (150047,'The West Wing');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (151963,'The West Wing');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (152978,'The West Wing');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (161457,'The West Wing');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (169162,'The West Wing');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (170989,'The West Wing');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (176174,'The West Wing');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (178200,'The West Wing');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (188773,'The West Wing');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (103698,'The Wire');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (111052,'The Wire');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (112821,'The Wire');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (116706,'The Wire');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (119242,'The Wire');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (122790,'The Wire');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (136040,'The Wire');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (141416,'The Wire');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (141469,'The Wire');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (143238,'The Wire');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (159719,'The Wire');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (166028,'The Wire');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (167036,'The Wire');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (167476,'The Wire');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (169828,'The Wire');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (170181,'The Wire');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (170878,'The Wire');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (182086,'The Wire');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (185838,'The Wire');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (186139,'The Wire');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (102831,'The Witcher');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (104348,'The Witcher');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (111362,'The Witcher');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (119460,'The Witcher');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (124355,'The Witcher');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (127695,'The Witcher');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (134150,'The Witcher');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (156862,'The Witcher');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (157245,'The Witcher');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (157636,'The Witcher');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (159609,'The Witcher');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (166922,'The Witcher');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (167539,'The Witcher');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (174148,'The Witcher');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (177448,'The Witcher');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (183757,'The Witcher');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (188982,'The Witcher');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (196377,'The Witcher');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (196441,'The Witcher');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (197012,'The Witcher');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (112302,'True Detective');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (114203,'True Detective');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (116781,'True Detective');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (127572,'True Detective');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (128301,'True Detective');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (129406,'True Detective');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (130651,'True Detective');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (132009,'True Detective');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (132115,'True Detective');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (136029,'True Detective');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (136576,'True Detective');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (142015,'True Detective');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (143267,'True Detective');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (151353,'True Detective');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (153727,'True Detective');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (157121,'True Detective');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (162919,'True Detective');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (167174,'True Detective');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (169155,'True Detective');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (199982,'True Detective');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (117529,'Vikings');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (117744,'Vikings');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (130957,'Vikings');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (131597,'Vikings');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (132608,'Vikings');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (134009,'Vikings');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (141675,'Vikings');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (152099,'Vikings');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (153347,'Vikings');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (154625,'Vikings');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (158189,'Vikings');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (167271,'Vikings');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (170731,'Vikings');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (172036,'Vikings');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (175637,'Vikings');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (187873,'Vikings');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (192092,'Vikings');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (192321,'Vikings');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (192405,'Vikings');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (195472,'Vikings');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (101301,'Westworld');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (101790,'Westworld');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (110658,'Westworld');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (112006,'Westworld');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (113841,'Westworld');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (121414,'Westworld');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (131834,'Westworld');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (134644,'Westworld');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (134660,'Westworld');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (137337,'Westworld');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (155056,'Westworld');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (163131,'Westworld');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (166269,'Westworld');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (169903,'Westworld');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (172652,'Westworld');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (173453,'Westworld');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (182474,'Westworld');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (182913,'Westworld');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (194522,'Westworld');
INSERT INTO `` (`idCapitulo`,`TitIngles`) VALUES (198946,'Westworld');
