/*
-- Query: SELECT * FROM tp_bd_2023.dispositivo
LIMIT 0, 1000

-- Date: 2023-06-01 21:02
*/
INSERT INTO `` (`idDispositivo`,`Nombre`,`Tipo`,`Marca`,`HoraDescarga`) VALUES (13,'Bose SoundLink Bluetooth Speaker','Portable Speaker','Bose',1);
INSERT INTO `` (`idDispositivo`,`Nombre`,`Tipo`,`Marca`,`HoraDescarga`) VALUES (17,'LG Ultrafine Display','Monitor','LG',1);
INSERT INTO `` (`idDispositivo`,`Nombre`,`Tipo`,`Marca`,`HoraDescarga`) VALUES (20,'Huawei MateBook X Pro','Laptop','Huawei',0);
INSERT INTO `` (`idDispositivo`,`Nombre`,`Tipo`,`Marca`,`HoraDescarga`) VALUES (27,'LG Ultrafine Display','Monitor','LG',1);
INSERT INTO `` (`idDispositivo`,`Nombre`,`Tipo`,`Marca`,`HoraDescarga`) VALUES (28,'Apple iMac','Desktop Computer','Apple',0);
INSERT INTO `` (`idDispositivo`,`Nombre`,`Tipo`,`Marca`,`HoraDescarga`) VALUES (29,'Samsung Galaxy A','Mobile Phone','Samsung',0);
INSERT INTO `` (`idDispositivo`,`Nombre`,`Tipo`,`Marca`,`HoraDescarga`) VALUES (30,'Apple iMac','Desktop Computer','Apple',1);
INSERT INTO `` (`idDispositivo`,`Nombre`,`Tipo`,`Marca`,`HoraDescarga`) VALUES (33,'Apple iPhone','Mobile Phone','Apple',3);
INSERT INTO `` (`idDispositivo`,`Nombre`,`Tipo`,`Marca`,`HoraDescarga`) VALUES (36,'Samsung Galaxy A52','Mobile Phone','Samsung',1);
INSERT INTO `` (`idDispositivo`,`Nombre`,`Tipo`,`Marca`,`HoraDescarga`) VALUES (43,'Microsoft Surface Go','Tablet','Microsoft',0);
INSERT INTO `` (`idDispositivo`,`Nombre`,`Tipo`,`Marca`,`HoraDescarga`) VALUES (48,'Lenovo Smart Clock','Smart Display','Lenovo',4);
INSERT INTO `` (`idDispositivo`,`Nombre`,`Tipo`,`Marca`,`HoraDescarga`) VALUES (54,'Apple iMac','Desktop Computer','Apple',4);
INSERT INTO `` (`idDispositivo`,`Nombre`,`Tipo`,`Marca`,`HoraDescarga`) VALUES (63,'Sony Xperia 10 III','Mobile Phone','Sony',1);
INSERT INTO `` (`idDispositivo`,`Nombre`,`Tipo`,`Marca`,`HoraDescarga`) VALUES (68,'Samsung Galaxy Tab','Tablet','Samsung',1);
INSERT INTO `` (`idDispositivo`,`Nombre`,`Tipo`,`Marca`,`HoraDescarga`) VALUES (69,'Microsoft Surface Laptop','Laptop','Microsoft',2);
INSERT INTO `` (`idDispositivo`,`Nombre`,`Tipo`,`Marca`,`HoraDescarga`) VALUES (81,'Huawei MediaPad','Tablet','Huawei',1);
INSERT INTO `` (`idDispositivo`,`Nombre`,`Tipo`,`Marca`,`HoraDescarga`) VALUES (87,'Lenovo Yoga Laptop','Laptop','Lenovo',4);
INSERT INTO `` (`idDispositivo`,`Nombre`,`Tipo`,`Marca`,`HoraDescarga`) VALUES (95,'Apple iPhone SE','Mobile Phone','Apple',1);
INSERT INTO `` (`idDispositivo`,`Nombre`,`Tipo`,`Marca`,`HoraDescarga`) VALUES (98,'Google Pixel','Mobile Phone','Google',2);
INSERT INTO `` (`idDispositivo`,`Nombre`,`Tipo`,`Marca`,`HoraDescarga`) VALUES (99,'Lenovo Yoga Laptop','Laptop','Lenovo',1);
INSERT INTO `` (`idDispositivo`,`Nombre`,`Tipo`,`Marca`,`HoraDescarga`) VALUES (104,'Huawei MateBook X Pro','Laptop','Huawei',4);
INSERT INTO `` (`idDispositivo`,`Nombre`,`Tipo`,`Marca`,`HoraDescarga`) VALUES (109,'LG Gram Laptop','Laptop','LG',4);
INSERT INTO `` (`idDispositivo`,`Nombre`,`Tipo`,`Marca`,`HoraDescarga`) VALUES (114,'Garmin Forerunner','Smartwatch','Garmin',1);
INSERT INTO `` (`idDispositivo`,`Nombre`,`Tipo`,`Marca`,`HoraDescarga`) VALUES (128,'JBL Flip Portable Bluetooth Speaker','Portable Speaker','JBL',0);
INSERT INTO `` (`idDispositivo`,`Nombre`,`Tipo`,`Marca`,`HoraDescarga`) VALUES (130,'Microsoft Surface Pro','Tablet/Laptop','Microsoft',1);
INSERT INTO `` (`idDispositivo`,`Nombre`,`Tipo`,`Marca`,`HoraDescarga`) VALUES (134,'Google Pixelbook','Laptop','Google',0);
INSERT INTO `` (`idDispositivo`,`Nombre`,`Tipo`,`Marca`,`HoraDescarga`) VALUES (135,'Huawei Watch GT','Smartwatch','Huawei',1);
INSERT INTO `` (`idDispositivo`,`Nombre`,`Tipo`,`Marca`,`HoraDescarga`) VALUES (137,'Google Pixelbook Go','Laptop','Google',2);
INSERT INTO `` (`idDispositivo`,`Nombre`,`Tipo`,`Marca`,`HoraDescarga`) VALUES (139,'Google Home Mini','Smart Speaker','Google',2);
INSERT INTO `` (`idDispositivo`,`Nombre`,`Tipo`,`Marca`,`HoraDescarga`) VALUES (141,'HP Spectre x360','Laptop','HP',3);
INSERT INTO `` (`idDispositivo`,`Nombre`,`Tipo`,`Marca`,`HoraDescarga`) VALUES (144,'Apple iPhone SE','Mobile Phone','Apple',3);
INSERT INTO `` (`idDispositivo`,`Nombre`,`Tipo`,`Marca`,`HoraDescarga`) VALUES (145,'TCL Smart TV','TV','TCL',3);
INSERT INTO `` (`idDispositivo`,`Nombre`,`Tipo`,`Marca`,`HoraDescarga`) VALUES (146,'HP Spectre x360','Laptop','HP',2);
INSERT INTO `` (`idDispositivo`,`Nombre`,`Tipo`,`Marca`,`HoraDescarga`) VALUES (155,'Roku Streaming Stick','Casting Device','Roku',4);
INSERT INTO `` (`idDispositivo`,`Nombre`,`Tipo`,`Marca`,`HoraDescarga`) VALUES (165,'Huawei MediaPad M5','Tablet','Huawei',1);
INSERT INTO `` (`idDispositivo`,`Nombre`,`Tipo`,`Marca`,`HoraDescarga`) VALUES (167,'Microsoft Surface Laptop','Laptop','Microsoft',2);
INSERT INTO `` (`idDispositivo`,`Nombre`,`Tipo`,`Marca`,`HoraDescarga`) VALUES (169,'JBL Flip Portable Bluetooth Speaker','Portable Speaker','JBL',1);
INSERT INTO `` (`idDispositivo`,`Nombre`,`Tipo`,`Marca`,`HoraDescarga`) VALUES (171,'Apple Watch','Smartwatch','Apple',1);
INSERT INTO `` (`idDispositivo`,`Nombre`,`Tipo`,`Marca`,`HoraDescarga`) VALUES (174,'Amazon Echo Dot','Smart Speaker','Amazon',3);
INSERT INTO `` (`idDispositivo`,`Nombre`,`Tipo`,`Marca`,`HoraDescarga`) VALUES (180,'OnePlus 9 Pro','Mobile Phone','OnePlus',0);
INSERT INTO `` (`idDispositivo`,`Nombre`,`Tipo`,`Marca`,`HoraDescarga`) VALUES (185,'Dell XPS Laptop','Laptop','Dell',1);
INSERT INTO `` (`idDispositivo`,`Nombre`,`Tipo`,`Marca`,`HoraDescarga`) VALUES (208,'Lenovo Smart Clock','Smart Display','Lenovo',0);
INSERT INTO `` (`idDispositivo`,`Nombre`,`Tipo`,`Marca`,`HoraDescarga`) VALUES (214,'Google Chromecast','Casting Device','Google',0);
INSERT INTO `` (`idDispositivo`,`Nombre`,`Tipo`,`Marca`,`HoraDescarga`) VALUES (218,'Sony WF-1000XM4 True Wireless Earbuds','Earbuds','Sony',0);
INSERT INTO `` (`idDispositivo`,`Nombre`,`Tipo`,`Marca`,`HoraDescarga`) VALUES (222,'LG G Pad','Tablet','LG',0);
INSERT INTO `` (`idDispositivo`,`Nombre`,`Tipo`,`Marca`,`HoraDescarga`) VALUES (223,'LG Ultrafine Display','Monitor','LG',1);
INSERT INTO `` (`idDispositivo`,`Nombre`,`Tipo`,`Marca`,`HoraDescarga`) VALUES (227,'Microsoft Xbox One','Gaming Console','Microsoft',1);
INSERT INTO `` (`idDispositivo`,`Nombre`,`Tipo`,`Marca`,`HoraDescarga`) VALUES (228,'Sony SmartWatch','Smartwatch','Sony',1);
INSERT INTO `` (`idDispositivo`,`Nombre`,`Tipo`,`Marca`,`HoraDescarga`) VALUES (231,'Bose QuietComfort Headphones','Headphones','Bose',3);
INSERT INTO `` (`idDispositivo`,`Nombre`,`Tipo`,`Marca`,`HoraDescarga`) VALUES (234,'LG Gram Laptop','Laptop','LG',3);
INSERT INTO `` (`idDispositivo`,`Nombre`,`Tipo`,`Marca`,`HoraDescarga`) VALUES (252,'Samsung Galaxy Buds','Earbuds','Samsung',1);
INSERT INTO `` (`idDispositivo`,`Nombre`,`Tipo`,`Marca`,`HoraDescarga`) VALUES (257,'Apple iPhone 12','Mobile Phone','Apple',0);
INSERT INTO `` (`idDispositivo`,`Nombre`,`Tipo`,`Marca`,`HoraDescarga`) VALUES (262,'Samsung Galaxy S','Mobile Phone','Samsung',1);
INSERT INTO `` (`idDispositivo`,`Nombre`,`Tipo`,`Marca`,`HoraDescarga`) VALUES (265,'Huawei MateBook','Laptop','Huawei',4);
INSERT INTO `` (`idDispositivo`,`Nombre`,`Tipo`,`Marca`,`HoraDescarga`) VALUES (268,'LG Smart TV','TV','LG',4);
INSERT INTO `` (`idDispositivo`,`Nombre`,`Tipo`,`Marca`,`HoraDescarga`) VALUES (272,'HP Spectre x360','Laptop','HP',3);
INSERT INTO `` (`idDispositivo`,`Nombre`,`Tipo`,`Marca`,`HoraDescarga`) VALUES (286,'Samsung Blu-ray Disc Player','Blu-ray Player','Samsung',3);
INSERT INTO `` (`idDispositivo`,`Nombre`,`Tipo`,`Marca`,`HoraDescarga`) VALUES (297,'Samsung Galaxy Tab S7','Tablet','Samsung',3);
INSERT INTO `` (`idDispositivo`,`Nombre`,`Tipo`,`Marca`,`HoraDescarga`) VALUES (298,'Samsung Galaxy Buds','Earbuds','Samsung',3);
INSERT INTO `` (`idDispositivo`,`Nombre`,`Tipo`,`Marca`,`HoraDescarga`) VALUES (307,'OnePlus 9 Pro','Mobile Phone','OnePlus',1);
INSERT INTO `` (`idDispositivo`,`Nombre`,`Tipo`,`Marca`,`HoraDescarga`) VALUES (308,'LG Soundbar with Chromecast','Soundbar','LG',2);
INSERT INTO `` (`idDispositivo`,`Nombre`,`Tipo`,`Marca`,`HoraDescarga`) VALUES (313,'Sonos One Smart Speaker','Smart Speaker','Sonos',3);
INSERT INTO `` (`idDispositivo`,`Nombre`,`Tipo`,`Marca`,`HoraDescarga`) VALUES (314,'Roku Smart Soundbar','Soundbar','Roku',2);
INSERT INTO `` (`idDispositivo`,`Nombre`,`Tipo`,`Marca`,`HoraDescarga`) VALUES (315,'Sony Smart TV','TV','Sony',2);
INSERT INTO `` (`idDispositivo`,`Nombre`,`Tipo`,`Marca`,`HoraDescarga`) VALUES (320,'JBL Link Bar','Soundbar with Android TV','JBL',1);
INSERT INTO `` (`idDispositivo`,`Nombre`,`Tipo`,`Marca`,`HoraDescarga`) VALUES (322,'Apple Watch','Smartwatch','Apple',1);
INSERT INTO `` (`idDispositivo`,`Nombre`,`Tipo`,`Marca`,`HoraDescarga`) VALUES (328,'LG OLED TV','TV','LG',0);
INSERT INTO `` (`idDispositivo`,`Nombre`,`Tipo`,`Marca`,`HoraDescarga`) VALUES (331,'UE Boom Wireless Speaker','Portable Speaker','UE',1);
INSERT INTO `` (`idDispositivo`,`Nombre`,`Tipo`,`Marca`,`HoraDescarga`) VALUES (337,'Apple iPad Air','Tablet','Apple',1);
INSERT INTO `` (`idDispositivo`,`Nombre`,`Tipo`,`Marca`,`HoraDescarga`) VALUES (341,'Apple TV','Casting Device','Apple',2);
INSERT INTO `` (`idDispositivo`,`Nombre`,`Tipo`,`Marca`,`HoraDescarga`) VALUES (344,'Fossil Gen 5 Smartwatch','Smartwatch','Fossil',2);
INSERT INTO `` (`idDispositivo`,`Nombre`,`Tipo`,`Marca`,`HoraDescarga`) VALUES (346,'Bose QuietComfort Headphones','Headphones','Bose',2);
INSERT INTO `` (`idDispositivo`,`Nombre`,`Tipo`,`Marca`,`HoraDescarga`) VALUES (351,'Samsung Galaxy Watch','Smartwatch','Samsung',2);
INSERT INTO `` (`idDispositivo`,`Nombre`,`Tipo`,`Marca`,`HoraDescarga`) VALUES (353,'Google Nest Hub','Smart Display','Google',1);
INSERT INTO `` (`idDispositivo`,`Nombre`,`Tipo`,`Marca`,`HoraDescarga`) VALUES (356,'Asus ZenBook Laptop','Laptop','Asus',2);
INSERT INTO `` (`idDispositivo`,`Nombre`,`Tipo`,`Marca`,`HoraDescarga`) VALUES (357,'LG K42','Mobile Phone','LG',2);
INSERT INTO `` (`idDispositivo`,`Nombre`,`Tipo`,`Marca`,`HoraDescarga`) VALUES (361,'Google Nest Mini','Smart Speaker','Google',1);
INSERT INTO `` (`idDispositivo`,`Nombre`,`Tipo`,`Marca`,`HoraDescarga`) VALUES (366,'LG Smart TV','TV','LG',3);
INSERT INTO `` (`idDispositivo`,`Nombre`,`Tipo`,`Marca`,`HoraDescarga`) VALUES (370,'Google Pixel Slate','Tablet','Google',3);
INSERT INTO `` (`idDispositivo`,`Nombre`,`Tipo`,`Marca`,`HoraDescarga`) VALUES (373,'OnePlus 9 Pro','Mobile Phone','OnePlus',3);
INSERT INTO `` (`idDispositivo`,`Nombre`,`Tipo`,`Marca`,`HoraDescarga`) VALUES (378,'Roku Streaming Stick','Casting Device','Roku',2);
INSERT INTO `` (`idDispositivo`,`Nombre`,`Tipo`,`Marca`,`HoraDescarga`) VALUES (381,'Apple iMac','Desktop Computer','Apple',0);
INSERT INTO `` (`idDispositivo`,`Nombre`,`Tipo`,`Marca`,`HoraDescarga`) VALUES (382,'TCL Smart TV','TV','TCL',1);
INSERT INTO `` (`idDispositivo`,`Nombre`,`Tipo`,`Marca`,`HoraDescarga`) VALUES (387,'Apple Watch','Smartwatch','Apple',0);
INSERT INTO `` (`idDispositivo`,`Nombre`,`Tipo`,`Marca`,`HoraDescarga`) VALUES (394,'Asus ZenBook Laptop','Laptop','Asus',0);
INSERT INTO `` (`idDispositivo`,`Nombre`,`Tipo`,`Marca`,`HoraDescarga`) VALUES (395,'Samsung Galaxy S21','Mobile Phone','Samsung',1);
INSERT INTO `` (`idDispositivo`,`Nombre`,`Tipo`,`Marca`,`HoraDescarga`) VALUES (398,'JBL Free True Wireless Earbuds','Earbuds','JBL',1);
INSERT INTO `` (`idDispositivo`,`Nombre`,`Tipo`,`Marca`,`HoraDescarga`) VALUES (401,'LG G Pad 5','Tablet','LG',3);
INSERT INTO `` (`idDispositivo`,`Nombre`,`Tipo`,`Marca`,`HoraDescarga`) VALUES (406,'Sony Smart TV','TV','Sony',1);
INSERT INTO `` (`idDispositivo`,`Nombre`,`Tipo`,`Marca`,`HoraDescarga`) VALUES (417,'Sony Xperia 5 II','Mobile Phone','Sony',1);
INSERT INTO `` (`idDispositivo`,`Nombre`,`Tipo`,`Marca`,`HoraDescarga`) VALUES (419,'UE Boom Wireless Speaker','Portable Speaker','UE',4);
INSERT INTO `` (`idDispositivo`,`Nombre`,`Tipo`,`Marca`,`HoraDescarga`) VALUES (425,'Amazon Fire HD Tablet','Tablet','Amazon',0);
INSERT INTO `` (`idDispositivo`,`Nombre`,`Tipo`,`Marca`,`HoraDescarga`) VALUES (427,'LG Velvet','Mobile Phone','LG',1);
INSERT INTO `` (`idDispositivo`,`Nombre`,`Tipo`,`Marca`,`HoraDescarga`) VALUES (433,'Samsung Galaxy Note 20','Mobile Phone','Samsung',2);
INSERT INTO `` (`idDispositivo`,`Nombre`,`Tipo`,`Marca`,`HoraDescarga`) VALUES (437,'Huawei Watch GT','Smartwatch','Huawei',3);
INSERT INTO `` (`idDispositivo`,`Nombre`,`Tipo`,`Marca`,`HoraDescarga`) VALUES (438,'Apple MacBook Pro','Laptop','Apple',2);
INSERT INTO `` (`idDispositivo`,`Nombre`,`Tipo`,`Marca`,`HoraDescarga`) VALUES (444,'Fitbit Versa','Smartwatch','Fitbit',3);
INSERT INTO `` (`idDispositivo`,`Nombre`,`Tipo`,`Marca`,`HoraDescarga`) VALUES (455,'Google Pixelbook Go','Laptop','Google',4);
INSERT INTO `` (`idDispositivo`,`Nombre`,`Tipo`,`Marca`,`HoraDescarga`) VALUES (456,'Sony WH-1000XM4 Headphones','Headphones','Sony',1);
INSERT INTO `` (`idDispositivo`,`Nombre`,`Tipo`,`Marca`,`HoraDescarga`) VALUES (460,'Apple AirPods','Earbuds','Apple',0);
INSERT INTO `` (`idDispositivo`,`Nombre`,`Tipo`,`Marca`,`HoraDescarga`) VALUES (468,'JBL Flip Portable Bluetooth Speaker','Portable Speaker','JBL',1);
INSERT INTO `` (`idDispositivo`,`Nombre`,`Tipo`,`Marca`,`HoraDescarga`) VALUES (471,'Samsung Galaxy Buds','Earbuds','Samsung',1);
INSERT INTO `` (`idDispositivo`,`Nombre`,`Tipo`,`Marca`,`HoraDescarga`) VALUES (479,'Sony WF-1000XM4 True Wireless Earbuds','Earbuds','Sony',2);
INSERT INTO `` (`idDispositivo`,`Nombre`,`Tipo`,`Marca`,`HoraDescarga`) VALUES (486,'Samsung Smart TV','TV','Samsung',3);
INSERT INTO `` (`idDispositivo`,`Nombre`,`Tipo`,`Marca`,`HoraDescarga`) VALUES (488,'Garmin Forerunner','Smartwatch','Garmin',1);
INSERT INTO `` (`idDispositivo`,`Nombre`,`Tipo`,`Marca`,`HoraDescarga`) VALUES (489,'OnePlus Nord','Mobile Phone','OnePlus',0);
INSERT INTO `` (`idDispositivo`,`Nombre`,`Tipo`,`Marca`,`HoraDescarga`) VALUES (490,'Asus ZenBook Laptop','Laptop','Asus',3);
INSERT INTO `` (`idDispositivo`,`Nombre`,`Tipo`,`Marca`,`HoraDescarga`) VALUES (497,'Bose SoundLink Bluetooth Speaker','Portable Speaker','Bose',4);
INSERT INTO `` (`idDispositivo`,`Nombre`,`Tipo`,`Marca`,`HoraDescarga`) VALUES (502,'Samsung Galaxy A52','Mobile Phone','Samsung',1);
INSERT INTO `` (`idDispositivo`,`Nombre`,`Tipo`,`Marca`,`HoraDescarga`) VALUES (507,'Apple iPad Air','Tablet','Apple',1);
INSERT INTO `` (`idDispositivo`,`Nombre`,`Tipo`,`Marca`,`HoraDescarga`) VALUES (508,'Sony WH-1000XM4 Headphones','Headphones','Sony',1);
INSERT INTO `` (`idDispositivo`,`Nombre`,`Tipo`,`Marca`,`HoraDescarga`) VALUES (511,'Samsung Galaxy Watch','Smartwatch','Samsung',3);
INSERT INTO `` (`idDispositivo`,`Nombre`,`Tipo`,`Marca`,`HoraDescarga`) VALUES (512,'Sonos One Smart Speaker','Smart Speaker','Sonos',4);
INSERT INTO `` (`idDispositivo`,`Nombre`,`Tipo`,`Marca`,`HoraDescarga`) VALUES (518,'Fossil Gen 5 Smartwatch','Smartwatch','Fossil',0);
INSERT INTO `` (`idDispositivo`,`Nombre`,`Tipo`,`Marca`,`HoraDescarga`) VALUES (519,'Google Pixel 5','Mobile Phone','Google',0);
INSERT INTO `` (`idDispositivo`,`Nombre`,`Tipo`,`Marca`,`HoraDescarga`) VALUES (525,'Google Pixel 5','Mobile Phone','Google',0);
INSERT INTO `` (`idDispositivo`,`Nombre`,`Tipo`,`Marca`,`HoraDescarga`) VALUES (528,'Google Nest Hub Max','Smart Display','Google',2);
INSERT INTO `` (`idDispositivo`,`Nombre`,`Tipo`,`Marca`,`HoraDescarga`) VALUES (530,'Microsoft Xbox One','Gaming Console','Microsoft',1);
INSERT INTO `` (`idDispositivo`,`Nombre`,`Tipo`,`Marca`,`HoraDescarga`) VALUES (532,'Fitbit Versa','Smartwatch','Fitbit',1);
INSERT INTO `` (`idDispositivo`,`Nombre`,`Tipo`,`Marca`,`HoraDescarga`) VALUES (539,'Bose QuietComfort Headphones','Headphones','Bose',2);
INSERT INTO `` (`idDispositivo`,`Nombre`,`Tipo`,`Marca`,`HoraDescarga`) VALUES (540,'Sony Xperia 10 III','Mobile Phone','Sony',3);
INSERT INTO `` (`idDispositivo`,`Nombre`,`Tipo`,`Marca`,`HoraDescarga`) VALUES (541,'LG XBOOM Go Portable Speaker','Portable Speaker','LG',2);
INSERT INTO `` (`idDispositivo`,`Nombre`,`Tipo`,`Marca`,`HoraDescarga`) VALUES (542,'Google Pixel 4a','Mobile Phone','Google',0);
INSERT INTO `` (`idDispositivo`,`Nombre`,`Tipo`,`Marca`,`HoraDescarga`) VALUES (545,'UE Boom Wireless Speaker','Portable Speaker','UE',0);
INSERT INTO `` (`idDispositivo`,`Nombre`,`Tipo`,`Marca`,`HoraDescarga`) VALUES (546,'Sony Xperia','Mobile Phone','Sony',2);
INSERT INTO `` (`idDispositivo`,`Nombre`,`Tipo`,`Marca`,`HoraDescarga`) VALUES (548,'Samsung Galaxy Book Flex','Laptop','Samsung',1);
INSERT INTO `` (`idDispositivo`,`Nombre`,`Tipo`,`Marca`,`HoraDescarga`) VALUES (562,'Sony Smart TV','TV','Sony',2);
INSERT INTO `` (`idDispositivo`,`Nombre`,`Tipo`,`Marca`,`HoraDescarga`) VALUES (565,'Huawei MateBook X Pro','Laptop','Huawei',1);
INSERT INTO `` (`idDispositivo`,`Nombre`,`Tipo`,`Marca`,`HoraDescarga`) VALUES (567,'Samsung Galaxy S','Mobile Phone','Samsung',0);
INSERT INTO `` (`idDispositivo`,`Nombre`,`Tipo`,`Marca`,`HoraDescarga`) VALUES (570,'Samsung Galaxy Watch Active','Smartwatch','Samsung',3);
INSERT INTO `` (`idDispositivo`,`Nombre`,`Tipo`,`Marca`,`HoraDescarga`) VALUES (574,'LG Ultrafine Display','Monitor','LG',4);
INSERT INTO `` (`idDispositivo`,`Nombre`,`Tipo`,`Marca`,`HoraDescarga`) VALUES (586,'LG XBOOM Go Portable Speaker','Portable Speaker','LG',2);
INSERT INTO `` (`idDispositivo`,`Nombre`,`Tipo`,`Marca`,`HoraDescarga`) VALUES (587,'Apple iPhone 12','Mobile Phone','Apple',2);
INSERT INTO `` (`idDispositivo`,`Nombre`,`Tipo`,`Marca`,`HoraDescarga`) VALUES (591,'Google Pixel Slate','Tablet','Google',3);
INSERT INTO `` (`idDispositivo`,`Nombre`,`Tipo`,`Marca`,`HoraDescarga`) VALUES (594,'OnePlus Nord','Mobile Phone','OnePlus',1);
INSERT INTO `` (`idDispositivo`,`Nombre`,`Tipo`,`Marca`,`HoraDescarga`) VALUES (599,'Amazon Fire Tablet','Tablet','Amazon',0);
INSERT INTO `` (`idDispositivo`,`Nombre`,`Tipo`,`Marca`,`HoraDescarga`) VALUES (606,'Google Pixel 4a','Mobile Phone','Google',0);
INSERT INTO `` (`idDispositivo`,`Nombre`,`Tipo`,`Marca`,`HoraDescarga`) VALUES (609,'Apple MacBook Pro','Laptop','Apple',1);
INSERT INTO `` (`idDispositivo`,`Nombre`,`Tipo`,`Marca`,`HoraDescarga`) VALUES (610,'Samsung Galaxy Note 20','Mobile Phone','Samsung',0);
INSERT INTO `` (`idDispositivo`,`Nombre`,`Tipo`,`Marca`,`HoraDescarga`) VALUES (621,'TCL Roku TV','TV','TCL',1);
INSERT INTO `` (`idDispositivo`,`Nombre`,`Tipo`,`Marca`,`HoraDescarga`) VALUES (623,'OnePlus 9 Pro','Mobile Phone','OnePlus',2);
INSERT INTO `` (`idDispositivo`,`Nombre`,`Tipo`,`Marca`,`HoraDescarga`) VALUES (625,'UE Boom Wireless Speaker','Portable Speaker','UE',3);
INSERT INTO `` (`idDispositivo`,`Nombre`,`Tipo`,`Marca`,`HoraDescarga`) VALUES (634,'Google Nest Hub Max','Smart Display','Google',0);
INSERT INTO `` (`idDispositivo`,`Nombre`,`Tipo`,`Marca`,`HoraDescarga`) VALUES (638,'Samsung Galaxy Tab','Tablet','Samsung',4);
INSERT INTO `` (`idDispositivo`,`Nombre`,`Tipo`,`Marca`,`HoraDescarga`) VALUES (640,'Google Pixelbook','Laptop','Google',1);
INSERT INTO `` (`idDispositivo`,`Nombre`,`Tipo`,`Marca`,`HoraDescarga`) VALUES (644,'Google Home Mini','Smart Speaker','Google',3);
INSERT INTO `` (`idDispositivo`,`Nombre`,`Tipo`,`Marca`,`HoraDescarga`) VALUES (671,'Google Nest Hub','Smart Display','Google',3);
INSERT INTO `` (`idDispositivo`,`Nombre`,`Tipo`,`Marca`,`HoraDescarga`) VALUES (672,'Samsung Galaxy A52','Mobile Phone','Samsung',2);
INSERT INTO `` (`idDispositivo`,`Nombre`,`Tipo`,`Marca`,`HoraDescarga`) VALUES (673,'Apple iMac','Desktop Computer','Apple',1);
INSERT INTO `` (`idDispositivo`,`Nombre`,`Tipo`,`Marca`,`HoraDescarga`) VALUES (674,'Asus ZenBook Laptop','Laptop','Asus',1);
INSERT INTO `` (`idDispositivo`,`Nombre`,`Tipo`,`Marca`,`HoraDescarga`) VALUES (676,'Samsung Galaxy Buds','Earbuds','Samsung',1);
INSERT INTO `` (`idDispositivo`,`Nombre`,`Tipo`,`Marca`,`HoraDescarga`) VALUES (677,'Amazon Fire HD Tablet','Tablet','Amazon',0);
INSERT INTO `` (`idDispositivo`,`Nombre`,`Tipo`,`Marca`,`HoraDescarga`) VALUES (678,'OnePlus Nord','Mobile Phone','OnePlus',4);
INSERT INTO `` (`idDispositivo`,`Nombre`,`Tipo`,`Marca`,`HoraDescarga`) VALUES (684,'Apple AirPods','Earbuds','Apple',0);
INSERT INTO `` (`idDispositivo`,`Nombre`,`Tipo`,`Marca`,`HoraDescarga`) VALUES (688,'Sony Blu-ray Disc Player','Blu-ray Player','Sony',2);
INSERT INTO `` (`idDispositivo`,`Nombre`,`Tipo`,`Marca`,`HoraDescarga`) VALUES (691,'Apple Watch','Smartwatch','Apple',0);
INSERT INTO `` (`idDispositivo`,`Nombre`,`Tipo`,`Marca`,`HoraDescarga`) VALUES (694,'Apple AirPods','Earbuds','Apple',3);
INSERT INTO `` (`idDispositivo`,`Nombre`,`Tipo`,`Marca`,`HoraDescarga`) VALUES (695,'Sony Xperia 1 III','Mobile Phone','Sony',0);
INSERT INTO `` (`idDispositivo`,`Nombre`,`Tipo`,`Marca`,`HoraDescarga`) VALUES (696,'Apple TV','Casting Device','Apple',4);
INSERT INTO `` (`idDispositivo`,`Nombre`,`Tipo`,`Marca`,`HoraDescarga`) VALUES (698,'Sony Xperia Tablet','Tablet','Sony',0);
INSERT INTO `` (`idDispositivo`,`Nombre`,`Tipo`,`Marca`,`HoraDescarga`) VALUES (703,'Google Home Mini','Smart Speaker','Google',3);
INSERT INTO `` (`idDispositivo`,`Nombre`,`Tipo`,`Marca`,`HoraDescarga`) VALUES (706,'Huawei MateBook X Pro','Laptop','Huawei',3);
INSERT INTO `` (`idDispositivo`,`Nombre`,`Tipo`,`Marca`,`HoraDescarga`) VALUES (708,'Samsung Galaxy S21','Mobile Phone','Samsung',1);
INSERT INTO `` (`idDispositivo`,`Nombre`,`Tipo`,`Marca`,`HoraDescarga`) VALUES (711,'Dell Ultrasharp Monitor','Monitor','Dell',1);
INSERT INTO `` (`idDispositivo`,`Nombre`,`Tipo`,`Marca`,`HoraDescarga`) VALUES (725,'Sony Xperia 1 III','Mobile Phone','Sony',3);
INSERT INTO `` (`idDispositivo`,`Nombre`,`Tipo`,`Marca`,`HoraDescarga`) VALUES (726,'Google Pixel Slate','Tablet','Google',0);
INSERT INTO `` (`idDispositivo`,`Nombre`,`Tipo`,`Marca`,`HoraDescarga`) VALUES (727,'Google Pixel Slate','Tablet','Google',2);
INSERT INTO `` (`idDispositivo`,`Nombre`,`Tipo`,`Marca`,`HoraDescarga`) VALUES (728,'Huawei MediaPad','Tablet','Huawei',2);
INSERT INTO `` (`idDispositivo`,`Nombre`,`Tipo`,`Marca`,`HoraDescarga`) VALUES (737,'Sonos One Smart Speaker','Smart Speaker','Sonos',2);
INSERT INTO `` (`idDispositivo`,`Nombre`,`Tipo`,`Marca`,`HoraDescarga`) VALUES (740,'LG G Pad','Tablet','LG',0);
INSERT INTO `` (`idDispositivo`,`Nombre`,`Tipo`,`Marca`,`HoraDescarga`) VALUES (751,'Apple iPhone SE','Mobile Phone','Apple',0);
INSERT INTO `` (`idDispositivo`,`Nombre`,`Tipo`,`Marca`,`HoraDescarga`) VALUES (754,'Google Chromecast','Casting Device','Google',2);
INSERT INTO `` (`idDispositivo`,`Nombre`,`Tipo`,`Marca`,`HoraDescarga`) VALUES (756,'Samsung Galaxy Tab','Tablet','Samsung',2);
INSERT INTO `` (`idDispositivo`,`Nombre`,`Tipo`,`Marca`,`HoraDescarga`) VALUES (763,'Apple iMac','Desktop Computer','Apple',3);
INSERT INTO `` (`idDispositivo`,`Nombre`,`Tipo`,`Marca`,`HoraDescarga`) VALUES (766,'LG XBOOM Go Portable Speaker','Portable Speaker','LG',1);
INSERT INTO `` (`idDispositivo`,`Nombre`,`Tipo`,`Marca`,`HoraDescarga`) VALUES (767,'Google Pixel 5','Mobile Phone','Google',1);
INSERT INTO `` (`idDispositivo`,`Nombre`,`Tipo`,`Marca`,`HoraDescarga`) VALUES (781,'Sony Xperia 5 II','Mobile Phone','Sony',0);
INSERT INTO `` (`idDispositivo`,`Nombre`,`Tipo`,`Marca`,`HoraDescarga`) VALUES (783,'Sony Blu-ray Disc Player','Blu-ray Player','Sony',2);
INSERT INTO `` (`idDispositivo`,`Nombre`,`Tipo`,`Marca`,`HoraDescarga`) VALUES (795,'Dell Ultrasharp Monitor','Monitor','Dell',0);
INSERT INTO `` (`idDispositivo`,`Nombre`,`Tipo`,`Marca`,`HoraDescarga`) VALUES (798,'Bose SoundLink Bluetooth Speaker','Portable Speaker','Bose',3);
INSERT INTO `` (`idDispositivo`,`Nombre`,`Tipo`,`Marca`,`HoraDescarga`) VALUES (800,'Sony Xperia Tablet','Tablet','Sony',0);
INSERT INTO `` (`idDispositivo`,`Nombre`,`Tipo`,`Marca`,`HoraDescarga`) VALUES (803,'Samsung Galaxy Book Flex','Laptop','Samsung',1);
INSERT INTO `` (`idDispositivo`,`Nombre`,`Tipo`,`Marca`,`HoraDescarga`) VALUES (805,'Apple iPhone 12','Mobile Phone','Apple',1);
INSERT INTO `` (`idDispositivo`,`Nombre`,`Tipo`,`Marca`,`HoraDescarga`) VALUES (809,'Samsung Galaxy Tab S','Tablet','Samsung',0);
INSERT INTO `` (`idDispositivo`,`Nombre`,`Tipo`,`Marca`,`HoraDescarga`) VALUES (810,'LG Gram Laptop','Laptop','LG',1);
INSERT INTO `` (`idDispositivo`,`Nombre`,`Tipo`,`Marca`,`HoraDescarga`) VALUES (811,'Google Pixelbook Go','Laptop','Google',1);
INSERT INTO `` (`idDispositivo`,`Nombre`,`Tipo`,`Marca`,`HoraDescarga`) VALUES (815,'Samsung Odyssey Gaming Monitor','Monitor','Samsung',2);
INSERT INTO `` (`idDispositivo`,`Nombre`,`Tipo`,`Marca`,`HoraDescarga`) VALUES (819,'JBL Link Bar','Soundbar with Android TV','JBL',1);
INSERT INTO `` (`idDispositivo`,`Nombre`,`Tipo`,`Marca`,`HoraDescarga`) VALUES (824,'Roku Streaming Stick','Casting Device','Roku',4);
INSERT INTO `` (`idDispositivo`,`Nombre`,`Tipo`,`Marca`,`HoraDescarga`) VALUES (827,'Amazon Fire TV Stick','Casting Device','Amazon',1);
INSERT INTO `` (`idDispositivo`,`Nombre`,`Tipo`,`Marca`,`HoraDescarga`) VALUES (833,'Samsung Galaxy Note 20','Mobile Phone','Samsung',0);
INSERT INTO `` (`idDispositivo`,`Nombre`,`Tipo`,`Marca`,`HoraDescarga`) VALUES (834,'Google Pixel 4a','Mobile Phone','Google',1);
INSERT INTO `` (`idDispositivo`,`Nombre`,`Tipo`,`Marca`,`HoraDescarga`) VALUES (838,'LG Smart TV','TV','LG',4);
INSERT INTO `` (`idDispositivo`,`Nombre`,`Tipo`,`Marca`,`HoraDescarga`) VALUES (839,'Microsoft Surface Pro','Tablet/Laptop','Microsoft',1);
INSERT INTO `` (`idDispositivo`,`Nombre`,`Tipo`,`Marca`,`HoraDescarga`) VALUES (841,'LG G Pad 5','Tablet','LG',0);
INSERT INTO `` (`idDispositivo`,`Nombre`,`Tipo`,`Marca`,`HoraDescarga`) VALUES (842,'Amazon Fire TV Stick','Casting Device','Amazon',2);
INSERT INTO `` (`idDispositivo`,`Nombre`,`Tipo`,`Marca`,`HoraDescarga`) VALUES (850,'Samsung Galaxy Book Flex','Laptop','Samsung',1);
INSERT INTO `` (`idDispositivo`,`Nombre`,`Tipo`,`Marca`,`HoraDescarga`) VALUES (854,'LG K42','Mobile Phone','LG',3);
INSERT INTO `` (`idDispositivo`,`Nombre`,`Tipo`,`Marca`,`HoraDescarga`) VALUES (859,'Google Pixelbook Go','Laptop','Google',1);
INSERT INTO `` (`idDispositivo`,`Nombre`,`Tipo`,`Marca`,`HoraDescarga`) VALUES (862,'Microsoft Surface Laptop','Laptop','Microsoft',2);
INSERT INTO `` (`idDispositivo`,`Nombre`,`Tipo`,`Marca`,`HoraDescarga`) VALUES (863,'OnePlus Nord','Mobile Phone','OnePlus',2);
INSERT INTO `` (`idDispositivo`,`Nombre`,`Tipo`,`Marca`,`HoraDescarga`) VALUES (866,'Dell Ultrasharp Monitor','Monitor','Dell',2);
INSERT INTO `` (`idDispositivo`,`Nombre`,`Tipo`,`Marca`,`HoraDescarga`) VALUES (867,'Samsung Galaxy Note 20','Mobile Phone','Samsung',1);
INSERT INTO `` (`idDispositivo`,`Nombre`,`Tipo`,`Marca`,`HoraDescarga`) VALUES (869,'JBL Free True Wireless Earbuds','Earbuds','JBL',3);
INSERT INTO `` (`idDispositivo`,`Nombre`,`Tipo`,`Marca`,`HoraDescarga`) VALUES (871,'Sonos One Smart Speaker','Smart Speaker','Sonos',4);
INSERT INTO `` (`idDispositivo`,`Nombre`,`Tipo`,`Marca`,`HoraDescarga`) VALUES (876,'Lenovo Yoga Laptop','Laptop','Lenovo',1);
INSERT INTO `` (`idDispositivo`,`Nombre`,`Tipo`,`Marca`,`HoraDescarga`) VALUES (892,'Apple MacBook Pro','Laptop','Apple',2);
INSERT INTO `` (`idDispositivo`,`Nombre`,`Tipo`,`Marca`,`HoraDescarga`) VALUES (894,'LG Velvet','Mobile Phone','LG',0);
INSERT INTO `` (`idDispositivo`,`Nombre`,`Tipo`,`Marca`,`HoraDescarga`) VALUES (896,'Samsung Galaxy A52','Mobile Phone','Samsung',1);
INSERT INTO `` (`idDispositivo`,`Nombre`,`Tipo`,`Marca`,`HoraDescarga`) VALUES (897,'LG Velvet','Mobile Phone','LG',3);
INSERT INTO `` (`idDispositivo`,`Nombre`,`Tipo`,`Marca`,`HoraDescarga`) VALUES (902,'Sony Xperia Tablet','Tablet','Sony',1);
INSERT INTO `` (`idDispositivo`,`Nombre`,`Tipo`,`Marca`,`HoraDescarga`) VALUES (904,'Google Pixel 4a','Mobile Phone','Google',2);
INSERT INTO `` (`idDispositivo`,`Nombre`,`Tipo`,`Marca`,`HoraDescarga`) VALUES (907,'Apple TV','Casting Device','Apple',0);
INSERT INTO `` (`idDispositivo`,`Nombre`,`Tipo`,`Marca`,`HoraDescarga`) VALUES (914,'Samsung Galaxy S21','Mobile Phone','Samsung',0);
INSERT INTO `` (`idDispositivo`,`Nombre`,`Tipo`,`Marca`,`HoraDescarga`) VALUES (920,'Apple iPhone','Mobile Phone','Apple',1);
INSERT INTO `` (`idDispositivo`,`Nombre`,`Tipo`,`Marca`,`HoraDescarga`) VALUES (928,'Apple iPad','Tablet','Apple',0);
INSERT INTO `` (`idDispositivo`,`Nombre`,`Tipo`,`Marca`,`HoraDescarga`) VALUES (932,'LG XBOOM Go','Portable Speaker','LG',3);
INSERT INTO `` (`idDispositivo`,`Nombre`,`Tipo`,`Marca`,`HoraDescarga`) VALUES (933,'Dell XPS Laptop','Laptop','Dell',2);
INSERT INTO `` (`idDispositivo`,`Nombre`,`Tipo`,`Marca`,`HoraDescarga`) VALUES (938,'Samsung Galaxy S21','Mobile Phone','Samsung',0);
INSERT INTO `` (`idDispositivo`,`Nombre`,`Tipo`,`Marca`,`HoraDescarga`) VALUES (949,'Dell Ultrasharp Monitor','Monitor','Dell',1);
INSERT INTO `` (`idDispositivo`,`Nombre`,`Tipo`,`Marca`,`HoraDescarga`) VALUES (951,'Microsoft Surface Laptop','Laptop','Microsoft',3);
INSERT INTO `` (`idDispositivo`,`Nombre`,`Tipo`,`Marca`,`HoraDescarga`) VALUES (957,'Apple AirPods','Earbuds','Apple',0);
INSERT INTO `` (`idDispositivo`,`Nombre`,`Tipo`,`Marca`,`HoraDescarga`) VALUES (959,'LG UHD TV','TV','LG',1);
INSERT INTO `` (`idDispositivo`,`Nombre`,`Tipo`,`Marca`,`HoraDescarga`) VALUES (960,'HP Spectre x360','Laptop','HP',1);
INSERT INTO `` (`idDispositivo`,`Nombre`,`Tipo`,`Marca`,`HoraDescarga`) VALUES (963,'Apple iPhone','Mobile Phone','Apple',1);
INSERT INTO `` (`idDispositivo`,`Nombre`,`Tipo`,`Marca`,`HoraDescarga`) VALUES (969,'Google Pixelbook','Laptop','Google',1);
INSERT INTO `` (`idDispositivo`,`Nombre`,`Tipo`,`Marca`,`HoraDescarga`) VALUES (974,'Google Pixel 5','Mobile Phone','Google',3);
INSERT INTO `` (`idDispositivo`,`Nombre`,`Tipo`,`Marca`,`HoraDescarga`) VALUES (976,'LG UHD TV','TV','LG',3);
INSERT INTO `` (`idDispositivo`,`Nombre`,`Tipo`,`Marca`,`HoraDescarga`) VALUES (977,'Sennheiser Momentum Wireless Headphones','Headphones','Sennheiser',1);
INSERT INTO `` (`idDispositivo`,`Nombre`,`Tipo`,`Marca`,`HoraDescarga`) VALUES (978,'Sennheiser Momentum Wireless Headphones','Headphones','Sennheiser',2);
INSERT INTO `` (`idDispositivo`,`Nombre`,`Tipo`,`Marca`,`HoraDescarga`) VALUES (982,'Google Nest Hub','Smart Display','Google',1);
INSERT INTO `` (`idDispositivo`,`Nombre`,`Tipo`,`Marca`,`HoraDescarga`) VALUES (983,'Microsoft Surface Pro','Tablet/Laptop','Microsoft',0);
INSERT INTO `` (`idDispositivo`,`Nombre`,`Tipo`,`Marca`,`HoraDescarga`) VALUES (984,'Sony WF-1000XM4 True Wireless Earbuds','Earbuds','Sony',2);
INSERT INTO `` (`idDispositivo`,`Nombre`,`Tipo`,`Marca`,`HoraDescarga`) VALUES (988,'Sennheiser Momentum Wireless Headphones','Headphones','Sennheiser',3);
INSERT INTO `` (`idDispositivo`,`Nombre`,`Tipo`,`Marca`,`HoraDescarga`) VALUES (990,'OnePlus Nord','Mobile Phone','OnePlus',3);
INSERT INTO `` (`idDispositivo`,`Nombre`,`Tipo`,`Marca`,`HoraDescarga`) VALUES (998,'Amazon Fire Tablet','Tablet','Amazon',1);
INSERT INTO `` (`idDispositivo`,`Nombre`,`Tipo`,`Marca`,`HoraDescarga`) VALUES (999,'Apple iPad','Tablet','Apple',3);
INSERT INTO `` (`idDispositivo`,`Nombre`,`Tipo`,`Marca`,`HoraDescarga`) VALUES (1001,'Apple iPhone 12','Mobile Phone','Apple',3);
INSERT INTO `` (`idDispositivo`,`Nombre`,`Tipo`,`Marca`,`HoraDescarga`) VALUES (1002,'JBL Free True Wireless Earbuds','Earbuds','JBL',2);
INSERT INTO `` (`idDispositivo`,`Nombre`,`Tipo`,`Marca`,`HoraDescarga`) VALUES (1003,'LG OLED TV','TV','LG',3);
INSERT INTO `` (`idDispositivo`,`Nombre`,`Tipo`,`Marca`,`HoraDescarga`) VALUES (1005,'Amazon Fire Tablet','Tablet','Amazon',4);
INSERT INTO `` (`idDispositivo`,`Nombre`,`Tipo`,`Marca`,`HoraDescarga`) VALUES (1009,'Samsung Odyssey Gaming Monitor','Monitor','Samsung',3);
INSERT INTO `` (`idDispositivo`,`Nombre`,`Tipo`,`Marca`,`HoraDescarga`) VALUES (1011,'LG Soundbar with Chromecast','Soundbar','LG',2);
INSERT INTO `` (`idDispositivo`,`Nombre`,`Tipo`,`Marca`,`HoraDescarga`) VALUES (1013,'Google Nest Mini','Smart Speaker','Google',1);
INSERT INTO `` (`idDispositivo`,`Nombre`,`Tipo`,`Marca`,`HoraDescarga`) VALUES (1014,'Microsoft Xbox One','Gaming Console','Microsoft',2);
INSERT INTO `` (`idDispositivo`,`Nombre`,`Tipo`,`Marca`,`HoraDescarga`) VALUES (1019,'OnePlus Nord','Mobile Phone','OnePlus',4);
INSERT INTO `` (`idDispositivo`,`Nombre`,`Tipo`,`Marca`,`HoraDescarga`) VALUES (1024,'Samsung Smart TV','TV','Samsung',3);
INSERT INTO `` (`idDispositivo`,`Nombre`,`Tipo`,`Marca`,`HoraDescarga`) VALUES (1029,'Samsung Blu-ray Disc Player','Blu-ray Player','Samsung',1);
INSERT INTO `` (`idDispositivo`,`Nombre`,`Tipo`,`Marca`,`HoraDescarga`) VALUES (1039,'LG XBOOM Go Portable Speaker','Portable Speaker','LG',2);
INSERT INTO `` (`idDispositivo`,`Nombre`,`Tipo`,`Marca`,`HoraDescarga`) VALUES (1040,'Dell XPS Laptop','Laptop','Dell',2);
INSERT INTO `` (`idDispositivo`,`Nombre`,`Tipo`,`Marca`,`HoraDescarga`) VALUES (1041,'Sony PlayStation 4','Gaming Console','Sony',4);
INSERT INTO `` (`idDispositivo`,`Nombre`,`Tipo`,`Marca`,`HoraDescarga`) VALUES (1042,'Microsoft Surface Laptop','Laptop','Microsoft',0);
INSERT INTO `` (`idDispositivo`,`Nombre`,`Tipo`,`Marca`,`HoraDescarga`) VALUES (1048,'Roku Smart Soundbar','Soundbar','Roku',0);
INSERT INTO `` (`idDispositivo`,`Nombre`,`Tipo`,`Marca`,`HoraDescarga`) VALUES (1051,'TCL Roku TV','TV','TCL',0);
INSERT INTO `` (`idDispositivo`,`Nombre`,`Tipo`,`Marca`,`HoraDescarga`) VALUES (1059,'Sony WH-1000XM4 Headphones','Headphones','Sony',1);
INSERT INTO `` (`idDispositivo`,`Nombre`,`Tipo`,`Marca`,`HoraDescarga`) VALUES (1071,'Huawei MediaPad M5','Tablet','Huawei',1);
INSERT INTO `` (`idDispositivo`,`Nombre`,`Tipo`,`Marca`,`HoraDescarga`) VALUES (1073,'Samsung Galaxy Watch','Smartwatch','Samsung',3);
INSERT INTO `` (`idDispositivo`,`Nombre`,`Tipo`,`Marca`,`HoraDescarga`) VALUES (1076,'Apple MacBook Pro','Laptop','Apple',1);
INSERT INTO `` (`idDispositivo`,`Nombre`,`Tipo`,`Marca`,`HoraDescarga`) VALUES (1086,'Sennheiser Momentum Wireless Headphones','Headphones','Sennheiser',1);
INSERT INTO `` (`idDispositivo`,`Nombre`,`Tipo`,`Marca`,`HoraDescarga`) VALUES (1089,'Sony WH-1000XM4 Headphones','Headphones','Sony',2);
INSERT INTO `` (`idDispositivo`,`Nombre`,`Tipo`,`Marca`,`HoraDescarga`) VALUES (1096,'Apple iPad','Tablet','Apple',0);
INSERT INTO `` (`idDispositivo`,`Nombre`,`Tipo`,`Marca`,`HoraDescarga`) VALUES (1100,'Bose QuietComfort Headphones','Headphones','Bose',2);
INSERT INTO `` (`idDispositivo`,`Nombre`,`Tipo`,`Marca`,`HoraDescarga`) VALUES (1106,'Samsung Smart TV','TV','Samsung',0);
INSERT INTO `` (`idDispositivo`,`Nombre`,`Tipo`,`Marca`,`HoraDescarga`) VALUES (1107,'Huawei MateBook','Laptop','Huawei',1);
INSERT INTO `` (`idDispositivo`,`Nombre`,`Tipo`,`Marca`,`HoraDescarga`) VALUES (1108,'Microsoft Surface Go','Tablet','Microsoft',0);
INSERT INTO `` (`idDispositivo`,`Nombre`,`Tipo`,`Marca`,`HoraDescarga`) VALUES (1112,'Lenovo Yoga Laptop','Laptop','Lenovo',1);
INSERT INTO `` (`idDispositivo`,`Nombre`,`Tipo`,`Marca`,`HoraDescarga`) VALUES (1113,'Amazon Echo Dot','Smart Speaker','Amazon',4);
INSERT INTO `` (`idDispositivo`,`Nombre`,`Tipo`,`Marca`,`HoraDescarga`) VALUES (1114,'Sony Xperia','Mobile Phone','Sony',3);
INSERT INTO `` (`idDispositivo`,`Nombre`,`Tipo`,`Marca`,`HoraDescarga`) VALUES (1115,'Sony PlayStation 4','Gaming Console','Sony',3);
INSERT INTO `` (`idDispositivo`,`Nombre`,`Tipo`,`Marca`,`HoraDescarga`) VALUES (1122,'JBL Flip Portable Bluetooth Speaker','Portable Speaker','JBL',3);
INSERT INTO `` (`idDispositivo`,`Nombre`,`Tipo`,`Marca`,`HoraDescarga`) VALUES (1128,'LG Gram Laptop','Laptop','LG',0);
INSERT INTO `` (`idDispositivo`,`Nombre`,`Tipo`,`Marca`,`HoraDescarga`) VALUES (1134,'Apple MacBook Pro','Laptop','Apple',1);
INSERT INTO `` (`idDispositivo`,`Nombre`,`Tipo`,`Marca`,`HoraDescarga`) VALUES (1144,'LG OLED TV','TV','LG',3);
INSERT INTO `` (`idDispositivo`,`Nombre`,`Tipo`,`Marca`,`HoraDescarga`) VALUES (1152,'LG Velvet','Mobile Phone','LG',1);
INSERT INTO `` (`idDispositivo`,`Nombre`,`Tipo`,`Marca`,`HoraDescarga`) VALUES (1154,'Sony Xperia 5 II','Mobile Phone','Sony',0);
INSERT INTO `` (`idDispositivo`,`Nombre`,`Tipo`,`Marca`,`HoraDescarga`) VALUES (1156,'Bose SoundLink Bluetooth Speaker','Portable Speaker','Bose',4);
INSERT INTO `` (`idDispositivo`,`Nombre`,`Tipo`,`Marca`,`HoraDescarga`) VALUES (1161,'LG XBOOM Go','Portable Speaker','LG',2);
INSERT INTO `` (`idDispositivo`,`Nombre`,`Tipo`,`Marca`,`HoraDescarga`) VALUES (1162,'Microsoft Surface Laptop','Laptop','Microsoft',1);
INSERT INTO `` (`idDispositivo`,`Nombre`,`Tipo`,`Marca`,`HoraDescarga`) VALUES (1163,'TCL Smart TV','TV','TCL',1);
INSERT INTO `` (`idDispositivo`,`Nombre`,`Tipo`,`Marca`,`HoraDescarga`) VALUES (1166,'Apple iPhone SE','Mobile Phone','Apple',3);
INSERT INTO `` (`idDispositivo`,`Nombre`,`Tipo`,`Marca`,`HoraDescarga`) VALUES (1176,'Samsung Odyssey Gaming Monitor','Monitor','Samsung',0);
INSERT INTO `` (`idDispositivo`,`Nombre`,`Tipo`,`Marca`,`HoraDescarga`) VALUES (1179,'Sony PlayStation 4','Gaming Console','Sony',0);
INSERT INTO `` (`idDispositivo`,`Nombre`,`Tipo`,`Marca`,`HoraDescarga`) VALUES (1181,'Sony Xperia 5 II','Mobile Phone','Sony',4);
INSERT INTO `` (`idDispositivo`,`Nombre`,`Tipo`,`Marca`,`HoraDescarga`) VALUES (1182,'Amazon Fire TV Stick','Casting Device','Amazon',2);
INSERT INTO `` (`idDispositivo`,`Nombre`,`Tipo`,`Marca`,`HoraDescarga`) VALUES (1185,'Samsung Galaxy Watch Active','Smartwatch','Samsung',2);
INSERT INTO `` (`idDispositivo`,`Nombre`,`Tipo`,`Marca`,`HoraDescarga`) VALUES (1189,'Sony WF-1000XM4 True Wireless Earbuds','Earbuds','Sony',3);
INSERT INTO `` (`idDispositivo`,`Nombre`,`Tipo`,`Marca`,`HoraDescarga`) VALUES (1190,'Google Chromecast','Casting Device','Google',4);
INSERT INTO `` (`idDispositivo`,`Nombre`,`Tipo`,`Marca`,`HoraDescarga`) VALUES (1192,'Samsung Galaxy Tab S7','Tablet','Samsung',0);
INSERT INTO `` (`idDispositivo`,`Nombre`,`Tipo`,`Marca`,`HoraDescarga`) VALUES (1193,'Dell XPS Laptop','Laptop','Dell',1);
INSERT INTO `` (`idDispositivo`,`Nombre`,`Tipo`,`Marca`,`HoraDescarga`) VALUES (1194,'Samsung Galaxy Book Flex','Laptop','Samsung',0);
INSERT INTO `` (`idDispositivo`,`Nombre`,`Tipo`,`Marca`,`HoraDescarga`) VALUES (1196,'Amazon Echo Show','Smart Display','Amazon',1);
INSERT INTO `` (`idDispositivo`,`Nombre`,`Tipo`,`Marca`,`HoraDescarga`) VALUES (1197,'Sony Xperia 1 III','Mobile Phone','Sony',3);
INSERT INTO `` (`idDispositivo`,`Nombre`,`Tipo`,`Marca`,`HoraDescarga`) VALUES (1198,'Google Pixel','Mobile Phone','Google',1);
INSERT INTO `` (`idDispositivo`,`Nombre`,`Tipo`,`Marca`,`HoraDescarga`) VALUES (1207,'Apple MacBook Pro','Laptop','Apple',1);
INSERT INTO `` (`idDispositivo`,`Nombre`,`Tipo`,`Marca`,`HoraDescarga`) VALUES (1208,'LG Soundbar with Chromecast','Soundbar','LG',3);
INSERT INTO `` (`idDispositivo`,`Nombre`,`Tipo`,`Marca`,`HoraDescarga`) VALUES (1212,'JBL Free True Wireless Earbuds','Earbuds','JBL',2);
INSERT INTO `` (`idDispositivo`,`Nombre`,`Tipo`,`Marca`,`HoraDescarga`) VALUES (1216,'Sony Xperia 1 III','Mobile Phone','Sony',1);
INSERT INTO `` (`idDispositivo`,`Nombre`,`Tipo`,`Marca`,`HoraDescarga`) VALUES (1227,'Samsung Galaxy A','Mobile Phone','Samsung',2);
INSERT INTO `` (`idDispositivo`,`Nombre`,`Tipo`,`Marca`,`HoraDescarga`) VALUES (1228,'Sony SmartWatch','Smartwatch','Sony',0);
INSERT INTO `` (`idDispositivo`,`Nombre`,`Tipo`,`Marca`,`HoraDescarga`) VALUES (1239,'Amazon Echo Show','Smart Display','Amazon',2);
INSERT INTO `` (`idDispositivo`,`Nombre`,`Tipo`,`Marca`,`HoraDescarga`) VALUES (1241,'Samsung Galaxy S','Mobile Phone','Samsung',0);
INSERT INTO `` (`idDispositivo`,`Nombre`,`Tipo`,`Marca`,`HoraDescarga`) VALUES (1247,'Samsung Odyssey Gaming Monitor','Monitor','Samsung',2);
INSERT INTO `` (`idDispositivo`,`Nombre`,`Tipo`,`Marca`,`HoraDescarga`) VALUES (1248,'Samsung Galaxy Tab S','Tablet','Samsung',0);
