/*
-- Query: SELECT * FROM tp_bd_2023.premios
LIMIT 0, 1000

-- Date: 2023-06-01 21:05
*/
INSERT INTO `` (`TitIngles`,`Premios`,`Festival`,`Ano`) VALUES ('Saving Private Ryan','Best Actress','Cannes Film Festival',2007);
INSERT INTO `` (`TitIngles`,`Premios`,`Festival`,`Ano`) VALUES ('The Princess Bride','Best Adapted Screenplay','Sundance Film Festival',2019);
INSERT INTO `` (`TitIngles`,`Premios`,`Festival`,`Ano`) VALUES ('The Lion King II: Simba\'s Pride','Best Visual Effects','Venice Film Festival',2010);
INSERT INTO `` (`TitIngles`,`Premios`,`Festival`,`Ano`) VALUES ('Mulan','Best Actress','Berlin International Film Festival',2017);
INSERT INTO `` (`TitIngles`,`Premios`,`Festival`,`Ano`) VALUES ('The Social Network','Best Visual Effects','Toronto International Film Festival',2002);
INSERT INTO `` (`TitIngles`,`Premios`,`Festival`,`Ano`) VALUES ('Gone with the Wind','Best Actress','Tribeca Film Festival',2021);
INSERT INTO `` (`TitIngles`,`Premios`,`Festival`,`Ano`) VALUES ('The Lord of the Rings: The Fellowship of the Ring','Best Original Screenplay','BFI London Film Festival',2016);
INSERT INTO `` (`TitIngles`,`Premios`,`Festival`,`Ano`) VALUES ('The Breakfast Club','Best Actress','SXSW Film Festival',2013);
INSERT INTO `` (`TitIngles`,`Premios`,`Festival`,`Ano`) VALUES ('Pulp Fiction','Best Actor','Tokyo International Film Festival',2005);
INSERT INTO `` (`TitIngles`,`Premios`,`Festival`,`Ano`) VALUES ('The Sixth Sense','Best Actor','Busan International Film Festival',2022);
INSERT INTO `` (`TitIngles`,`Premios`,`Festival`,`Ano`) VALUES ('2001: A Space Odyssey','Best Actress','Sydney Film Festival',2014);
INSERT INTO `` (`TitIngles`,`Premios`,`Festival`,`Ano`) VALUES ('Titanic','Best Cinematography','Shanghai International Film Festival',2006);
INSERT INTO `` (`TitIngles`,`Premios`,`Festival`,`Ano`) VALUES ('Star Wars: Episode IV - A New Hope','Best Supporting Actor','Moscow International Film Festival',2020);
INSERT INTO `` (`TitIngles`,`Premios`,`Festival`,`Ano`) VALUES ('The Hateful Eight','Best Supporting Actor','Karlovy Vary International Film Festival',2012);
INSERT INTO `` (`TitIngles`,`Premios`,`Festival`,`Ano`) VALUES ('Star Wars: Episode I - The Phantom Menace','Best Actress','Locarno Film Festival',2018);
INSERT INTO `` (`TitIngles`,`Premios`,`Festival`,`Ano`) VALUES ('The Lord of the Rings: The Return of the King','Best Visual Effects','Palm Springs International Film Festival',2015);
INSERT INTO `` (`TitIngles`,`Premios`,`Festival`,`Ano`) VALUES ('Star Wars: Episode II - Attack of the Clones','Best Visual Effects','San SebastiÃ¡n International Film Festival',2011);
INSERT INTO `` (`TitIngles`,`Premios`,`Festival`,`Ano`) VALUES ('The Matrix','Best Cinematography','Cairo International Film Festival',2009);
INSERT INTO `` (`TitIngles`,`Premios`,`Festival`,`Ano`) VALUES ('The Iron Giant','Best Director','Mar del Plata International Film Festival',2004);
INSERT INTO `` (`TitIngles`,`Premios`,`Festival`,`Ano`) VALUES ('Aladdin','Best Supporting Actor','Mumbai Film Festival (MAMI)',2003);
INSERT INTO `` (`TitIngles`,`Premios`,`Festival`,`Ano`) VALUES ('Star Wars: Episode III - Revenge of the Sith','Best Supporting Actor','Cannes Film Festival',2001);
INSERT INTO `` (`TitIngles`,`Premios`,`Festival`,`Ano`) VALUES ('The Exorcist','Best Picture','Sundance Film Festival',2008);
INSERT INTO `` (`TitIngles`,`Premios`,`Festival`,`Ano`) VALUES ('Goodfellas','Best Actor','Berlin International Film Festival',2023);
INSERT INTO `` (`TitIngles`,`Premios`,`Festival`,`Ano`) VALUES ('Django Unchained','Best Visual Effects','Toronto International Film Festival',2017);
INSERT INTO `` (`TitIngles`,`Premios`,`Festival`,`Ano`) VALUES ('Nemo','Best Picture','Tribeca Film Festival',2002);
INSERT INTO `` (`TitIngles`,`Premios`,`Festival`,`Ano`) VALUES ('The Little Mermaid','Best Visual Effects','BFI London Film Festival',2022);
INSERT INTO `` (`TitIngles`,`Premios`,`Festival`,`Ano`) VALUES ('The Others','Best Supporting Actress','SXSW Film Festival',2010);
INSERT INTO `` (`TitIngles`,`Premios`,`Festival`,`Ano`) VALUES ('Signs','Best Director','Tokyo International Film Festival',2014);
INSERT INTO `` (`TitIngles`,`Premios`,`Festival`,`Ano`) VALUES ('The Shawshank Redemption','Best Director','Busan International Film Festival',2006);
INSERT INTO `` (`TitIngles`,`Premios`,`Festival`,`Ano`) VALUES ('Toy Story','Best Director','Sydney Film Festival',2015);
INSERT INTO `` (`TitIngles`,`Premios`,`Festival`,`Ano`) VALUES ('The Silence of the Lambs','Best Original Screenplay','Shanghai International Film Festival',2019);
INSERT INTO `` (`TitIngles`,`Premios`,`Festival`,`Ano`) VALUES ('Star Wars: Episode V - The Empire Strikes Back','Best Picture','Moscow International Film Festival',2005);
INSERT INTO `` (`TitIngles`,`Premios`,`Festival`,`Ano`) VALUES ('Star Wars: Episode VI - Return of the Jedi','Best Director','Karlovy Vary International Film Festival',2018);
INSERT INTO `` (`TitIngles`,`Premios`,`Festival`,`Ano`) VALUES ('The Incredibles','Best Visual Effects','Locarno Film Festival',2016);
INSERT INTO `` (`TitIngles`,`Premios`,`Festival`,`Ano`) VALUES ('The Grand Budapest Hotel','Best Actor','Palm Springs International Film Festival',2011);
INSERT INTO `` (`TitIngles`,`Premios`,`Festival`,`Ano`) VALUES ('Jurassic Park','Best Cinematography','San SebastiÃ¡n International Film Festival',2007);
INSERT INTO `` (`TitIngles`,`Premios`,`Festival`,`Ano`) VALUES ('Harry Potter and the Goblet of Fire','Best Visual Effects','Cairo International Film Festival',2021);
INSERT INTO `` (`TitIngles`,`Premios`,`Festival`,`Ano`) VALUES ('The Godfather: Part III','Best Actor','Mar del Plata International Film Festival',2013);
INSERT INTO `` (`TitIngles`,`Premios`,`Festival`,`Ano`) VALUES ('The Truman Show','Best Cinematography','Mumbai Film Festival (MAMI)',2012);
INSERT INTO `` (`TitIngles`,`Premios`,`Festival`,`Ano`) VALUES ('The Godfather: Part II','Best Cinematography','Cannes Film Festival',2003);
INSERT INTO `` (`TitIngles`,`Premios`,`Festival`,`Ano`) VALUES ('The Wizard of Oz','Best Director','Sundance Film Festival',2001);
INSERT INTO `` (`TitIngles`,`Premios`,`Festival`,`Ano`) VALUES ('The Avengers','Best Cinematography','Venice Film Festival',2008);
INSERT INTO `` (`TitIngles`,`Premios`,`Festival`,`Ano`) VALUES ('Inside Out','Best Supporting Actor','Berlin International Film Festival',2020);
INSERT INTO `` (`TitIngles`,`Premios`,`Festival`,`Ano`) VALUES ('Captain America','Best Actor','Toronto International Film Festival',2000);
INSERT INTO `` (`TitIngles`,`Premios`,`Festival`,`Ano`) VALUES ('The Departed','Best Picture','Tribeca Film Festival',2023);
INSERT INTO `` (`TitIngles`,`Premios`,`Festival`,`Ano`) VALUES ('The Godfather','Best Supporting Actress','BFI London Film Festival',2009);
INSERT INTO `` (`TitIngles`,`Premios`,`Festival`,`Ano`) VALUES ('Harry Potter and the Order of the Phoenix','Best Visual Effects','SXSW Film Festival',2004);
INSERT INTO `` (`TitIngles`,`Premios`,`Festival`,`Ano`) VALUES ('Avengers: Endgame','Best Original Screenplay','Tokyo International Film Festival',2017);
INSERT INTO `` (`TitIngles`,`Premios`,`Festival`,`Ano`) VALUES ('Avengers: Infinity War','Best Cinematography','Busan International Film Festival',2010);
INSERT INTO `` (`TitIngles`,`Premios`,`Festival`,`Ano`) VALUES ('Saving Private Ryan','Best Original Screenplay','Sydney Film Festival',2021);
INSERT INTO `` (`TitIngles`,`Premios`,`Festival`,`Ano`) VALUES ('The Princess Bride','Best Picture','Shanghai International Film Festival',2002);
INSERT INTO `` (`TitIngles`,`Premios`,`Festival`,`Ano`) VALUES ('The Lion King II: Simba\'s Pride','Best Actor','Moscow International Film Festival',2016);
INSERT INTO `` (`TitIngles`,`Premios`,`Festival`,`Ano`) VALUES ('Pulp Fiction','Best Actress','Karlovy Vary International Film Festival',2013);
INSERT INTO `` (`TitIngles`,`Premios`,`Festival`,`Ano`) VALUES ('The Social Network','Best Actress','Locarno Film Festival',2006);
INSERT INTO `` (`TitIngles`,`Premios`,`Festival`,`Ano`) VALUES ('Gone with the Wind','Best Visual Effects','Palm Springs International Film Festival',2014);
INSERT INTO `` (`TitIngles`,`Premios`,`Festival`,`Ano`) VALUES ('The Breakfast Club','Best Cinematography','Cairo International Film Festival',2015);
INSERT INTO `` (`TitIngles`,`Premios`,`Festival`,`Ano`) VALUES ('Pulp Fiction','Best Supporting Actor','Mar del Plata International Film Festival',2000);
INSERT INTO `` (`TitIngles`,`Premios`,`Festival`,`Ano`) VALUES ('2001: A Space Odyssey','Best Picture','Cannes Film Festival',2011);
INSERT INTO `` (`TitIngles`,`Premios`,`Festival`,`Ano`) VALUES ('Titanic','Best Picture','Sundance Film Festival',2007);
INSERT INTO `` (`TitIngles`,`Premios`,`Festival`,`Ano`) VALUES ('Star Wars: Episode IV - A New Hope','Best Cinematography','Venice Film Festival',2022);
INSERT INTO `` (`TitIngles`,`Premios`,`Festival`,`Ano`) VALUES ('The Hateful Eight','Best Supporting Actress','Berlin International Film Festival',2008);
INSERT INTO `` (`TitIngles`,`Premios`,`Festival`,`Ano`) VALUES ('Star Wars: Episode I - The Phantom Menace','Best Actress','Toronto International Film Festival',2005);
INSERT INTO `` (`TitIngles`,`Premios`,`Festival`,`Ano`) VALUES ('The Lord of the Rings: The Return of the King','Best Director','Tribeca Film Festival',2003);
INSERT INTO `` (`TitIngles`,`Premios`,`Festival`,`Ano`) VALUES ('Star Wars: Episode II - Attack of the Clones','Best Adapted Screenplay','BFI London Film Festival',2020);
INSERT INTO `` (`TitIngles`,`Premios`,`Festival`,`Ano`) VALUES ('The Matrix','Best Adapted Screenplay','SXSW Film Festival',2019);
INSERT INTO `` (`TitIngles`,`Premios`,`Festival`,`Ano`) VALUES ('The Iron Giant','Best Adapted Screenplay','Tokyo International Film Festival',2016);
INSERT INTO `` (`TitIngles`,`Premios`,`Festival`,`Ano`) VALUES ('Aladdin','Best Original Screenplay','Busan International Film Festival',2014);
INSERT INTO `` (`TitIngles`,`Premios`,`Festival`,`Ano`) VALUES ('Star Wars: Episode III - Revenge of the Sith','Best Director','Sydney Film Festival',2010);
INSERT INTO `` (`TitIngles`,`Premios`,`Festival`,`Ano`) VALUES ('The Exorcist','Best Picture','Shanghai International Film Festival',2009);
INSERT INTO `` (`TitIngles`,`Premios`,`Festival`,`Ano`) VALUES ('Goodfellas','Best Supporting Actor','Karlovy Vary International Film Festival',2012);
INSERT INTO `` (`TitIngles`,`Premios`,`Festival`,`Ano`) VALUES ('Django Unchained','Best Director','Locarno Film Festival',2006);
INSERT INTO `` (`TitIngles`,`Premios`,`Festival`,`Ano`) VALUES ('Nemo','Best Actor','Palm Springs International Film Festival',2011);
INSERT INTO `` (`TitIngles`,`Premios`,`Festival`,`Ano`) VALUES ('The Little Mermaid','Best Adapted Screenplay','San SebastiÃ¡n International Film Festival',2004);
INSERT INTO `` (`TitIngles`,`Premios`,`Festival`,`Ano`) VALUES ('The Others','Best Picture','Cairo International Film Festival',2017);
INSERT INTO `` (`TitIngles`,`Premios`,`Festival`,`Ano`) VALUES ('Signs','Best Adapted Screenplay','Mar del Plata International Film Festival',2023);
INSERT INTO `` (`TitIngles`,`Premios`,`Festival`,`Ano`) VALUES ('The Shawshank Redemption','Best Supporting Actor','Mumbai Film Festival (MAMI)',2015);
INSERT INTO `` (`TitIngles`,`Premios`,`Festival`,`Ano`) VALUES ('Toy Story','Best Original Screenplay','Cannes Film Festival',2002);
INSERT INTO `` (`TitIngles`,`Premios`,`Festival`,`Ano`) VALUES ('The Silence of the Lambs','Best Director','Sundance Film Festival',2013);
INSERT INTO `` (`TitIngles`,`Premios`,`Festival`,`Ano`) VALUES ('Star Wars: Episode V - The Empire Strikes Back','Best Original Screenplay','Venice Film Festival',2007);
INSERT INTO `` (`TitIngles`,`Premios`,`Festival`,`Ano`) VALUES ('Star Wars: Episode VI - Return of the Jedi','Best Adapted Screenplay','Berlin International Film Festival',2021);
INSERT INTO `` (`TitIngles`,`Premios`,`Festival`,`Ano`) VALUES ('The Incredibles','Best Cinematography','Toronto International Film Festival',2005);
INSERT INTO `` (`TitIngles`,`Premios`,`Festival`,`Ano`) VALUES ('The Grand Budapest Hotel','Best Actress','Tribeca Film Festival',2019);
INSERT INTO `` (`TitIngles`,`Premios`,`Festival`,`Ano`) VALUES ('Jurassic Park','Best Original Screenplay','BFI London Film Festival',2000);
INSERT INTO `` (`TitIngles`,`Premios`,`Festival`,`Ano`) VALUES ('Harry Potter and the Goblet of Fire','Best Cinematography','SXSW Film Festival',2022);
INSERT INTO `` (`TitIngles`,`Premios`,`Festival`,`Ano`) VALUES ('The Godfather: Part III','Best Visual Effects','Tokyo International Film Festival',2008);
INSERT INTO `` (`TitIngles`,`Premios`,`Festival`,`Ano`) VALUES ('The Truman Show','Best Actress','Busan International Film Festival',2009);
INSERT INTO `` (`TitIngles`,`Premios`,`Festival`,`Ano`) VALUES ('The Godfather: Part II','Best Supporting Actress','Sydney Film Festival',2014);
INSERT INTO `` (`TitIngles`,`Premios`,`Festival`,`Ano`) VALUES ('The Wizard of Oz','Best Original Screenplay','Shanghai International Film Festival',2016);
INSERT INTO `` (`TitIngles`,`Premios`,`Festival`,`Ano`) VALUES ('The Avengers','Best Picture','Moscow International Film Festival',2011);
INSERT INTO `` (`TitIngles`,`Premios`,`Festival`,`Ano`) VALUES ('Inside Out','Best Original Screenplay','Karlovy Vary International Film Festival',2006);
INSERT INTO `` (`TitIngles`,`Premios`,`Festival`,`Ano`) VALUES ('Captain America','Best Director','Locarno Film Festival',2003);
INSERT INTO `` (`TitIngles`,`Premios`,`Festival`,`Ano`) VALUES ('The Departed','Best Actress','Palm Springs International Film Festival',2017);
INSERT INTO `` (`TitIngles`,`Premios`,`Festival`,`Ano`) VALUES ('The Godfather','Best Cinematography','San SebastiÃ¡n International Film Festival',2010);
INSERT INTO `` (`TitIngles`,`Premios`,`Festival`,`Ano`) VALUES ('Harry Potter and the Order of the Phoenix','Best Original Screenplay','Cairo International Film Festival',2018);
INSERT INTO `` (`TitIngles`,`Premios`,`Festival`,`Ano`) VALUES ('Avengers: Endgame','Best Supporting Actor','Mar del Plata International Film Festival',2002);
INSERT INTO `` (`TitIngles`,`Premios`,`Festival`,`Ano`) VALUES ('Avengers: Infinity War','Best Director','Mumbai Film Festival (MAMI)',2020);
INSERT INTO `` (`TitIngles`,`Premios`,`Festival`,`Ano`) VALUES ('Saving Private Ryan','Best Supporting Actress','Cannes Film Festival',2012);
INSERT INTO `` (`TitIngles`,`Premios`,`Festival`,`Ano`) VALUES ('The Princess Bride','Best Supporting Actress','Sundance Film Festival',2015);
INSERT INTO `` (`TitIngles`,`Premios`,`Festival`,`Ano`) VALUES ('The Lion King II: Simba\'s Pride','Best Director','Venice Film Festival',2004);
INSERT INTO `` (`TitIngles`,`Premios`,`Festival`,`Ano`) VALUES ('Mulan','Best Picture','Berlin International Film Festival',2001);
INSERT INTO `` (`TitIngles`,`Premios`,`Festival`,`Ano`) VALUES ('The Social Network','Best Adapted Screenplay','Toronto International Film Festival',2023);
INSERT INTO `` (`TitIngles`,`Premios`,`Festival`,`Ano`) VALUES ('Gone with the Wind','Best Director','Tribeca Film Festival',2007);
INSERT INTO `` (`TitIngles`,`Premios`,`Festival`,`Ano`) VALUES ('The Breakfast Club','Best Original Screenplay','SXSW Film Festival',2000);
INSERT INTO `` (`TitIngles`,`Premios`,`Festival`,`Ano`) VALUES ('Pulp Fiction','Best Director','Tokyo International Film Festival',2019);
INSERT INTO `` (`TitIngles`,`Premios`,`Festival`,`Ano`) VALUES ('The Sixth Sense','Best Supporting Actress','Busan International Film Festival',2014);
INSERT INTO `` (`TitIngles`,`Premios`,`Festival`,`Ano`) VALUES ('Star Wars: Episode IV - A New Hope','Best Visual Effects','Moscow International Film Festival',2022);
INSERT INTO `` (`TitIngles`,`Premios`,`Festival`,`Ano`) VALUES ('The Hateful Eight','Best Director','Karlovy Vary International Film Festival',2010);
INSERT INTO `` (`TitIngles`,`Premios`,`Festival`,`Ano`) VALUES ('Star Wars: Episode I - The Phantom Menace','Best Adapted Screenplay','Locarno Film Festival',2013);
INSERT INTO `` (`TitIngles`,`Premios`,`Festival`,`Ano`) VALUES ('The Lord of the Rings: The Return of the King','Best Actor','Palm Springs International Film Festival',2009);
INSERT INTO `` (`TitIngles`,`Premios`,`Festival`,`Ano`) VALUES ('Star Wars: Episode II - Attack of the Clones','Best Supporting Actor','San SebastiÃ¡n International Film Festival',2006);
INSERT INTO `` (`TitIngles`,`Premios`,`Festival`,`Ano`) VALUES ('The Matrix','Best Actor','Cairo International Film Festival',2003);
INSERT INTO `` (`TitIngles`,`Premios`,`Festival`,`Ano`) VALUES ('The Iron Giant','Best Adapted Screenplay','Mar del Plata International Film Festival',2017);
INSERT INTO `` (`TitIngles`,`Premios`,`Festival`,`Ano`) VALUES ('Aladdin','Best Actor','Mumbai Film Festival (MAMI)',2021);
INSERT INTO `` (`TitIngles`,`Premios`,`Festival`,`Ano`) VALUES ('Star Wars: Episode III - Revenge of the Sith','Best Adapted Screenplay','Cannes Film Festival',2018);
INSERT INTO `` (`TitIngles`,`Premios`,`Festival`,`Ano`) VALUES ('The Exorcist','Best Director','Sundance Film Festival',2002);
INSERT INTO `` (`TitIngles`,`Premios`,`Festival`,`Ano`) VALUES ('The Lord of the Rings: The Fellowship of the Ring','Best Actress','Venice Film Festival',2015);
INSERT INTO `` (`TitIngles`,`Premios`,`Festival`,`Ano`) VALUES ('Goodfellas','Best Cinematography','Berlin International Film Festival',2004);
INSERT INTO `` (`TitIngles`,`Premios`,`Festival`,`Ano`) VALUES ('Django Unchained','Best Actor','Toronto International Film Festival',2012);
INSERT INTO `` (`TitIngles`,`Premios`,`Festival`,`Ano`) VALUES ('Nemo','Best Supporting Actor','Tribeca Film Festival',2007);
INSERT INTO `` (`TitIngles`,`Premios`,`Festival`,`Ano`) VALUES ('The Little Mermaid','Best Cinematography','BFI London Film Festival',2019);
INSERT INTO `` (`TitIngles`,`Premios`,`Festival`,`Ano`) VALUES ('The Others','Best Original Screenplay','SXSW Film Festival',2010);
INSERT INTO `` (`TitIngles`,`Premios`,`Festival`,`Ano`) VALUES ('Signs','Best Cinematography','Tokyo International Film Festival',2017);
INSERT INTO `` (`TitIngles`,`Premios`,`Festival`,`Ano`) VALUES ('Toy Story','Best Actor','Sydney Film Festival',2021);
INSERT INTO `` (`TitIngles`,`Premios`,`Festival`,`Ano`) VALUES ('The Silence of the Lambs','Best Cinematography','Shanghai International Film Festival',2016);
INSERT INTO `` (`TitIngles`,`Premios`,`Festival`,`Ano`) VALUES ('Star Wars: Episode V - The Empire Strikes Back','Best Cinematography','Moscow International Film Festival',2013);
INSERT INTO `` (`TitIngles`,`Premios`,`Festival`,`Ano`) VALUES ('Star Wars: Episode VI - Return of the Jedi','Best Actor','Karlovy Vary International Film Festival',2005);
INSERT INTO `` (`TitIngles`,`Premios`,`Festival`,`Ano`) VALUES ('The Incredibles','Best Actor','Locarno Film Festival',2022);
INSERT INTO `` (`TitIngles`,`Premios`,`Festival`,`Ano`) VALUES ('The Grand Budapest Hotel','Best Director','Palm Springs International Film Festival',2014);
INSERT INTO `` (`TitIngles`,`Premios`,`Festival`,`Ano`) VALUES ('Jurassic Park','Best Visual Effects','San SebastiÃ¡n International Film Festival',2006);
INSERT INTO `` (`TitIngles`,`Premios`,`Festival`,`Ano`) VALUES ('Harry Potter and the Goblet of Fire','Best Actress','Cairo International Film Festival',2020);
INSERT INTO `` (`TitIngles`,`Premios`,`Festival`,`Ano`) VALUES ('The Godfather: Part III','Best Original Screenplay','Mar del Plata International Film Festival',2012);
INSERT INTO `` (`TitIngles`,`Premios`,`Festival`,`Ano`) VALUES ('The Truman Show','Best Picture','Mumbai Film Festival (MAMI)',2018);
INSERT INTO `` (`TitIngles`,`Premios`,`Festival`,`Ano`) VALUES ('The Godfather: Part II','Best Director','Cannes Film Festival',2015);
INSERT INTO `` (`TitIngles`,`Premios`,`Festival`,`Ano`) VALUES ('The Wizard of Oz','Best Picture','Sundance Film Festival',2011);
INSERT INTO `` (`TitIngles`,`Premios`,`Festival`,`Ano`) VALUES ('The Avengers','Best Supporting Actress','Venice Film Festival',2009);
INSERT INTO `` (`TitIngles`,`Premios`,`Festival`,`Ano`) VALUES ('Inside Out','Best Visual Effects','Berlin International Film Festival',2004);
INSERT INTO `` (`TitIngles`,`Premios`,`Festival`,`Ano`) VALUES ('Captain America','Best Supporting Actress','Toronto International Film Festival',2003);
INSERT INTO `` (`TitIngles`,`Premios`,`Festival`,`Ano`) VALUES ('The Godfather','Best Cinematography','BFI London Film Festival',2008);
INSERT INTO `` (`TitIngles`,`Premios`,`Festival`,`Ano`) VALUES ('Harry Potter and the Order of the Phoenix','Best Supporting Actress','SXSW Film Festival',2000);
INSERT INTO `` (`TitIngles`,`Premios`,`Festival`,`Ano`) VALUES ('Avengers: Endgame','Best Director','Tokyo International Film Festival',2023);
INSERT INTO `` (`TitIngles`,`Premios`,`Festival`,`Ano`) VALUES ('Avengers: Infinity War','Best Director','Busan International Film Festival',2017);
INSERT INTO `` (`TitIngles`,`Premios`,`Festival`,`Ano`) VALUES ('Saving Private Ryan','Best Director','Sydney Film Festival',2002);
INSERT INTO `` (`TitIngles`,`Premios`,`Festival`,`Ano`) VALUES ('The Princess Bride','Best Cinematography','Shanghai International Film Festival',2022);
INSERT INTO `` (`TitIngles`,`Premios`,`Festival`,`Ano`) VALUES ('Mulan','Best Actor','Moscow International Film Festival',2010);
INSERT INTO `` (`TitIngles`,`Premios`,`Festival`,`Ano`) VALUES ('Mulan','Best Supporting Actress','Karlovy Vary International Film Festival',2014);
INSERT INTO `` (`TitIngles`,`Premios`,`Festival`,`Ano`) VALUES ('2001: A Space Odyssey','Best Visual Effects','Palm Springs International Film Festival',2015);
INSERT INTO `` (`TitIngles`,`Premios`,`Festival`,`Ano`) VALUES ('The Lord of the Rings: The Fellowship of the Ring','Best Supporting Actress','San SebastiÃ¡n International Film Festival',2019);
INSERT INTO `` (`TitIngles`,`Premios`,`Festival`,`Ano`) VALUES ('The Breakfast Club','Best Visual Effects','Cairo International Film Festival',2005);
INSERT INTO `` (`TitIngles`,`Premios`,`Festival`,`Ano`) VALUES ('Pulp Fiction','Best Supporting Actress','Mar del Plata International Film Festival',2018);
INSERT INTO `` (`TitIngles`,`Premios`,`Festival`,`Ano`) VALUES ('The Sixth Sense','Best Director','Mumbai Film Festival (MAMI)',2016);
INSERT INTO `` (`TitIngles`,`Premios`,`Festival`,`Ano`) VALUES ('2001: A Space Odyssey','Best Director','Cannes Film Festival',2011);
INSERT INTO `` (`TitIngles`,`Premios`,`Festival`,`Ano`) VALUES ('Titanic','Best Actress','Sundance Film Festival',2007);
INSERT INTO `` (`TitIngles`,`Premios`,`Festival`,`Ano`) VALUES ('Star Wars: Episode IV - A New Hope','Best Actor','Venice Film Festival',2021);
INSERT INTO `` (`TitIngles`,`Premios`,`Festival`,`Ano`) VALUES ('The Hateful Eight','Best Director','Berlin International Film Festival',2013);
INSERT INTO `` (`TitIngles`,`Premios`,`Festival`,`Ano`) VALUES ('Star Wars: Episode I - The Phantom Menace','Best Actor','Toronto International Film Festival',2012);
INSERT INTO `` (`TitIngles`,`Premios`,`Festival`,`Ano`) VALUES ('The Lord of the Rings: The Return of the King','Best Actress','Tribeca Film Festival',2003);
INSERT INTO `` (`TitIngles`,`Premios`,`Festival`,`Ano`) VALUES ('Star Wars: Episode II - Attack of the Clones','Best Director','BFI London Film Festival',2001);
INSERT INTO `` (`TitIngles`,`Premios`,`Festival`,`Ano`) VALUES ('The Matrix','Best Picture','SXSW Film Festival',2008);
INSERT INTO `` (`TitIngles`,`Premios`,`Festival`,`Ano`) VALUES ('The Iron Giant','Best Cinematography','Tokyo International Film Festival',2020);
INSERT INTO `` (`TitIngles`,`Premios`,`Festival`,`Ano`) VALUES ('Star Wars: Episode III - Revenge of the Sith','Best Visual Effects','Sydney Film Festival',2023);
INSERT INTO `` (`TitIngles`,`Premios`,`Festival`,`Ano`) VALUES ('The Exorcist','Best Original Screenplay','Shanghai International Film Festival',2009);
INSERT INTO `` (`TitIngles`,`Premios`,`Festival`,`Ano`) VALUES ('The Lord of the Rings: The Fellowship of the Ring','Best Picture','Moscow International Film Festival',2004);
INSERT INTO `` (`TitIngles`,`Premios`,`Festival`,`Ano`) VALUES ('Goodfellas','Best Visual Effects','Karlovy Vary International Film Festival',2017);
INSERT INTO `` (`TitIngles`,`Premios`,`Festival`,`Ano`) VALUES ('Django Unchained','Best Picture','Locarno Film Festival',2010);
INSERT INTO `` (`TitIngles`,`Premios`,`Festival`,`Ano`) VALUES ('Nemo','Best Visual Effects','Palm Springs International Film Festival',2021);
INSERT INTO `` (`TitIngles`,`Premios`,`Festival`,`Ano`) VALUES ('The Little Mermaid','Best Picture','San SebastiÃ¡n International Film Festival',2002);
INSERT INTO `` (`TitIngles`,`Premios`,`Festival`,`Ano`) VALUES ('The Others','Best Actress','Cairo International Film Festival',2016);
INSERT INTO `` (`TitIngles`,`Premios`,`Festival`,`Ano`) VALUES ('Signs','Best Picture','Mar del Plata International Film Festival',2013);
INSERT INTO `` (`TitIngles`,`Premios`,`Festival`,`Ano`) VALUES ('The Shawshank Redemption','Best Adapted Screenplay','Mumbai Film Festival (MAMI)',2006);
INSERT INTO `` (`TitIngles`,`Premios`,`Festival`,`Ano`) VALUES ('Toy Story','Best Supporting Actor','Cannes Film Festival',2014);
INSERT INTO `` (`TitIngles`,`Premios`,`Festival`,`Ano`) VALUES ('The Silence of the Lambs','Best Picture','Sundance Film Festival',2018);
INSERT INTO `` (`TitIngles`,`Premios`,`Festival`,`Ano`) VALUES ('Star Wars: Episode V - The Empire Strikes Back','Best Visual Effects','Venice Film Festival',2015);
INSERT INTO `` (`TitIngles`,`Premios`,`Festival`,`Ano`) VALUES ('Star Wars: Episode VI - Return of the Jedi','Best Actor','Berlin International Film Festival',2000);
INSERT INTO `` (`TitIngles`,`Premios`,`Festival`,`Ano`) VALUES ('The Incredibles','Best Actress','Toronto International Film Festival',2012);
INSERT INTO `` (`TitIngles`,`Premios`,`Festival`,`Ano`) VALUES ('The Grand Budapest Hotel','Best Actor','Tribeca Film Festival',2011);
INSERT INTO `` (`TitIngles`,`Premios`,`Festival`,`Ano`) VALUES ('Jurassic Park','Best Supporting Actress','BFI London Film Festival',2007);
INSERT INTO `` (`TitIngles`,`Premios`,`Festival`,`Ano`) VALUES ('Harry Potter and the Goblet of Fire','Best Supporting Actor','SXSW Film Festival',2022);
INSERT INTO `` (`TitIngles`,`Premios`,`Festival`,`Ano`) VALUES ('The Godfather: Part III','Best Supporting Actor','Tokyo International Film Festival',2008);
INSERT INTO `` (`TitIngles`,`Premios`,`Festival`,`Ano`) VALUES ('The Truman Show','Best Adapted Screenplay','Busan International Film Festival',2005);
INSERT INTO `` (`TitIngles`,`Premios`,`Festival`,`Ano`) VALUES ('The Godfather: Part II','Best Original Screenplay','Sydney Film Festival',2003);
INSERT INTO `` (`TitIngles`,`Premios`,`Festival`,`Ano`) VALUES ('The Wizard of Oz','Best Actor','Shanghai International Film Festival',2020);
INSERT INTO `` (`TitIngles`,`Premios`,`Festival`,`Ano`) VALUES ('The Avengers','Best Picture','Moscow International Film Festival',2019);
INSERT INTO `` (`TitIngles`,`Premios`,`Festival`,`Ano`) VALUES ('Inside Out','Best Supporting Actor','Karlovy Vary International Film Festival',2016);
INSERT INTO `` (`TitIngles`,`Premios`,`Festival`,`Ano`) VALUES ('Captain America','Best Supporting Actress','Locarno Film Festival',2014);
INSERT INTO `` (`TitIngles`,`Premios`,`Festival`,`Ano`) VALUES ('The Departed','Best Visual Effects','Palm Springs International Film Festival',2010);
INSERT INTO `` (`TitIngles`,`Premios`,`Festival`,`Ano`) VALUES ('The Godfather','Best Supporting Actress','San SebastiÃ¡n International Film Festival',2009);
INSERT INTO `` (`TitIngles`,`Premios`,`Festival`,`Ano`) VALUES ('Harry Potter and the Order of the Phoenix','Best Adapted Screenplay','Cairo International Film Festival',2018);
INSERT INTO `` (`TitIngles`,`Premios`,`Festival`,`Ano`) VALUES ('Avengers: Endgame','Best Director','Mar del Plata International Film Festival',2012);
INSERT INTO `` (`TitIngles`,`Premios`,`Festival`,`Ano`) VALUES ('Avengers: Infinity War','Best Supporting Actress','Mumbai Film Festival (MAMI)',2006);
